esphome:
  name: ${devicename}
  friendly_name: ${friendly_name}

esp32:
  board: esp32dev
  framework:
    type: esp-idf

logger:
  level: DEBUG
  initial_level: INFO
  baud_rate: 115200

api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "PV-DG Fallback"
    password: !secret fallback_ap_password

captive_portal:

web_server:
  port: 80
  version: 3
  sorting_groups:
    - id: grp_overview
      name: "Overview"
      sorting_weight: 10
    - id: grp_control
      name: "Control"
      sorting_weight: 20
    - id: grp_grid
      name: "Grid Meter"
      sorting_weight: 30
    - id: grp_inverter
      name: "Huawei Inverter"
      sorting_weight: 40
    - id: grp_energy
      name: "Energy"
      sorting_weight: 50
    - id: grp_service
      name: "Service"
      sorting_weight: 60
    - id: grp_io
      name: "I/O"
      sorting_weight: 70
    - id: grp_debug
      name: "Debug"
      sorting_weight: 80

uart:
  - id: rs485
    tx_pin: GPIO27
    rx_pin: GPIO14
    baud_rate: 9600
    data_bits: 8
    parity: NONE
    stop_bits: 1

modbus:
  - id: plant_bus
    uart_id: rs485
    send_wait_time: 400ms

globals:
  - id: pv_cmd_percent_internal
    type: float
    restore_value: yes
    initial_value: "0.0"
  - id: pv_cmd_kw_internal
    type: float
    restore_value: no
    initial_value: "0.0"
  - id: control_error_kw
    type: float
    restore_value: no
    initial_value: "0.0"
  - id: filtered_grid_kw
    type: float
    restore_value: no
    initial_value: "0.0"
  - id: grid_seen
    type: bool
    restore_value: no
    initial_value: "false"
  - id: inverter_seen
    type: bool
    restore_value: no
    initial_value: "false"

modbus_controller:
  - id: grid_meter
    modbus_id: plant_bus
    address: 1
    setup_priority: -10
    update_interval: 3s
    command_throttle: 150ms
    offline_skip_updates: 3

  - id: solar_inverter
    modbus_id: plant_bus
    address: 10
    setup_priority: -10
    update_interval: 3s
    command_throttle: 350ms
    offline_skip_updates: 3
    
text_sensor:
  - platform: wifi_info
    ip_address:
      id: ip_addr
      name: "IP Address"
    ssid:
      id: wifi_ssid_sensor
      name: "WiFi SSID"
    bssid:
      id: wifi_bssid_sensor
      name: "WiFi BSSID"
    mac_address:
      id: wifi_mac_sensor
      name: "WiFi MAC"