sensor:
  - platform: modbus_controller
    modbus_controller_id: solar_inverter_3
    id: inverter3_pmax_kw
    name: "Inverter 3 Pmax"
    register_type: read
    address: 30083
    value_type: U_DWORD
    unit_of_measurement: "kW"
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
    on_value:
      - lambda: "id(inverter3_seen) = true;"
    web_server:
      sorting_group_id: grp_inverter
      sorting_weight: 120

  - platform: modbus_controller
    modbus_controller_id: solar_inverter_3
    id: inverter3_actual_kw
    name: "Inverter 3 Actual Power"
    register_type: read
    address: 32080
    value_type: S_DWORD
    unit_of_measurement: "kW"
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
    on_value:
      - lambda: "id(inverter3_seen) = true;"
    web_server:
      sorting_group_id: grp_inverter
      sorting_weight: 121
