i2c:
  id: bus_a
  sda: GPIO4
  scl:
    number: GPIO15
    ignore_strapping_warning: true
  scan: true

pcf8574:
  - id: pcf_out
    address: 0x24
  - id: pcf_in
    address: 0x22

switch:
  - platform: gpio
    id: relay_1
    name: "Relay 1"
    pin:
      pcf8574: pcf_out
      number: 0
      mode: OUTPUT
      inverted: true
    web_server:
      sorting_group_id: grp_io
      sorting_weight: 10

  - platform: gpio
    id: relay_2
    name: "Relay 2"
    pin:
      pcf8574: pcf_out
      number: 1
      mode: OUTPUT
      inverted: true
    web_server:
      sorting_group_id: grp_io
      sorting_weight: 11

  - platform: gpio
    id: relay_3
    name: "Relay 3"
    pin:
      pcf8574: pcf_out
      number: 2
      mode: OUTPUT
      inverted: true
    web_server:
      sorting_group_id: grp_io
      sorting_weight: 12

  - platform: gpio
    id: relay_4
    name: "Relay 4"
    pin:
      pcf8574: pcf_out
      number: 3
      mode: OUTPUT
      inverted: true
    web_server:
      sorting_group_id: grp_io
      sorting_weight: 13

  - platform: gpio
    id: relay_5
    name: "Relay 5"
    pin:
      pcf8574: pcf_out
      number: 4
      mode: OUTPUT
      inverted: true
    web_server:
      sorting_group_id: grp_io
      sorting_weight: 14

  - platform: gpio
    id: relay_6
    name: "Relay 6"
    pin:
      pcf8574: pcf_out
      number: 5
      mode: OUTPUT
      inverted: true
    web_server:
      sorting_group_id: grp_io
      sorting_weight: 15

binary_sensor:
  - platform: status
    name: "ESP Online"
    web_server:
      sorting_group_id: grp_debug
      sorting_weight: 1

  - platform: gpio
    name: "Input 1"
    pin:
      pcf8574: pcf_in
      number: 0
      mode: INPUT
      inverted: true
    web_server:
      sorting_group_id: grp_io
      sorting_weight: 20

  - platform: gpio
    name: "Input 2"
    pin:
      pcf8574: pcf_in
      number: 1
      mode: INPUT
      inverted: true
    web_server:
      sorting_group_id: grp_io
      sorting_weight: 21

  - platform: gpio
    name: "Input 3"
    pin:
      pcf8574: pcf_in
      number: 2
      mode: INPUT
      inverted: true
    web_server:
      sorting_group_id: grp_io
      sorting_weight: 22

  - platform: gpio
    name: "Input 4"
    pin:
      pcf8574: pcf_in
      number: 3
      mode: INPUT
      inverted: true
    web_server:
      sorting_group_id: grp_io
      sorting_weight: 23

  - platform: gpio
    name: "Input 5"
    pin:
      pcf8574: pcf_in
      number: 4
      mode: INPUT
      inverted: true
    web_server:
      sorting_group_id: grp_io
      sorting_weight: 24

  - platform: gpio
    name: "Input 6"
    pin:
      pcf8574: pcf_in
      number: 5
      mode: INPUT
      inverted: true
    web_server:
      sorting_group_id: grp_io
      sorting_weight: 25