import type { DriverRegister } from '../driverStore.js';

export const cpsChintRegisters: DriverRegister[] = [
  { paramKey: "device", label: "Device", registerType: "holding", address: 0, valueKind: "U_WORD" },
  { paramKey: "reserve", label: "Reserve", registerType: "holding", address: 1, valueKind: "U_WORD" },
  { paramKey: "reserve_2", label: "Reserve", registerType: "holding", address: 2, valueKind: "U_WORD" },
  { paramKey: "regnum", label: "RegNum", registerType: "holding", address: 3, valueKind: "U_WORD" },
  { paramKey: "rwregsum", label: "RWRegSum", registerType: "holding", address: 20, valueKind: "U_WORD" },
  { paramKey: "rwregadd", label: "RWRegAdd", registerType: "holding", address: 21, valueKind: "U_WORD" },
  { paramKey: "tyield", label: "TYield", unit: "kWh", registerType: "holding", address: 22, valueKind: "U_DWORD" },
  { paramKey: "dyield", label: "DYield", unit: "kWh", registerType: "holding", address: 24, valueKind: "U_WORD", scale: 0.1 },
  { paramKey: "eff", label: "Eff", unit: "%", registerType: "holding", address: 25, valueKind: "U_WORD", scale: 0.1 },
  { paramKey: "pf", label: "PF", registerType: "holding", address: 26, valueKind: "S_WORD", scale: 0.001 },
  { paramKey: "pmax", label: "Pmax", unit: "kW", registerType: "holding", address: 27, valueKind: "U_WORD", scale: 0.1 },
  { paramKey: "runt", label: "RunT", unit: "Min", registerType: "holding", address: 28, valueKind: "U_WORD", scale: 0.1 },
  { paramKey: "pac", label: "Pac", unit: "kW", registerType: "holding", address: 29, valueKind: "U_WORD", scale: 0.1 },
  { paramKey: "uab", label: "Uab", unit: "V", registerType: "holding", address: 31, valueKind: "U_WORD", scale: 0.1 },
  { paramKey: "ubc", label: "Ubc", unit: "V", registerType: "holding", address: 32, valueKind: "U_WORD", scale: 0.1 },
  { paramKey: "uca", label: "Uca", unit: "V", registerType: "holding", address: 33, valueKind: "U_WORD", scale: 0.1 },
  { paramKey: "ia", label: "Ia", unit: "A", registerType: "holding", address: 34, valueKind: "U_WORD", scale: 0.1 },
  { paramKey: "ib", label: "Ib", unit: "A", registerType: "holding", address: 35, valueKind: "U_WORD", scale: 0.1 },
  { paramKey: "ic", label: "Ic", unit: "A", registerType: "holding", address: 36, valueKind: "U_WORD", scale: 0.1 },
  { paramKey: "upv1", label: "Upv1", unit: "V", registerType: "holding", address: 37, valueKind: "U_WORD", scale: 0.1 },
  { paramKey: "ipv1", label: "Ipv1", unit: "A", registerType: "holding", address: 38, valueKind: "S_WORD", scale: 0.1 },
  { paramKey: "freq", label: "Freq", unit: "Hz", registerType: "holding", address: 43, valueKind: "U_WORD", scale: 0.1 },
  { paramKey: "tmod", label: "Tmod", unit: "C", registerType: "holding", address: 44, valueKind: "S_WORD", scale: 0.1 },
  { paramKey: "tamb", label: "Tamb", unit: "C", registerType: "holding", address: 45, valueKind: "S_WORD", scale: 0.1 },
  { paramKey: "mode", label: "Mode", registerType: "holding", address: 47, valueKind: "U_WORD" },
  { paramKey: "time", label: "Time", registerType: "holding", address: 48, valueKind: "U_QWORD" },
  { paramKey: "pfault", label: "PFault", registerType: "holding", address: 52, valueKind: "U_WORD" },
  { paramKey: "warn", label: "Warn", registerType: "holding", address: 53, valueKind: "U_WORD" },
  { paramKey: "fault0", label: "Fault0", registerType: "holding", address: 54, valueKind: "U_WORD" },
  { paramKey: "fault1", label: "Fault1", registerType: "holding", address: 55, valueKind: "U_WORD" },
  { paramKey: "fault2", label: "Fault2", registerType: "holding", address: 56, valueKind: "U_WORD" },
  { paramKey: "fault3", label: "Fault3", registerType: "holding", address: 57, valueKind: "U_WORD" },
  { paramKey: "fault4", label: "Fault4", registerType: "holding", address: 58, valueKind: "U_WORD" },
  { paramKey: "qac", label: "Qac", unit: "kvar", registerType: "holding", address: 59, valueKind: "S_WORD", scale: 0.1 },
  { paramKey: "reserve_3", label: "Reserve", registerType: "holding", address: 60, valueKind: "U_WORD" },
  { paramKey: "reserve_4", label: "Reserve", registerType: "holding", address: 61, valueKind: "U_WORD" },
  { paramKey: "reserve_5", label: "Reserve", registerType: "holding", address: 62, valueKind: "U_WORD" },
  { paramKey: "reserve_6", label: "Reserve", registerType: "holding", address: 63, valueKind: "U_WORD" },
  { paramKey: "reserve_7", label: "Reserve", registerType: "holding", address: 64, valueKind: "U_WORD" },
  { paramKey: "majorver", label: "MajorVer", registerType: "holding", address: 65, valueKind: "U_WORD" },
  { paramKey: "buscapacitance", label: "BusCapacitance", unit: "uF", registerType: "holding", address: 67, valueKind: "S_WORD" },
  { paramKey: "accapacitance", label: "AcCapacitance", unit: "uF", registerType: "holding", address: 68, valueKind: "S_WORD" },
  { paramKey: "pdc", label: "Pdc", unit: "kW", registerType: "holding", address: 69, valueKind: "U_WORD", scale: 0.1 },
  { paramKey: "pmaxlim", label: "PmaxLim", unit: "kW", registerType: "holding", address: 70, valueKind: "U_WORD" },
  { paramKey: "frequency", label: "Frequency", unit: "Hz", registerType: "holding", address: 1018, valueKind: "U_DWORD", scale: 0.1 },
  { paramKey: "onoff", label: "OnOff", registerType: "holding", address: 4096, valueKind: "U_WORD" },
  { paramKey: "pset", label: "PSet", registerType: "holding", address: 4097, valueKind: "U_WORD", scale: 0.1 },
  { paramKey: "qset", label: "QSet", registerType: "holding", address: 4099, valueKind: "S_WORD", scale: 0.1 },
  { paramKey: "timeset", label: "TimeSet", registerType: "holding", address: 4100, valueKind: "U_QWORD" },
  { paramKey: "gridfrqmax1", label: "GridFrqMax1", unit: "Hz", registerType: "holding", address: 8207, valueKind: "U_WORD", scale: 0.01 },
  { paramKey: "gridfrqmax2", label: "GridFrqMax2", unit: "Hz", registerType: "holding", address: 8209, valueKind: "U_WORD", scale: 0.01 },
  { paramKey: "gridfrqmax3", label: "GridFrqMax3", unit: "Hz", registerType: "holding", address: 8211, valueKind: "U_WORD", scale: 0.01 },
  { paramKey: "gridfrqmin1", label: "GridFrqMin1", unit: "Hz", registerType: "holding", address: 8213, valueKind: "U_WORD", scale: 0.01 },
  { paramKey: "gridfrqmin2", label: "GridFrqMin2", unit: "Hz", registerType: "holding", address: 8215, valueKind: "U_WORD", scale: 0.01 },
  { paramKey: "gridfrqmin3", label: "GridFrqMin3", unit: "Hz", registerType: "holding", address: 8217, valueKind: "U_WORD", scale: 0.01 },
  { paramKey: "frqmax", label: "FrqMax", unit: "Hz", registerType: "holding", address: 8219, valueKind: "U_WORD", scale: 0.01 },
  { paramKey: "frqmin", label: "FrqMin", unit: "Hz", registerType: "holding", address: 8220, valueKind: "U_WORD", scale: 0.01 },
  { paramKey: "frqrecoveryt", label: "FrqRecoveryT", unit: "s", registerType: "holding", address: 8221, valueKind: "U_WORD", scale: 0.01 },
  { paramKey: "maxtript", label: "MaxTripT", unit: "s", registerType: "holding", address: 8223, valueKind: "U_WORD", scale: 0.01 },
  { paramKey: "mintript", label: "MinTripT", unit: "s", registerType: "holding", address: 8225, valueKind: "U_WORD", scale: 0.01 },
  { paramKey: "pvgridvpeakdif", label: "PvGridVPeakDif", unit: "V", registerType: "holding", address: 8230, valueKind: "U_WORD" },
  { paramKey: "ovrfrqmin", label: "OvrFrqMin", unit: "Hz", registerType: "holding", address: 8452, valueKind: "U_WORD", scale: 0.01 },
  { paramKey: "ovrfrqmax", label: "OvrFrqMax", unit: "Hz", registerType: "holding", address: 8453, valueKind: "U_WORD", scale: 0.01 },
  { paramKey: "ovrfrqslop", label: "OvrFrqSlop", unit: "%", registerType: "holding", address: 8454, valueKind: "U_WORD", scale: 0.01 },
  { paramKey: "recoveryfrq", label: "RecoveryFrq", unit: "Hz", registerType: "holding", address: 8455, valueKind: "U_WORD", scale: 0.01 },
  { paramKey: "vwcurvev1", label: "VwCurveV1", unit: "%", registerType: "holding", address: 8465, valueKind: "U_WORD", scale: 0.01 },
  { paramKey: "vwcurvep1", label: "VwCurveP1", unit: "%", registerType: "holding", address: 8466, valueKind: "U_WORD", scale: 0.1 },
  { paramKey: "vwcurvev2", label: "VwCurveV2", unit: "%", registerType: "holding", address: 8467, valueKind: "U_WORD", scale: 0.01 },
  { paramKey: "vwcurvep2", label: "VwCurveP2", unit: "%", registerType: "holding", address: 8468, valueKind: "U_WORD", scale: 0.1 },
  { paramKey: "gridvopenlprespt", label: "GridVOpenLpRespT", unit: "s", registerType: "holding", address: 8469, valueKind: "U_WORD", scale: 0.1 },
  { paramKey: "freqdroop_dbuf", label: "FreqDroop_DbUf", unit: "Hz", registerType: "holding", address: 8472, valueKind: "U_WORD", scale: 0.001 },
  { paramKey: "freqdroop_kof", label: "FreqDroop_KOf", registerType: "holding", address: 8473, valueKind: "U_WORD", scale: 0.01 },
  { paramKey: "freqdroop_kuf", label: "FreqDroop_KUf", registerType: "holding", address: 8474, valueKind: "U_WORD", scale: 0.01 },
  { paramKey: "freqdroop_rsptms", label: "FreqDroop_RspTms", unit: "S", registerType: "holding", address: 8475, valueKind: "U_WORD", scale: 0.1 },
  { paramKey: "pfpcurvep1", label: "PFpCurveP1", unit: "%", registerType: "holding", address: 8705, valueKind: "U_WORD", scale: 0.1 },
  { paramKey: "pfpcurvep2", label: "PFpCurveP2", unit: "%", registerType: "holding", address: 8707, valueKind: "U_WORD", scale: 0.1 },
  { paramKey: "qucurveu1", label: "QuCurveU1", unit: "%", registerType: "holding", address: 8711, valueKind: "U_WORD", scale: 0.01 },
  { paramKey: "qucurveq1", label: "QuCurveQ1", unit: "%", registerType: "holding", address: 8712, valueKind: "S_WORD", scale: 0.1 },
  { paramKey: "qucurveu2", label: "QuCurveU2", unit: "%", registerType: "holding", address: 8713, valueKind: "U_WORD", scale: 0.01 },
  { paramKey: "qucurveq2", label: "QuCurveQ2", unit: "%", registerType: "holding", address: 8714, valueKind: "S_WORD", scale: 0.1 },
  { paramKey: "qucurveu1i", label: "QuCurveU1i", unit: "%", registerType: "holding", address: 8715, valueKind: "U_WORD", scale: 0.01 },
  { paramKey: "qucurveq1i", label: "QuCurveQ1i", unit: "%", registerType: "holding", address: 8716, valueKind: "S_WORD", scale: 0.1 },
  { paramKey: "qucurveu2i", label: "QuCurveU2i", unit: "%", registerType: "holding", address: 8717, valueKind: "U_WORD", scale: 0.01 },
  { paramKey: "qucurveq2i", label: "QuCurveQ2i", unit: "%", registerType: "holding", address: 8718, valueKind: "S_WORD", scale: 0.1 },
  { paramKey: "qucurvetripower", label: "QuCurveTriPower", unit: "%", registerType: "holding", address: 8719, valueKind: "U_WORD", scale: 0.1 },
  { paramKey: "qucurveundopower", label: "QuCurveUndoPower", unit: "%", registerType: "holding", address: 8720, valueKind: "U_WORD", scale: 0.1 },
  { paramKey: "activereaccurvep1", label: "ActiveReacCurveP1", unit: "%", registerType: "holding", address: 8721, valueKind: "U_WORD", scale: 0.1 },
  { paramKey: "activereaccurveq1", label: "ActiveReacCurveQ1", unit: "%", registerType: "holding", address: 8722, valueKind: "S_WORD", scale: 0.1 },
  { paramKey: "activereaccurvep2", label: "ActiveReacCurveP2", unit: "%", registerType: "holding", address: 8723, valueKind: "U_WORD", scale: 0.1 },
  { paramKey: "activereaccurveq2", label: "ActiveReacCurveQ2", unit: "%", registerType: "holding", address: 8724, valueKind: "S_WORD", scale: 0.1 },
  { paramKey: "activereaccurvep3", label: "ActiveReacCurveP3", unit: "%", registerType: "holding", address: 8725, valueKind: "U_WORD", scale: 0.1 },
  { paramKey: "activereaccurveq3", label: "ActiveReacCurveQ3", unit: "%", registerType: "holding", address: 8726, valueKind: "S_WORD", scale: 0.1 },
  { paramKey: "qucurvevref", label: "QuCurveVref", unit: "%", registerType: "holding", address: 8728, valueKind: "U_WORD", scale: 0.01 },
  { paramKey: "qucrvvrefadjstt", label: "QuCrvVrefAdjstT", unit: "s", registerType: "holding", address: 8729, valueKind: "U_WORD" },
  { paramKey: "qucrvopenloopt", label: "QuCrvOpenLoopT", unit: "s", registerType: "holding", address: 8730, valueKind: "U_WORD", scale: 0.1 },
  { paramKey: "bandwidth1", label: "Bandwidth1", unit: "K", registerType: "holding", address: 8960, valueKind: "U_WORD" },
  { paramKey: "startfrq1", label: "StartFrq1", unit: "K", registerType: "holding", address: 8961, valueKind: "U_WORD" },
  { paramKey: "proportion1", label: "Proportion1", registerType: "holding", address: 8962, valueKind: "U_WORD" },
  { paramKey: "filter1", label: "Filter1", unit: "%", registerType: "holding", address: 8963, valueKind: "U_WORD" },
  { paramKey: "threshold1", label: "Threshold1", unit: "dB", registerType: "holding", address: 8964, valueKind: "U_WORD" },
  { paramKey: "sigperapdlmt1", label: "SigPerApdLmt1", unit: "dB", registerType: "holding", address: 8965, valueKind: "U_WORD" },
  { paramKey: "bandwidth2", label: "Bandwidth2", unit: "K", registerType: "holding", address: 8966, valueKind: "U_WORD" },
  { paramKey: "startfrq2", label: "StartFrq2", unit: "K", registerType: "holding", address: 8967, valueKind: "U_WORD" },
  { paramKey: "proportion2", label: "Proportion2", registerType: "holding", address: 8968, valueKind: "U_WORD" },
  { paramKey: "filter2", label: "Filter2", unit: "%", registerType: "holding", address: 8969, valueKind: "U_WORD" },
  { paramKey: "threshold2", label: "Threshold2", unit: "dB", registerType: "holding", address: 8970, valueKind: "U_WORD" },
  { paramKey: "sigperapdlmt2", label: "SigPerApdLmt2", unit: "dB", registerType: "holding", address: 8971, valueKind: "U_WORD" },
  { paramKey: "bandwidth1base", label: "Bandwidth1base", unit: "K", registerType: "holding", address: 8972, valueKind: "U_WORD" },
  { paramKey: "bandwidth2base", label: "Bandwidth2base", unit: "K", registerType: "holding", address: 8973, valueKind: "U_WORD" },
  { paramKey: "lvrttime1", label: "LVRTTime1", unit: "S", registerType: "holding", address: 9217, valueKind: "U_WORD", scale: 0.01 },
  { paramKey: "lvrttime2", label: "LVRTTime2", unit: "S", registerType: "holding", address: 9219, valueKind: "U_WORD", scale: 0.01 },
  { paramKey: "lvrttime3", label: "LVRTTime3", unit: "S", registerType: "holding", address: 9221, valueKind: "U_WORD", scale: 0.01 },
  { paramKey: "lvrttime4", label: "LVRTTime4", unit: "S", registerType: "holding", address: 9223, valueKind: "U_WORD", scale: 0.01 },
  { paramKey: "lvrttime5", label: "LVRTTime5", unit: "S", registerType: "holding", address: 9225, valueKind: "U_WORD", scale: 0.01 },
  { paramKey: "lvrttime6", label: "LVRTTime6", unit: "S", registerType: "holding", address: 9227, valueKind: "U_WORD", scale: 0.01 },
  { paramKey: "lvrttime7", label: "LVRTTime7", unit: "S", registerType: "holding", address: 9229, valueKind: "U_WORD", scale: 0.01 },
  { paramKey: "lvrttime8", label: "LVRTTime8", unit: "S", registerType: "holding", address: 9231, valueKind: "U_WORD", scale: 0.01 },
  { paramKey: "hvrttime1", label: "HVRTTime1", unit: "S", registerType: "holding", address: 9233, valueKind: "U_WORD", scale: 0.01 },
  { paramKey: "hvrttime2", label: "HVRTTime2", unit: "S", registerType: "holding", address: 9235, valueKind: "U_WORD", scale: 0.01 },
  { paramKey: "hvrttime3", label: "HVRTTime3", unit: "S", registerType: "holding", address: 9237, valueKind: "U_WORD", scale: 0.01 },
  { paramKey: "hvrttime4", label: "HVRTTime4", unit: "S", registerType: "holding", address: 9239, valueKind: "U_WORD", scale: 0.01 },
  { paramKey: "hvrttime5", label: "HVRTTime5", unit: "S", registerType: "holding", address: 9241, valueKind: "U_WORD", scale: 0.01 },
  { paramKey: "hvrttime6", label: "HVRTTime6", unit: "S", registerType: "holding", address: 9243, valueKind: "U_WORD", scale: 0.01 },
  { paramKey: "hvrttime7", label: "HVRTTime7", unit: "S", registerType: "holding", address: 9245, valueKind: "U_WORD", scale: 0.01 },
  { paramKey: "hvrttime8", label: "HVRTTime8", unit: "S", registerType: "holding", address: 9247, valueKind: "U_WORD", scale: 0.01 },
  { paramKey: "powerondelay", label: "PowerOnDelay", unit: "s", registerType: "holding", address: 9472, valueKind: "U_WORD" },
  { paramKey: "pvslowstartpwdelta", label: "PVSlowStartPwDelta", unit: "%", registerType: "holding", address: 9474, valueKind: "U_WORD", scale: 0.01 },
  { paramKey: "errsoftstartt", label: "ErrSoftStartT", unit: "s", registerType: "holding", address: 9475, valueKind: "U_WORD" },
  { paramKey: "normsoftstopt", label: "NormSoftStopT", unit: "s", registerType: "holding", address: 9476, valueKind: "U_WORD" },
  { paramKey: "normsoftstartt", label: "NormSoftStartT", unit: "s", registerType: "holding", address: 9477, valueKind: "U_WORD" },
  { paramKey: "normderatingstep", label: "NormDeratingStep", unit: "%", registerType: "holding", address: 9478, valueKind: "U_WORD", scale: 0.01 },
  { paramKey: "lvrtpstreactivei", label: "LVRTPstReactiveI", unit: "%", registerType: "holding", address: 9484, valueKind: "U_WORD", scale: 0.1 },
  { paramKey: "lvrtnegreactivei", label: "LVRTNegReactiveI", unit: "%", registerType: "holding", address: 9485, valueKind: "U_WORD", scale: 0.1 },
  { paramKey: "percentage", label: "Percentage", unit: "%", registerType: "holding", address: 9486, valueKind: "U_WORD", scale: 0.1 },
  { paramKey: "percentage_2", label: "Percentage", unit: "%", registerType: "holding", address: 9487, valueKind: "U_WORD", scale: 0.1 },
  { paramKey: "gfcistatict", label: "GFCIStaticT", unit: "s", registerType: "holding", address: 9490, valueKind: "U_WORD", scale: 0.01 },
  { paramKey: "gfcidynprofactor", label: "GFCIDynProFactor", unit: "%", registerType: "holding", address: 9491, valueKind: "U_WORD", scale: 0.1 },
  { paramKey: "dciprotection1", label: "DCIProtection1", unit: "%", registerType: "holding", address: 9492, valueKind: "U_WORD", scale: 0.01 },
  { paramKey: "dciprotectiont1", label: "DCIProtectionT1", unit: "s", registerType: "holding", address: 9493, valueKind: "U_WORD", scale: 0.01 },
  { paramKey: "dciprotection2", label: "DCIProtection2", unit: "mA", registerType: "holding", address: 9494, valueKind: "U_WORD" },
  { paramKey: "dciprotectiont2", label: "DCIProtectionT2", unit: "s", registerType: "holding", address: 9495, valueKind: "U_WORD", scale: 0.01 },
  { paramKey: "duplicationcontrol", label: "DuplicationControl", unit: "%", registerType: "holding", address: 9496, valueKind: "U_WORD" },
  { paramKey: "mpptscanperiod", label: "MPPTScanPeriod", unit: "s", registerType: "holding", address: 9497, valueKind: "U_WORD", scale: 10.0 },
  { paramKey: "phaselosercvcoeff", label: "PhaseLoseRcvCoeff", unit: "%", registerType: "holding", address: 9500, valueKind: "U_WORD", scale: 0.1 },
  { paramKey: "phaselosevunbalance", label: "PhaseLoseVUnbalance", unit: "%", registerType: "holding", address: 9501, valueKind: "U_WORD", scale: 0.01 },
  { paramKey: "pvslowstartstep", label: "PVSlowStartStep", unit: "%", registerType: "holding", address: 9503, valueKind: "U_WORD", scale: 0.01 },
  { paramKey: "phaselosecoeff", label: "PhaseLoseCoeff", unit: "%", registerType: "holding", address: 9528, valueKind: "U_WORD", scale: 0.1 },
  { paramKey: "mpptscanen", label: "MPPTScanEn", registerType: "holding", address: 9731, valueKind: "U_WORD" },
  { paramKey: "arcenable", label: "ARCEnable", registerType: "holding", address: 9732, valueKind: "U_WORD" },
  { paramKey: "arcparagroup", label: "ArcParaGroup", registerType: "holding", address: 9733, valueKind: "U_WORD" },
  { paramKey: "vpvstartupseten", label: "VpvStartUpSetEn", registerType: "holding", address: 9734, valueKind: "U_WORD" },
  { paramKey: "normsoftstoppen", label: "NormSoftStopPEn", registerType: "holding", address: 9738, valueKind: "U_WORD" },
  { paramKey: "gridfrqmax1en", label: "GridFrqMax1En", registerType: "holding", address: 9746, valueKind: "U_WORD" },
  { paramKey: "gridfrqmax2en", label: "GridFrqMax2En", registerType: "holding", address: 9747, valueKind: "U_WORD" },
  { paramKey: "gridfrqmax3en", label: "GridFrqMax3En", registerType: "holding", address: 9748, valueKind: "U_WORD" },
  { paramKey: "gridfrqmin1en", label: "GridFrqMin1En", registerType: "holding", address: 9749, valueKind: "U_WORD" },
  { paramKey: "gridfrqmin2en", label: "GridFrqMin2En", registerType: "holding", address: 9750, valueKind: "U_WORD" },
  { paramKey: "gridfrqmin3en", label: "GridFrqMin3En", registerType: "holding", address: 9751, valueKind: "U_WORD" },
  { paramKey: "gfcistaticen", label: "GFCIStaticEn", registerType: "holding", address: 9754, valueKind: "U_WORD" },
  { paramKey: "gfcidynproen", label: "GFCIDynProEn", registerType: "holding", address: 9755, valueKind: "U_WORD" },
  { paramKey: "dciprotection1en", label: "DCIProtection1En", registerType: "holding", address: 9757, valueKind: "U_WORD" },
  { paramKey: "dciprotection2en", label: "DCIProtection2En", registerType: "holding", address: 9758, valueKind: "U_WORD" },
  { paramKey: "ufderen", label: "UFDerEn", registerType: "holding", address: 9760, valueKind: "U_WORD" },
  { paramKey: "pvslowstartsen", label: "PVSlowStartSEn", registerType: "holding", address: 9762, valueKind: "U_WORD" },
  { paramKey: "isoprotectionen", label: "ISOProtectionEn", registerType: "holding", address: 9763, valueKind: "U_WORD" },
  { paramKey: "fandetect", label: "FANDetect", registerType: "holding", address: 9764, valueKind: "U_WORD" },
  { paramKey: "acspddetectenset", label: "ACSPDDetectEnSet", registerType: "holding", address: 9765, valueKind: "U_WORD" },
  { paramKey: "activepowerover", label: "ActivePowerOver", registerType: "holding", address: 9767, valueKind: "U_WORD" },
  { paramKey: "reactivepowerover", label: "ReactivePowerOver", registerType: "holding", address: 9768, valueKind: "U_WORD" },
  { paramKey: "pwmmodeselect", label: "PWMModeSelect", registerType: "holding", address: 9799, valueKind: "U_WORD" },
  { paramKey: "mpptmodeselect", label: "MPPTModeSelect", registerType: "holding", address: 9800, valueKind: "U_WORD" },
  { paramKey: "poweronoff", label: "PowerOnOff", registerType: "holding", address: 9984, valueKind: "U_WORD" },
  { paramKey: "forcerestart", label: "ForceRestart", registerType: "holding", address: 9985, valueKind: "U_WORD" },
  { paramKey: "factorydefaults", label: "FactoryDefaults", registerType: "holding", address: 9986, valueKind: "U_WORD" },
  { paramKey: "mpptscan", label: "MPPTScan", registerType: "holding", address: 9988, valueKind: "U_WORD" },
  { paramKey: "arcdetect", label: "ARCDetect", registerType: "holding", address: 9989, valueKind: "U_WORD" },
  { paramKey: "arcclear", label: "ARCClear", registerType: "holding", address: 9990, valueKind: "U_WORD" },
  { paramKey: "psetpercentremote", label: "PSetPercentRemote", registerType: "holding", address: 9992, valueKind: "U_WORD", scale: 0.1 },
  { paramKey: "qsetpercentremote", label: "QSetPercentRemote", registerType: "holding", address: 9993, valueKind: "S_WORD", scale: 0.1 },
  { paramKey: "dspfwchksum", label: "DSPFWChkSum", registerType: "holding", address: 10498, valueKind: "U_WORD" },
  { paramKey: "bootfwcodechksum", label: "BootFWCodeChkSum", registerType: "holding", address: 10500, valueKind: "U_WORD" },
  { paramKey: "gridconnectionrule", label: "GridConnectionRule", registerType: "holding", address: 10508, valueKind: "U_WORD" },
  { paramKey: "neutrallinesetting", label: "NeutralLineSetting", registerType: "holding", address: 10509, valueKind: "U_WORD" },
  { paramKey: "pvinputmode", label: "PVInputMode", registerType: "holding", address: 10510, valueKind: "U_WORD" },
  { paramKey: "thisfieldchecksum", label: "ThisfieldCheckSum", registerType: "holding", address: 10513, valueKind: "U_WORD" },
  { paramKey: "dspsafetyver", label: "DspSafetyVer", registerType: "holding", address: 10514, valueKind: "U_WORD" },
  { paramKey: "regunitflag1", label: "RegUnitFlag1", registerType: "holding", address: 10518, valueKind: "U_WORD" },
  { paramKey: "timeset_2", label: "TimeSet", registerType: "holding", address: 11010, valueKind: "U_WORD" },
  { paramKey: "modbusaddr", label: "ModbusAddr", registerType: "holding", address: 11014, valueKind: "U_WORD" },
  { paramKey: "baudrate", label: "BaudRate", registerType: "holding", address: 11015, valueKind: "U_WORD" },
  { paramKey: "compaswd", label: "ComPaswd", registerType: "holding", address: 11016, valueKind: "U_WORD" },
  { paramKey: "lcdlessbootfwchkcode", label: "LcdlessBootFwChkCode", registerType: "holding", address: 11018, valueKind: "U_WORD" },
  { paramKey: "lcdlessappfwchkcode", label: "LcdlessAppFwChkCode", registerType: "holding", address: 11019, valueKind: "U_WORD" },
  { paramKey: "lcdlessbootver", label: "LcdlessBootVer", registerType: "holding", address: 11020, valueKind: "U_WORD" },
  { paramKey: "lcdlessappver", label: "LcdlessAppVer", registerType: "holding", address: 11021, valueKind: "U_WORD" },
  { paramKey: "clearfutrunlog", label: "ClearFutRunLog", registerType: "holding", address: 11022, valueKind: "U_WORD" },
  { paramKey: "clearyield", label: "ClearYield", registerType: "holding", address: 11023, valueKind: "U_WORD" },
  { paramKey: "restorecombrd", label: "RestoreComBrd", registerType: "holding", address: 11024, valueKind: "U_WORD" },
  { paramKey: "clearfutwaveoriv", label: "ClearFutWaveOrIV", registerType: "holding", address: 11025, valueKind: "U_WORD" },
  { paramKey: "comstateinvteth", label: "ComStateInvtEth", registerType: "holding", address: 11027, valueKind: "U_WORD" },
  { paramKey: "pwrmodecombrd", label: "PwrModeComBrd", registerType: "holding", address: 11028, valueKind: "U_WORD" },
  { paramKey: "restchipcombrd", label: "RestChipComBrd", registerType: "holding", address: 11029, valueKind: "U_WORD" },
  { paramKey: "pwrstatedsp", label: "PwrStateDsp", registerType: "holding", address: 11030, valueKind: "U_WORD" },
  { paramKey: "functivcve", label: "FunctIvCve", registerType: "holding", address: 11044, valueKind: "U_WORD" },
  { paramKey: "functautmdbsadr", label: "FunctAutMdbsAdr", registerType: "holding", address: 11045, valueKind: "U_WORD" },
  { paramKey: "functfaultwave", label: "FunctFaultWave", registerType: "holding", address: 11046, valueKind: "U_WORD" },
  { paramKey: "freqa", label: "FreqA", unit: "Hz", registerType: "holding", address: 32774, valueKind: "S_WORD", scale: 0.1 },
  { paramKey: "freqb", label: "FreqB", unit: "Hz", registerType: "holding", address: 32775, valueKind: "S_WORD", scale: 0.1 },
  { paramKey: "freqc", label: "FreqC", unit: "Hz", registerType: "holding", address: 32776, valueKind: "S_WORD", scale: 0.1 },
  { paramKey: "freqt", label: "FreqT", unit: "Hz", registerType: "holding", address: 32779, valueKind: "S_WORD", scale: 0.1 },
  { paramKey: "npevolt", label: "NPEVolt", unit: "V", registerType: "holding", address: 32780, valueKind: "S_WORD" },
  { paramKey: "iamcu", label: "IaMcu", unit: "A", registerType: "holding", address: 32781, valueKind: "U_WORD" },
  { paramKey: "ibmcu", label: "IbMcu", unit: "A", registerType: "holding", address: 32782, valueKind: "U_WORD" },
  { paramKey: "icmcu", label: "IcMcu", unit: "A", registerType: "holding", address: 32783, valueKind: "U_WORD" },
  { paramKey: "uamcu", label: "UaMcu", unit: "V", registerType: "holding", address: 32784, valueKind: "U_WORD" },
  { paramKey: "ubmcu", label: "UbMcu", unit: "V", registerType: "holding", address: 32785, valueKind: "U_WORD" },
  { paramKey: "ucmcu", label: "UcMcu", unit: "V", registerType: "holding", address: 32786, valueKind: "U_WORD" },
  { paramKey: "ia_2", label: "Ia", unit: "A", registerType: "holding", address: 33024, valueKind: "S_WORD", scale: 0.1 },
  { paramKey: "ib_2", label: "Ib", unit: "A", registerType: "holding", address: 33025, valueKind: "S_WORD", scale: 0.1 },
  { paramKey: "ic_2", label: "Ic", unit: "A", registerType: "holding", address: 33026, valueKind: "S_WORD", scale: 0.1 },
  { paramKey: "paca", label: "PacA", unit: "kW", registerType: "holding", address: 33027, valueKind: "S_WORD", scale: 0.1 },
  { paramKey: "pacb", label: "PacB", unit: "kW", registerType: "holding", address: 33028, valueKind: "S_WORD", scale: 0.1 },
  { paramKey: "pacc", label: "PacC", unit: "kW", registerType: "holding", address: 33029, valueKind: "S_WORD", scale: 0.1 },
  { paramKey: "pact", label: "PacT", unit: "kW", registerType: "holding", address: 33030, valueKind: "S_WORD", scale: 0.1 },
  { paramKey: "qaca", label: "QacA", unit: "kvar", registerType: "holding", address: 33031, valueKind: "S_WORD", scale: 0.1 },
  { paramKey: "qacb", label: "QacB", unit: "kvar", registerType: "holding", address: 33032, valueKind: "S_WORD", scale: 0.1 },
  { paramKey: "qacc", label: "QacC", unit: "kvar", registerType: "holding", address: 33033, valueKind: "S_WORD", scale: 0.1 },
  { paramKey: "qact", label: "QacT", unit: "kvar", registerType: "holding", address: 33034, valueKind: "S_WORD", scale: 0.1 },
  { paramKey: "pfa", label: "PFa", registerType: "holding", address: 33035, valueKind: "S_WORD", scale: 0.01 },
  { paramKey: "pfb", label: "PFb", registerType: "holding", address: 33036, valueKind: "S_WORD", scale: 0.01 },
  { paramKey: "pfc", label: "PFc", registerType: "holding", address: 33037, valueKind: "S_WORD", scale: 0.01 },
  { paramKey: "pft", label: "PFt", registerType: "holding", address: 33038, valueKind: "S_WORD", scale: 0.01 },
  { paramKey: "uinva", label: "UinvA", unit: "V", registerType: "holding", address: 33039, valueKind: "S_WORD", scale: 0.1 },
  { paramKey: "uinvb", label: "UinvB", unit: "V", registerType: "holding", address: 33040, valueKind: "S_WORD", scale: 0.1 },
  { paramKey: "uinvc", label: "UinvC", unit: "V", registerType: "holding", address: 33041, valueKind: "S_WORD", scale: 0.1 },
  { paramKey: "pvinputmode_2", label: "PVInputMode", registerType: "holding", address: 33280, valueKind: "U_WORD" },
  { paramKey: "pdc_2", label: "Pdc", unit: "kW", registerType: "holding", address: 33281, valueKind: "S_WORD", scale: 0.1 },
  { paramKey: "mode_2", label: "Mode", registerType: "holding", address: 33536, valueKind: "U_WORD" },
  { paramKey: "poweronoffsta", label: "PowerOnOffSta", registerType: "holding", address: 33537, valueKind: "U_WORD" },
  { paramKey: "gfci", label: "GFCI", unit: "mA", registerType: "holding", address: 33541, valueKind: "S_WORD" },
  { paramKey: "dcia", label: "DCIA", unit: "mA", registerType: "holding", address: 33542, valueKind: "S_WORD" },
  { paramKey: "dcib", label: "DCIB", unit: "mA", registerType: "holding", address: 33543, valueKind: "S_WORD" },
  { paramKey: "dcic", label: "DCIC", unit: "mA", registerType: "holding", address: 33544, valueKind: "S_WORD" },
  { paramKey: "ubuspst", label: "UbusPst", unit: "V", registerType: "holding", address: 33545, valueKind: "S_WORD" },
  { paramKey: "ubusngt", label: "UbusNgt", unit: "V", registerType: "holding", address: 33546, valueKind: "S_WORD" },
  { paramKey: "ubuspstngt", label: "UbusPstNgt", unit: "V", registerType: "holding", address: 33547, valueKind: "S_WORD" },
  { paramKey: "cntdwpwron", label: "CntDwPwrOn", unit: "S", registerType: "holding", address: 33548, valueKind: "S_WORD" },
  { paramKey: "usampiso", label: "UsampIso", unit: "V", registerType: "holding", address: 33549, valueKind: "S_WORD" },
  { paramKey: "buscapacitance_2", label: "BusCapacitance", unit: "uF", registerType: "holding", address: 33550, valueKind: "S_WORD" },
  { paramKey: "accapacitance_2", label: "AcCapacitance", unit: "uF", registerType: "holding", address: 33551, valueKind: "S_WORD" },
  { paramKey: "deratestatus", label: "DerateStatus", registerType: "holding", address: 33556, valueKind: "U_WORD" },
  { paramKey: "acvoltrating", label: "AcVoltRating", unit: "V", registerType: "holding", address: 33565, valueKind: "U_WORD" },
  { paramKey: "warn_2", label: "Warn", registerType: "holding", address: 33792, valueKind: "U_WORD" },
  { paramKey: "fault0_2", label: "Fault0", registerType: "holding", address: 33793, valueKind: "U_WORD" },
  { paramKey: "fault1_2", label: "Fault1", registerType: "holding", address: 33794, valueKind: "U_WORD" },
  { paramKey: "fault2_2", label: "Fault2", registerType: "holding", address: 33795, valueKind: "U_WORD" },
  { paramKey: "fault3_2", label: "Fault3", registerType: "holding", address: 33796, valueKind: "U_WORD" },
  { paramKey: "fault4_2", label: "Fault4", registerType: "holding", address: 33797, valueKind: "U_WORD" },
  { paramKey: "pfault_2", label: "PFault", registerType: "holding", address: 33798, valueKind: "U_WORD" },
];
