import type { DriverRegister } from '../driverStore.js';

export const growattRegisters: DriverRegister[] = [
  { paramKey: 'charge', label: 'charge', registerType: 'read', address: 3024, valueKind: 'U_WORD' },
  { paramKey: 'battery_low_warning', label: '"Battery-low" warning', registerType: 'read', address: 3025, valueKind: 'U_WORD' },
  { paramKey: 'stop_for', label: 'stop for', registerType: 'read', address: 3028, valueKind: 'U_WORD' },
  { paramKey: 'start_for', label: 'start for', registerType: 'read', address: 3029, valueKind: 'U_WORD' },
  { paramKey: 'constant', label: 'constant', registerType: 'read', address: 3030, valueKind: 'U_WORD' },
  { paramKey: 'temp', label: 'temp', registerType: 'read', address: 3032, valueKind: 'U_WORD' },
  { paramKey: 'temp_2', label: 'temp', registerType: 'read', address: 3033, valueKind: 'U_WORD' },
  { paramKey: 'temp_3', label: 'temp', registerType: 'read', address: 3034, valueKind: 'U_WORD' },
  { paramKey: 'charge_and', label: 'charge and', registerType: 'read', address: 3038, valueKind: 'U_WORD' },
  { paramKey: 'bit0_7_minutes', label: 'Bit0~7: minutes;', registerType: 'read', address: 3039, valueKind: 'U_WORD' },
  { paramKey: 'charge_and_2', label: 'charge and', registerType: 'read', address: 3040, valueKind: 'U_WORD' },
  { paramKey: 'bit0_7_minutes_2', label: 'Bit0~7: minutes;', registerType: 'read', address: 3041, valueKind: 'U_WORD' },
  { paramKey: 'with_time1', label: 'With Time1', registerType: 'read', address: 3043, valueKind: 'U_WORD' },
  { paramKey: '4_xh_with_time1_r_w_with_time1', label: '4(xh) With Time1 R/W With Time1', registerType: 'read', address: 3044, valueKind: 'U_WORD' },
  { paramKey: 'with_time1_2', label: 'With Time1', registerType: 'read', address: 3045, valueKind: 'U_WORD' },
  { paramKey: 'first_stop', label: 'First Stop', registerType: 'read', address: 3046, valueKind: 'U_WORD' },
  { paramKey: 'stop', label: 'stop', registerType: 'read', address: 3048, valueKind: 'U_WORD' },
  { paramKey: '5_xh_time1', label: '5(xh) 同 Time1', registerType: 'read', address: 3050, valueKind: 'U_WORD' },
  { paramKey: 'with_time1_3', label: 'With Time1', registerType: 'read', address: 3051, valueKind: 'U_WORD' },
  { paramKey: '6_xh_time1_r_w_with_time1', label: '6(xh) 同 Time1 R/W With Time1', registerType: 'read', address: 3052, valueKind: 'U_WORD' },
  { paramKey: 'with_time1_4', label: 'With Time1', registerType: 'read', address: 3053, valueKind: 'U_WORD' },
  { paramKey: '7_xh_time1', label: '7(xh) 同 Time1', registerType: 'read', address: 3054, valueKind: 'U_WORD' },
  { paramKey: 'with_time1_5', label: 'With Time1', registerType: 'read', address: 3055, valueKind: 'U_WORD' },
  { paramKey: '8_xh_time1_r_w_with_time1', label: '8(xh) 同 Time1 R/W With Time1', registerType: 'read', address: 3056, valueKind: 'U_WORD' },
  { paramKey: 'with_time1_6', label: 'With Time1', registerType: 'read', address: 3057, valueKind: 'U_WORD' },
  { paramKey: '9_xh_time1_r_w_with_time1', label: '9(xh) 同 Time1 R/W With Time1', registerType: 'read', address: 3058, valueKind: 'U_WORD' },
  { paramKey: 'with_time1_7', label: 'With Time1', registerType: 'read', address: 3059, valueKind: 'U_WORD' },
  { paramKey: 'battery_type_choose_of', label: 'Battery type choose of', registerType: 'read', address: 3070, valueKind: 'U_WORD' },
  { paramKey: 'ups_function_enable_or', label: 'Ups function enable or', registerType: 'read', address: 3079, valueKind: 'U_WORD' },
  { paramKey: 'ups_output_voltage_r_w_0_0', label: 'UPS output voltage R/W 0 0:', unit: 'V', registerType: 'read', address: 3080, valueKind: 'U_WORD', scale: 230.0 },
  { paramKey: 'ups_output_frequency_r_w_0_0', label: 'UPS output frequency R/W 0 0:', unit: 'Hz', registerType: 'read', address: 3081, valueKind: 'U_WORD', scale: 50.0 },
  { paramKey: 'stopsoc_when_loadfirst_r_w_13_100_ratio', label: 'StopSoc When LoadFirst R/W 13-100 ratio', registerType: 'read', address: 3082, valueKind: 'U_WORD' },
  { paramKey: 'address_communication_addr_r_w_1_1_communication', label: 'Address Communication addr R/W 1 1 : Communication', registerType: 'read', address: 3085, valueKind: 'U_WORD' },
  { paramKey: 'communication_baudrate_r_w_0_0_9600_bps', label: 'Communication BaudRate R/W 0 0: 9600 bps', registerType: 'read', address: 3086, valueKind: 'U_WORD' },
  { paramKey: 'no_serial_number_1_2_r_w_ascii_for_battery', label: 'NO Serial Number 1-2 R/W ASCII For battery', registerType: 'read', address: 3087, valueKind: 'U_WORD' },
  { paramKey: 'no_serial_number_3_4_r_w_ascii', label: 'No Serial Number 3-4 R/W ASCII', registerType: 'read', address: 3088, valueKind: 'U_WORD' },
  { paramKey: 'no_serial_number_5_6_r_w_ascii', label: 'No Serial Number 5-6 R/W ASCII', registerType: 'read', address: 3089, valueKind: 'U_WORD' },
  { paramKey: 'no_serial_number_7_8_r_w_ascii', label: 'No Serial Number 7-8 R/W ASCII', registerType: 'read', address: 3090, valueKind: 'U_WORD' },
  { paramKey: 'no_serial_number_9_10_r_w_ascii', label: 'No Serial Number 9-10 R/W ASCII', registerType: 'read', address: 3091, valueKind: 'U_WORD' },
  { paramKey: 'model_r_w', label: 'Model R/W', registerType: 'read', address: 3092, valueKind: 'U_DWORD' },
  { paramKey: 'max', label: 'max', registerType: 'read', address: 3095, valueKind: 'U_WORD' },
  { paramKey: 'dtc_r', label: 'DTC R', registerType: 'read', address: 3098, valueKind: 'U_WORD' },
  { paramKey: 'code1_fw_code1_r_ascii', label: 'Code1 FW Code1 R ASCII', registerType: 'read', address: 3099, valueKind: 'U_WORD' },
  { paramKey: 'code2_fw_code2_r_ascii', label: 'Code2 FW Code2 R ASCII', registerType: 'read', address: 3100, valueKind: 'U_WORD' },
  { paramKey: 'user', label: 'User', registerType: 'read', address: 3102, valueKind: 'U_WORD' },
  { paramKey: 'to', label: 'to', registerType: 'read', address: 3103, valueKind: 'U_WORD' },
  { paramKey: 'charge_2', label: 'Charge', registerType: 'read', address: 1124, valueKind: 'U_WORD' },
  { paramKey: 'status_inverter_run_state_0_waiting', label: 'Status Inverter run state 0:waiting,', registerType: 'read', address: 2000, valueKind: 'U_WORD' },
  { paramKey: 'output_power', label: 'Output power', unit: 'W', registerType: 'read', address: 2035, valueKind: 'S_DWORD', scale: 0.1 },
  { paramKey: 'grid_frequency', label: 'Grid frequency', unit: 'Hz', registerType: 'read', address: 2037, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'three_single_phase_grid_voltage', label: 'Three/single phase grid voltage', unit: 'V', registerType: 'read', address: 2038, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'three_single_phase_grid_output_current', label: 'Three/single phase grid output current', unit: 'A', registerType: 'read', address: 2039, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'three_single_phase_grid_output_watt', label: 'Three/single phase grid output watt', registerType: 'read', address: 2040, valueKind: 'S_DWORD' },
  { paramKey: 'today_today_generate_energy', label: 'today Today generate energy', unit: 'kWh', registerType: 'read', address: 2053, valueKind: 'U_DWORD', scale: 0.1 },
  { paramKey: 'total_total_generate_energy', label: 'total Total generate energy', unit: 'kWh', registerType: 'read', address: 2055, valueKind: 'U_DWORD', scale: 0.1 },
  { paramKey: 'total_work_time_total_0_5s_spa', label: 'total Work time total 0.5s SPA', registerType: 'read', address: 2057, valueKind: 'U_DWORD' },
  { paramKey: 'inverter_temperature', label: 'Inverter temperature', unit: '°C', registerType: 'read', address: 2093, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'the_inside_ipm_in_inverter_temperature', label: 'The inside IPM in inverter Temperature', unit: '°C', registerType: 'read', address: 2094, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'boost_temperature', label: 'Boost temperature', unit: '°C', registerType: 'read', address: 2095, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'reserved', label: 'reserved', registerType: 'read', address: 2096, valueKind: 'U_WORD' },
  { paramKey: 'batvolt_dsp', label: 'BatVolt_DSP', unit: 'V', registerType: 'read', address: 2097, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'bus_voltage_p_bus_inside_voltage', label: 'Bus Voltage P Bus inside Voltage', unit: 'V', registerType: 'read', address: 2098, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'bus_voltage_n_bus_inside_voltage', label: 'Bus Voltage N Bus inside Voltage', unit: 'V', registerType: 'read', address: 2099, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'param', label: '/', registerType: 'read', address: 2100, valueKind: 'U_WORD' },
  { paramKey: 'ac_power', label: 'AC Power', registerType: 'read', address: 2102, valueKind: 'U_WORD' },
  { paramKey: 'ac_power_2', label: 'AC Power', registerType: 'read', address: 2103, valueKind: 'U_WORD' },
  { paramKey: 'extra_inverter_powertouser_extra', label: 'Extra inverter PowerTOUser_Extra', registerType: 'read', address: 2104, valueKind: 'U_DWORD' },
  { paramKey: 'today', label: 'today', registerType: 'read', address: 2109, valueKind: 'U_WORD' },
  { paramKey: 'charge_3', label: 'charge', registerType: 'read', address: 2116, valueKind: 'U_WORD' },
  { paramKey: 'charge_4', label: 'charge', registerType: 'read', address: 2117, valueKind: 'U_WORD' },
  { paramKey: '0_load_first', label: '0:Load First', registerType: 'read', address: 2118, valueKind: 'U_WORD' },
  { paramKey: 'type_0_lead_acid', label: 'Type 0：Lead-acid', registerType: 'read', address: 2119, valueKind: 'U_WORD' },
  { paramKey: 'pv', label: 'PV', unit: 'v', registerType: 'read', address: 3003, valueKind: 'U_WORD' },
  { paramKey: 'pv1_input_current', label: 'PV1 input current', unit: 'A', registerType: 'read', address: 3004, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'pv_2', label: 'PV', unit: 'v', registerType: 'read', address: 3007, valueKind: 'U_WORD', scale: 2.0 },
  { paramKey: 'pv2_input_current', label: 'PV2 input current', unit: 'A', registerType: 'read', address: 3008, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'pv_3', label: 'PV', unit: 'v', registerType: 'read', address: 3011, valueKind: 'U_WORD', scale: 3.0 },
  { paramKey: 'pv3_input_current', label: 'PV3 input current', unit: 'A', registerType: 'read', address: 3012, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'pv_4', label: 'PV', unit: 'v', registerType: 'read', address: 3015, valueKind: 'U_WORD', scale: 4.0 },
  { paramKey: 'pv4_input_current', label: 'PV4 input current', registerType: 'read', address: 3016, valueKind: 'U_WORD' },
  { paramKey: 'pv4_power', label: 'PV4 power', registerType: 'read', address: 3017, valueKind: 'U_WORD' },
  { paramKey: 'three_phase_grid_voltage', label: 'Three phase grid voltage', unit: 'V', registerType: 'read', address: 3038, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'three_phase_grid_voltage_2', label: 'Three phase grid voltage', unit: 'V', registerType: 'read', address: 3039, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'three_phase_grid_voltage_3', label: 'Three phase grid voltage', unit: 'V', registerType: 'read', address: 3040, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'pv_iso_value_1k', label: 'PV ISO value 1KΩ', registerType: 'read', address: 3087, valueKind: 'U_WORD' },
  { paramKey: 'r_dci_curr_0_1ma', label: 'R DCI Curr 0.1mA', registerType: 'read', address: 3088, valueKind: 'U_WORD' },
  { paramKey: 's_dci_curr_0_1ma', label: 'S DCI Curr 0.1mA', registerType: 'read', address: 3089, valueKind: 'U_WORD' },
  { paramKey: 't_dci_curr_0_1ma', label: 'T DCI Curr 0.1mA', registerType: 'read', address: 3090, valueKind: 'U_WORD' },
  { paramKey: 'gfci_curr_1ma', label: 'GFCI Curr 1mA', registerType: 'read', address: 3091, valueKind: 'U_WORD' },
  { paramKey: 'inverter_temperature_0_1', label: 'Inverter temperature 0.1℃', registerType: 'read', address: 3093, valueKind: 'U_WORD' },
  { paramKey: 'the_inside_ipm_in_inverter_temperature_0_1', label: 'The inside IPM in inverter temperature 0.1℃', registerType: 'read', address: 3094, valueKind: 'U_WORD' },
  { paramKey: 'boost_temperature_0_1', label: 'Boost temperature 0.1℃', registerType: 'read', address: 3095, valueKind: 'U_WORD' },
  { paramKey: 'reserved_0_1', label: 'Reserved 0.1℃', registerType: 'read', address: 3096, valueKind: 'U_WORD' },
  { paramKey: 'commmunication_broad_temperature_0_1', label: 'Commmunication broad temperature 0.1℃', registerType: 'read', address: 3097, valueKind: 'U_WORD' },
  { paramKey: 'bus_voltage_p_bus_inside_voltage_2', label: 'Bus Voltage P Bus inside Voltage', unit: 'V', registerType: 'read', address: 3098, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'bus_voltage_n_bus_inside_voltage_2', label: 'Bus Voltage N Bus inside Voltage', unit: 'V', registerType: 'read', address: 3099, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'inverter_output_pf_now_0_20000', label: 'Inverter output PF now 0-20000', registerType: 'read', address: 3100, valueKind: 'U_WORD' },
  { paramKey: 'real_output_power_percent', label: 'Real Output power Percent', unit: '%', registerType: 'read', address: 3101, valueKind: 'U_WORD' },
  { paramKey: 'code_inverter_fault_code', label: 'code Inverter fault code', registerType: 'read', address: 3105, valueKind: 'U_WORD' },
  { paramKey: 'code_inverter_warning_code', label: 'code Inverter Warning code', registerType: 'read', address: 3106, valueKind: 'U_WORD' },
  { paramKey: 'fac_ups_frequency', label: 'Fac UPS frequency', unit: 'Hz', registerType: 'read', address: 3145, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'vac1_ups_phase_r_output_voltage', label: 'Vac1 UPS phase R output voltage', unit: 'V', registerType: 'read', address: 3146, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'iac1_ups_phase_r_output_current', label: 'Iac1 UPS phase R output current', unit: 'A', registerType: 'read', address: 3147, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'vac2_ups_phase_s_output_voltage', label: 'Vac2 UPS phase S output voltage', unit: 'V', registerType: 'read', address: 3150, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'iac2_ups_phase_s_output_current', label: 'Iac2 UPS phase S output current', unit: 'A', registerType: 'read', address: 3151, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'vac3_ups_phase_t_output_voltage', label: 'Vac3 UPS phase T output voltage', unit: 'V', registerType: 'read', address: 3154, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'iac3_ups_phase_t_output_current', label: 'Iac3 UPS phase T output current', unit: 'A', registerType: 'read', address: 3155, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'load_percent_of_ups_ouput', label: 'Load percent of UPS ouput', unit: '%', registerType: 'read', address: 3160, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'power_factor_0_1', label: 'Power factor 0.1', registerType: 'read', address: 3161, valueKind: 'U_WORD' },
  { paramKey: 'dc_voltage_1mv', label: 'DC voltage 1mV', registerType: 'read', address: 3162, valueKind: 'U_WORD' },
  { paramKey: 'storge_device_fault_code', label: 'Storge device fault code', registerType: 'read', address: 3167, valueKind: 'U_WORD' },
  { paramKey: 'storge_device_warning_code', label: 'Storge device warning code', registerType: 'read', address: 3168, valueKind: 'U_WORD' },
  { paramKey: 'battery_voltage', label: 'Battery voltage', unit: 'V', registerType: 'read', address: 3169, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'battery_current', label: 'Battery current', unit: 'A', registerType: 'read', address: 3170, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'state_of_charge_capacity', label: 'State of charge Capacity', unit: '%', registerType: 'read', address: 3171, valueKind: 'U_WORD' },
  { paramKey: 'bus', label: 'BUS', unit: 'v', registerType: 'read', address: 3172, valueKind: 'U_WORD' },
  { paramKey: 'bus_2', label: 'BUS', unit: 'v', registerType: 'read', address: 3173, valueKind: 'U_WORD', scale: 2.0 },
  { paramKey: 'buck_boost_current', label: 'BUCK-BOOST Current', unit: 'A', registerType: 'read', address: 3174, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'llc_current', label: 'LLC Current', unit: 'A', registerType: 'read', address: 3175, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'temperture_a_0_1', label: 'Temperture A 0.1℃', registerType: 'read', address: 3176, valueKind: 'U_WORD' },
  { paramKey: 'temperture_b_0_1', label: 'Temperture B 0.1℃', registerType: 'read', address: 3177, valueKind: 'U_WORD' },
  { paramKey: 'reserved_2', label: 'Reserved', registerType: 'read', address: 3186, valueKind: 'U_WORD' },
  { paramKey: 'storge_device_fault_code_2', label: 'Storge device fault code', registerType: 'read', address: 3190, valueKind: 'U_WORD' },
  { paramKey: 'battery_voltage_2', label: 'Battery voltage', unit: 'V', registerType: 'read', address: 3192, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'battery_current_2', label: 'Battery current', unit: 'A', registerType: 'read', address: 3193, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'state_of_charge_capacity_2', label: 'State of charge Capacity', unit: '%', registerType: 'read', address: 3194, valueKind: 'U_WORD' },
  { paramKey: 'bus_3', label: 'BUS', unit: 'v', registerType: 'read', address: 3195, valueKind: 'U_WORD' },
  { paramKey: 'bus_4', label: 'BUS', unit: 'v', registerType: 'read', address: 3196, valueKind: 'U_WORD', scale: 2.0 },
  { paramKey: 'buck_boost_current_2', label: 'BUCK-BOOST Current', unit: 'A', registerType: 'read', address: 3197, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'llc_current_2', label: 'LLC Current', unit: 'A', registerType: 'read', address: 3198, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'temperture_a_0_1_2', label: 'Temperture A 0.1℃', registerType: 'read', address: 3199, valueKind: 'U_WORD' },
  { paramKey: 'temperture_b_0_1_2', label: 'Temperture B 0.1℃', registerType: 'read', address: 3200, valueKind: 'U_WORD' },
  { paramKey: 'reserved_3', label: 'reserved', registerType: 'read', address: 3209, valueKind: 'U_WORD' },
  { paramKey: 'status_from_bms_r_1', label: 'Status from BMS R 1', registerType: 'read', address: 3212, valueKind: 'U_WORD' },
  { paramKey: 'error_information_from_bms_r_1', label: 'Error information from BMS R 1', registerType: 'read', address: 3213, valueKind: 'U_WORD' },
  { paramKey: 'warning_information_from_bms_r_1', label: 'Warning information from BMS R 1', registerType: 'read', address: 3214, valueKind: 'U_WORD' },
  { paramKey: 'soc_from_bms_r', label: 'SOC from BMS R', unit: '%', registerType: 'read', address: 3215, valueKind: 'U_WORD' },
  { paramKey: 'delta_v_from_bms_r', label: 'Delta V from BMS R', unit: 'A', registerType: 'read', address: 3220, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'cycle_count_from_bms_r_1', label: 'Cycle Count from BMS R 1', registerType: 'read', address: 3221, valueKind: 'U_WORD' },
  { paramKey: 'soh_from_bms_r_1', label: 'SOH from BMS R 1', registerType: 'read', address: 3222, valueKind: 'U_WORD' },
  { paramKey: 'bmsinformation_from_bms_r_1', label: 'BMSInformation from BMS R 1', registerType: 'read', address: 3224, valueKind: 'U_WORD' },
  { paramKey: 'pack_information_from_bms_r_1', label: 'Pack Information from BMS R 1', registerType: 'read', address: 3225, valueKind: 'U_WORD' },
  { paramKey: 'using_cap_from_bms_r_1', label: 'Using Cap from BMS R 1', registerType: 'read', address: 3226, valueKind: 'U_WORD' },
  { paramKey: 'r_1', label: 'R 1', registerType: 'read', address: 3227, valueKind: 'U_WORD' },
  { paramKey: 'logger_rf_shineversion', label: 'logger RF-ShineVersion', registerType: 'read', address: 10001, valueKind: 'U_WORD' },
  { paramKey: 'logger_web_shinepano', label: 'logger Web-ShinePano', registerType: 'read', address: 10002, valueKind: 'U_WORD' },
  { paramKey: 'logger_web_shinewebbox', label: 'logger Web-ShineWebBox', registerType: 'read', address: 10003, valueKind: 'U_WORD' },
  { paramKey: 'logger_wl_wifi_module', label: 'logger WL-WIFI Module', registerType: 'read', address: 10004, valueKind: 'U_WORD' },
  { paramKey: 'box_confluence_box_1', label: 'box Confluence box 1', registerType: 'read', address: 11001, valueKind: 'U_WORD' },
];
