import type { DriverRegister } from '../driverStore.js';

export const huaweiSmartloggerRegisters: DriverRegister[] = [
  { paramKey: 'date_time', label: 'Date&Time', registerType: 'holding', address: 40000, valueKind: 'U_DWORD' },
  { paramKey: 'city', label: 'City', registerType: 'holding', address: 40002, valueKind: 'U_DWORD' },
  { paramKey: 'daylight_saving_time_dst', label: 'Daylight Saving Time (DST)', registerType: 'holding', address: 40004, valueKind: 'U_WORD' },
  { paramKey: 'time_zone', label: 'Time Zone', unit: 's', registerType: 'holding', address: 40005, valueKind: 'S_DWORD' },
  { paramKey: 'dst_state', label: 'DST state', registerType: 'holding', address: 40007, valueKind: 'U_WORD' },
  { paramKey: 'dst_offset', label: 'DST offset', unit: 'mins', registerType: 'holding', address: 40008, valueKind: 'U_WORD' },
  { paramKey: 'the_local_time', label: 'The Local Time', registerType: 'holding', address: 40009, valueKind: 'U_DWORD' },
  { paramKey: 'power_on', label: 'Power on', registerType: 'holding', address: 40200, valueKind: 'U_WORD' },
  { paramKey: 'power_off', label: 'Power off', registerType: 'holding', address: 40201, valueKind: 'U_WORD' },
  { paramKey: 'power_on_off', label: 'Power on/off', registerType: 'holding', address: 40202, valueKind: 'U_WORD' },
  { paramKey: 'power_on_off_2', label: 'Power on/off', registerType: 'holding', address: 40203, valueKind: 'U_WORD' },
  { paramKey: 'transfer_trip', label: 'Transfer trip', registerType: 'holding', address: 40204, valueKind: 'U_WORD' },
  { paramKey: 'array_reset', label: 'Array reset', registerType: 'holding', address: 40205, valueKind: 'U_WORD' },
  { paramKey: 'active_adjustment', label: 'Active adjustment', unit: 'kW', registerType: 'holding', address: 40420, valueKind: 'U_DWORD', scale: 0.1 },
  { paramKey: 'reactive_adjustment', label: 'Reactive adjustment', unit: 'kVar', registerType: 'holding', address: 40422, valueKind: 'S_DWORD', scale: 0.1 },
  { paramKey: 'active_adjustment_2', label: 'Active adjustment', unit: 'kW', registerType: 'holding', address: 40424, valueKind: 'U_DWORD', scale: 0.1 },
  { paramKey: 'reactive_adjustment_2', label: 'Reactive adjustment', unit: 'kVar', registerType: 'holding', address: 40426, valueKind: 'S_DWORD', scale: 0.1 },
  { paramKey: 'active_power_adjustment_by_percentage', label: 'Active power adjustment by percentage', unit: '%', registerType: 'holding', address: 40428, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'power_factor_adjustment', label: 'Power factor adjustment', registerType: 'holding', address: 40429, valueKind: 'S_WORD', scale: 0.001 },
  { paramKey: 'dc_current', label: 'DC current', unit: 'A', registerType: 'holding', address: 40500, valueKind: 'S_WORD', scale: 0.1 },
  { paramKey: 'input_power', label: 'Input power', unit: 'kW', registerType: 'holding', address: 40521, valueKind: 'U_DWORD', scale: 0.001 },
  { paramKey: 'co2_reduction', label: 'CO2 reduction', unit: 'kg', registerType: 'holding', address: 40523, valueKind: 'U_DWORD', scale: 0.1 },
  { paramKey: 'active_power', label: 'Active power', unit: 'kW', registerType: 'holding', address: 40525, valueKind: 'S_DWORD', scale: 0.001 },
  { paramKey: 'power_factor', label: 'Power factor', registerType: 'holding', address: 40532, valueKind: 'S_WORD', scale: 0.001 },
  { paramKey: 'plant_status', label: 'Plant status', registerType: 'holding', address: 40543, valueKind: 'U_WORD' },
  { paramKey: 'reactive_power', label: 'Reactive power', unit: 'kVar', registerType: 'holding', address: 40544, valueKind: 'S_DWORD', scale: 0.001 },
  { paramKey: 'co2_reduction_2', label: 'CO2 reduction', unit: 'kg', registerType: 'holding', address: 40550, valueKind: 'U_QWORD', scale: 0.01 },
  { paramKey: 'dc_current_2', label: 'DC current 2', unit: 'A', registerType: 'holding', address: 40554, valueKind: 'S_DWORD', scale: 0.1 },
  { paramKey: 'e_total', label: 'E-Total', unit: 'kWh', registerType: 'holding', address: 40560, valueKind: 'U_DWORD', scale: 0.1 },
  { paramKey: 'e_daily', label: 'E-Daily', unit: 'kWh', registerType: 'holding', address: 40562, valueKind: 'U_DWORD', scale: 0.1 },
  { paramKey: 'duration_of_daily_power_generation', label: 'Duration of daily power generation', unit: 'h', registerType: 'holding', address: 40564, valueKind: 'U_DWORD', scale: 0.1 },
  { paramKey: 'plant_status_2', label: 'Plant status', registerType: 'holding', address: 40566, valueKind: 'U_WORD' },
  { paramKey: 'plant_status_3', label: 'Plant status', registerType: 'holding', address: 40567, valueKind: 'U_WORD' },
  { paramKey: 'active_alarm_sequence_number', label: 'Active alarm sequence number', registerType: 'holding', address: 40568, valueKind: 'U_DWORD' },
  { paramKey: 'historical_alarm_sequence_number', label: 'Historical alarm sequence number', registerType: 'holding', address: 40570, valueKind: 'U_DWORD' },
  { paramKey: 'phase_a_current', label: 'Phase A current', unit: 'A', registerType: 'holding', address: 40572, valueKind: 'S_WORD' },
  { paramKey: 'phase_b_current', label: 'Phase B current', unit: 'A', registerType: 'holding', address: 40573, valueKind: 'S_WORD' },
  { paramKey: 'phase_c_current', label: 'Phase C current', unit: 'A', registerType: 'holding', address: 40574, valueKind: 'S_WORD' },
  { paramKey: 'uab', label: 'Uab', unit: 'V', registerType: 'holding', address: 40575, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'ubc', label: 'Ubc', unit: 'V', registerType: 'holding', address: 40576, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'uca', label: 'Uca', unit: 'V', registerType: 'holding', address: 40577, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'reserved', label: 'Reserved', registerType: 'holding', address: 40608, valueKind: 'U_WORD' },
  { paramKey: 'inverter_efficiency', label: 'Inverter Efficiency', unit: '%', registerType: 'holding', address: 40685, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'max_reactive_adjustment', label: 'Max. reactive adjustment', unit: 'kVar', registerType: 'holding', address: 40693, valueKind: 'U_DWORD', scale: 0.1 },
  { paramKey: 'min_reactive_adjustment', label: 'Min. reactive adjustment', unit: 'kVar', registerType: 'holding', address: 40695, valueKind: 'S_DWORD', scale: 0.1 },
  { paramKey: 'max_activeadjustm_ent', label: 'Max. activeadjustm ent', unit: 'kW', registerType: 'holding', address: 40697, valueKind: 'U_DWORD', scale: 0.1 },
  { paramKey: 'locked', label: 'Locked', registerType: 'holding', address: 40699, valueKind: 'U_WORD' },
  { paramKey: 'di_status', label: 'DI status', registerType: 'holding', address: 40700, valueKind: 'U_WORD' },
  { paramKey: 'esn', label: 'ESN', registerType: 'holding', address: 40713, valueKind: 'STRING', stringLengthWords: 10 },
  { paramKey: 'system_reset', label: 'System reset', registerType: 'holding', address: 40723, valueKind: 'U_WORD' },
  { paramKey: 'fast_device_access', label: 'Fast device access', registerType: 'holding', address: 40724, valueKind: 'U_WORD' },
  { paramKey: 'device_operation', label: 'Device operation', registerType: 'holding', address: 40725, valueKind: 'STRING', stringLengthWords: 11 },
  { paramKey: 'device_access_status', label: 'Device access status', registerType: 'holding', address: 40736, valueKind: 'U_WORD' },
  { paramKey: 'active_power_control_mode', label: 'Active power control mode', registerType: 'holding', address: 40737, valueKind: 'U_WORD' },
  { paramKey: 'active_power_scheduling_target_value', label: 'Active power scheduling target value', unit: 'kW', registerType: 'holding', address: 40738, valueKind: 'U_DWORD', scale: 0.1 },
  { paramKey: 'reactive_power_control_mode', label: 'Reactive power control mode', registerType: 'holding', address: 40740, valueKind: 'U_WORD' },
  { paramKey: 'reactive_power_scheduling_curve_mode', label: 'Reactive power scheduling curve mode', registerType: 'holding', address: 40741, valueKind: 'U_WORD' },
  { paramKey: 'active_scheduling_percentage', label: 'Active scheduling percentage', unit: '%', registerType: 'holding', address: 40802, valueKind: 'U_DWORD' },
  { paramKey: 'pv_module_capacity', label: 'PV module capacity', unit: 'kW', registerType: 'holding', address: 41934, valueKind: 'U_DWORD', scale: 0.001 },
  { paramKey: 'rated_plant_capacity', label: 'Rated plant capacity', unit: 'kW', registerType: 'holding', address: 41936, valueKind: 'U_DWORD', scale: 0.001 },
  { paramKey: 'total_rated_capacity_of_grid_connecte_d_inverters', label: 'Total rated capacity of grid-connecte d inverters', unit: 'kW', registerType: 'holding', address: 41938, valueKind: 'U_DWORD', scale: 0.001 },
  { paramKey: 'conversion_coefficient', label: 'Conversion coefficient', registerType: 'holding', address: 41940, valueKind: 'U_DWORD', scale: 0.001 },
  { paramKey: 'communicati_on_status', label: 'Communicati on status', registerType: 'holding', address: 41942, valueKind: 'U_WORD' },
  { paramKey: 'the_systemtime_year', label: 'The SystemTime: year', registerType: 'holding', address: 42017, valueKind: 'U_WORD' },
  { paramKey: 'the_systemtime_month', label: 'The SystemTime: month', registerType: 'holding', address: 42018, valueKind: 'U_WORD' },
  { paramKey: 'the_systemtime_day', label: 'The SystemTime: day', registerType: 'holding', address: 42019, valueKind: 'U_WORD' },
  { paramKey: 'the_systemtime_hour', label: 'The SystemTime: hour', registerType: 'holding', address: 42020, valueKind: 'U_WORD' },
  { paramKey: 'the_systemtime_minute', label: 'The SystemTime: minute', registerType: 'holding', address: 42021, valueKind: 'U_WORD' },
  { paramKey: 'the_systemtime_second', label: 'The SystemTime: second', registerType: 'holding', address: 42022, valueKind: 'U_WORD' },
  { paramKey: 'current_error_during_scanning', label: 'Current error during scanning', registerType: 'holding', address: 42150, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'inspection', label: 'Inspection', registerType: 'holding', address: 42730, valueKind: 'U_WORD' },
  { paramKey: 'iv_curve_scanning', label: 'IV curve scanning', registerType: 'holding', address: 42779, valueKind: 'U_WORD' },
  { paramKey: 'alarm_info_1', label: 'Alarm Info 1', registerType: 'holding', address: 50000, valueKind: 'U_WORD' },
  { paramKey: 'alarm_info_2', label: 'Alarm Info 2', registerType: 'holding', address: 50001, valueKind: 'U_WORD' },
];
