import type { DriverRegister } from '../driverStore.js';

export const iskraMc3Registers: DriverRegister[] = [
  { paramKey: "act_voltage_u1", label: "Voltage\u00a0U1", registerType: "read", address: 106, valueKind: "FP32" },
  { paramKey: "act_voltage_u2", label: "Voltage\u00a0U2", registerType: "read", address: 108, valueKind: "FP32" },
  { paramKey: "act_voltage_u3", label: "Voltage\u00a0U3", registerType: "read", address: 110, valueKind: "FP32" },
  { paramKey: "act_average_phase_voltage_u", label: "Average\u00a0phase\u00a0Voltage\u00a0U~", registerType: "read", address: 112, valueKind: "FP32" },
  { paramKey: "act_phase_to_phase_voltage_u12", label: "Phase\u00a0to\u00a0phase\u00a0voltage\u00a0U12", registerType: "read", address: 117, valueKind: "FP32" },
  { paramKey: "act_phase_to_phase_voltage_u23", label: "Phase\u00a0to\u00a0phase\u00a0voltage\u00a0U23", registerType: "read", address: 119, valueKind: "FP32" },
  { paramKey: "act_phase_to_phase_voltage_u31", label: "Phase\u00a0to\u00a0phase\u00a0voltage\u00a0U31", registerType: "read", address: 121, valueKind: "FP32" },
  { paramKey: "act_avg_phase_to_phase_voltage_upp", label: "Avg.\u00a0phase\u00a0to\u00a0phase\u00a0Voltage\u00a0Upp~", registerType: "read", address: 123, valueKind: "FP32" },
  { paramKey: "act_current_i1", label: "Current\u00a0I1", registerType: "read", address: 125, valueKind: "FP32" },
  { paramKey: "act_current_i2", label: "Current\u00a0I2", registerType: "read", address: 127, valueKind: "FP32" },
  { paramKey: "act_current_i3", label: "Current\u00a0I3", registerType: "read", address: 129, valueKind: "FP32" },
  { paramKey: "act_total_current_i", label: "Total\u00a0Current\u00a0I", registerType: "read", address: 137, valueKind: "FP32" },
  { paramKey: "act_neutral_current_in", label: "Neutral\u00a0current\u00a0In", registerType: "read", address: 131, valueKind: "FP32" },
  { paramKey: "act_real_power_p1", label: "Real\u00a0Power\u00a0P1", registerType: "read", address: 141, valueKind: "FP32" },
  { paramKey: "act_real_power_p2", label: "Real\u00a0Power\u00a0P2", registerType: "read", address: 143, valueKind: "FP32" },
  { paramKey: "act_real_power_p3", label: "Real\u00a0Power\u00a0P3", registerType: "read", address: 145, valueKind: "FP32" },
  { paramKey: "act_total_real_power_p", label: "Total\u00a0Real\u00a0Power\u00a0P", registerType: "read", address: 139, valueKind: "FP32" },
  { paramKey: "act_reactive_power_q1", label: "Reactive\u00a0Power\u00a0Q1", registerType: "read", address: 149, valueKind: "FP32" },
  { paramKey: "act_reactive_power_q2", label: "Reactive\u00a0Power\u00a0Q2", registerType: "read", address: 151, valueKind: "FP32" },
  { paramKey: "act_reactive_power_q3", label: "Reactive\u00a0Power\u00a0Q3", registerType: "read", address: 153, valueKind: "FP32" },
  { paramKey: "act_total_reactive_power_q", label: "Total\u00a0Reactive\u00a0Power\u00a0Q", registerType: "read", address: 147, valueKind: "FP32" },
  { paramKey: "act_apparent_power_s1", label: "Apparent\u00a0Power\u00a0S1", registerType: "read", address: 157, valueKind: "FP32" },
  { paramKey: "act_apparent_power_s2", label: "Apparent\u00a0Power\u00a0S2", registerType: "read", address: 159, valueKind: "FP32" },
  { paramKey: "act_apparent_power_s3", label: "Apparent\u00a0Power\u00a0S3", registerType: "read", address: 161, valueKind: "FP32" },
  { paramKey: "act_total_apparent_power_s", label: "Total\u00a0Apparent\u00a0Power\u00a0S", registerType: "read", address: 155, valueKind: "FP32" },
  { paramKey: "act_power_factor_pf1", label: "Power\u00a0Factor\u00a0PF1", registerType: "read", address: 165, valueKind: "FP32" },
  { paramKey: "act_power_factor_pf2", label: "Power\u00a0Factor\u00a0PF2", registerType: "read", address: 167, valueKind: "FP32" },
  { paramKey: "act_power_factor_pf3", label: "Power\u00a0Factor\u00a0PF3", registerType: "read", address: 169, valueKind: "FP32" },
  { paramKey: "act_total_power_factor_pf", label: "Total\u00a0Power\u00a0Factor\u00a0PF", registerType: "read", address: 163, valueKind: "FP32" },
  { paramKey: "act_counter_e1", label: "Counter\u00a0E1", registerType: "read", address: 405, valueKind: "U_DWORD" },
  { paramKey: "act_counter_e2", label: "Counter\u00a0E2", registerType: "read", address: 407, valueKind: "U_DWORD" },
  { paramKey: "act_counter_e3", label: "Counter\u00a0E3", registerType: "read", address: 409, valueKind: "U_DWORD" },
  { paramKey: "act_counter_e4", label: "Counter\u00a0E4", registerType: "read", address: 411, valueKind: "U_DWORD" },
  { paramKey: "norm_voltage_u1", label: "Voltage\u00a0U1 (normalized)", registerType: "read", address: 800, valueKind: "FP32" },
  { paramKey: "norm_voltage_u2", label: "Voltage\u00a0U2 (normalized)", registerType: "read", address: 801, valueKind: "FP32" },
  { paramKey: "norm_voltage_u3", label: "Voltage\u00a0U3 (normalized)", registerType: "read", address: 802, valueKind: "FP32" },
  { paramKey: "norm_average_phase_voltage_u", label: "Average\u00a0phase\u00a0Voltage\u00a0U~ (normalized)", registerType: "read", address: 803, valueKind: "FP32" },
  { paramKey: "norm_phase_to_phase_voltage_u12", label: "Phase\u00a0to\u00a0phase\u00a0voltage\u00a0U12 (normalized)", registerType: "read", address: 804, valueKind: "FP32" },
  { paramKey: "norm_phase_to_phase_voltage_u23", label: "Phase\u00a0to\u00a0phase\u00a0voltage\u00a0U23 (normalized)", registerType: "read", address: 805, valueKind: "FP32" },
  { paramKey: "norm_phase_to_phase_voltage_u31", label: "Phase\u00a0to\u00a0phase\u00a0voltage\u00a0U31 (normalized)", registerType: "read", address: 806, valueKind: "FP32" },
  { paramKey: "norm_average_phase_to_phase_voltage", label: "Average\u00a0 phase\u00a0 to\u00a0 phase\u00a0 Voltage (normalized)", registerType: "read", address: 807, valueKind: "FP32" },
  { paramKey: "norm_current_i1", label: "Current\u00a0I1 (normalized)", registerType: "read", address: 808, valueKind: "FP32" },
  { paramKey: "norm_current_i2", label: "Current\u00a0I2 (normalized)", registerType: "read", address: 809, valueKind: "FP32" },
  { paramKey: "norm_current_i3", label: "Current\u00a0I3 (normalized)", registerType: "read", address: 810, valueKind: "FP32" },
  { paramKey: "norm_total_current_i", label: "Total\u00a0Current\u00a0I (normalized)", registerType: "read", address: 811, valueKind: "FP32" },
  { paramKey: "norm_neutral_current_in", label: "Neutral\u00a0current\u00a0In (normalized)", registerType: "read", address: 812, valueKind: "FP32" },
  { paramKey: "norm_average_current_i", label: "Average\u00a0Current\u00a0I~ (normalized)", registerType: "read", address: 814, valueKind: "FP32" },
  { paramKey: "norm_real_power_p1", label: "Real\u00a0Power\u00a0P1 (normalized)", registerType: "read", address: 815, valueKind: "FP32" },
  { paramKey: "norm_real_power_p2", label: "Real\u00a0Power\u00a0P2 (normalized)", registerType: "read", address: 816, valueKind: "FP32" },
  { paramKey: "norm_real_power_p3", label: "Real\u00a0Power\u00a0P3 (normalized)", registerType: "read", address: 817, valueKind: "FP32" },
  { paramKey: "norm_total_real_power_p", label: "Total\u00a0Real\u00a0Power\u00a0P (normalized)", registerType: "read", address: 818, valueKind: "FP32" },
  { paramKey: "norm_reactive_power_q1", label: "Reactive\u00a0Power\u00a0Q1 (normalized)", registerType: "read", address: 819, valueKind: "FP32" },
  { paramKey: "norm_reactive_power_q2", label: "Reactive\u00a0Power\u00a0Q2 (normalized)", registerType: "read", address: 820, valueKind: "FP32" },
  { paramKey: "norm_reactive_power_q3", label: "Reactive\u00a0Power\u00a0Q3 (normalized)", registerType: "read", address: 821, valueKind: "FP32" },
  { paramKey: "norm_total_reactive_power_q", label: "Total\u00a0Reactive\u00a0Power\u00a0Q (normalized)", registerType: "read", address: 822, valueKind: "FP32" },
  { paramKey: "norm_apparent_power_s1", label: "Apparent\u00a0Power\u00a0S1 (normalized)", registerType: "read", address: 823, valueKind: "FP32" },
  { paramKey: "norm_apparent_power_s2", label: "Apparent\u00a0Power\u00a0S2 (normalized)", registerType: "read", address: 824, valueKind: "FP32" },
  { paramKey: "norm_apparent_power_s3", label: "Apparent\u00a0Power\u00a0S3 (normalized)", registerType: "read", address: 825, valueKind: "FP32" },
  { paramKey: "norm_total_apparent_power_s", label: "Total\u00a0Apparent\u00a0Power\u00a0S (normalized)", registerType: "read", address: 826, valueKind: "FP32" },
  { paramKey: "norm_power_factor_pf1", label: "Power\u00a0Factor\u00a0PF1 (normalized)", registerType: "read", address: 827, valueKind: "FP32" },
  { paramKey: "norm_power_factor_pf2", label: "Power\u00a0Factor\u00a0PF2 (normalized)", registerType: "read", address: 828, valueKind: "FP32" },
  { paramKey: "norm_power_factor_pf3", label: "Power\u00a0Factor\u00a0PF3 (normalized)", registerType: "read", address: 829, valueKind: "FP32" },
  { paramKey: "norm_total_power_factor_pf", label: "Total\u00a0Power\u00a0Factor\u00a0PF (normalized)", registerType: "read", address: 830, valueKind: "FP32" },
  { paramKey: "norm_cap_ind_p_f_phase_1_pf1", label: "CAP/IND\u00a0P.F.\u00a0Phase\u00a01\u00a0(PF1) (normalized)", registerType: "read", address: 831, valueKind: "FP32" },
  { paramKey: "norm_cap_ind_p_f_phase_2_pf2", label: "CAP/IND\u00a0P.F.\u00a0Phase\u00a02\u00a0(PF2) (normalized)", registerType: "read", address: 832, valueKind: "FP32" },
  { paramKey: "norm_cap_ind_p_f_phase_3_pf3", label: "CAP/IND\u00a0P.F.\u00a0Phase\u00a03\u00a0(PF3) (normalized)", registerType: "read", address: 833, valueKind: "FP32" },
  { paramKey: "norm_cap_ind_p_f_total_pft", label: "CAP/IND\u00a0P.F.\u00a0Total\u00a0(PFt) (normalized)", registerType: "read", address: 834, valueKind: "FP32" },
  { paramKey: "norm_power_angle_u1_i1", label: "Power\u00a0Angle\u00a0U1\u2212I1 (normalized)", registerType: "read", address: 835, valueKind: "FP32" },
  { paramKey: "norm_power_angle_u2_i2", label: "Power\u00a0Angle\u00a0U2\u2212I2 (normalized)", registerType: "read", address: 836, valueKind: "FP32" },
  { paramKey: "norm_power_angle_u3_i3", label: "Power\u00a0Angle\u00a0U3\u2212I3 (normalized)", registerType: "read", address: 837, valueKind: "FP32" },
  { paramKey: "norm_power_angle_atan_2_pt_qt", label: "Power\u00a0Angle\u00a0atan\u00a02(Pt,\u00a0Qt) (normalized)", registerType: "read", address: 838, valueKind: "FP32" },
  { paramKey: "norm_angle_u1_u2", label: "Angle\u00a0U1\u2212U2 (normalized)", registerType: "read", address: 839, valueKind: "FP32" },
  { paramKey: "norm_angle_u2_u3", label: "Angle\u00a0U2\u2212U3 (normalized)", registerType: "read", address: 840, valueKind: "FP32" },
  { paramKey: "norm_angle_u3_u1", label: "Angle\u00a0U3\u2212U1 (normalized)", registerType: "read", address: 841, valueKind: "FP32" },
  { paramKey: "norm_frequency", label: "Frequency (normalized)", registerType: "read", address: 842, valueKind: "FP32" },
  { paramKey: "norm_thd_i1", label: "THD\u00a0I1 (normalized)", registerType: "read", address: 844, valueKind: "FP32" },
  { paramKey: "norm_thd_i2", label: "THD\u00a0I2 (normalized)", registerType: "read", address: 845, valueKind: "FP32" },
  { paramKey: "norm_thd_i3", label: "THD\u00a0I3 (normalized)", registerType: "read", address: 846, valueKind: "FP32" },
  { paramKey: "norm_thd_u1", label: "THD\u00a0U1 (normalized)", registerType: "read", address: 847, valueKind: "FP32" },
  { paramKey: "norm_thd_u2", label: "THD\u00a0U2 (normalized)", registerType: "read", address: 848, valueKind: "FP32" },
  { paramKey: "norm_thd_u3", label: "THD\u00a0U3 (normalized)", registerType: "read", address: 849, valueKind: "FP32" },
  { paramKey: "norm_thd_u12", label: "THD\u00a0U12 (normalized)", registerType: "read", address: 850, valueKind: "FP32" },
  { paramKey: "norm_thd_u23", label: "THD\u00a0U23 (normalized)", registerType: "read", address: 851, valueKind: "FP32" },
  { paramKey: "norm_thd_u31", label: "THD\u00a0U31 (normalized)", registerType: "read", address: 852, valueKind: "FP32" },
  { paramKey: "norm_md_real_power_p_positive", label: "MD\u00a0Real\u00a0Power\u00a0P\u00a0(positive) (normalized)", registerType: "read", address: 853, valueKind: "FP32" },
  { paramKey: "norm_md_real_power_p_negative", label: "MD\u00a0Real\u00a0Power\u00a0P\u00a0(negative) (normalized)", registerType: "read", address: 854, valueKind: "FP32" },
  { paramKey: "norm_md_reactive_power_q_l", label: "MD\u00a0Reactive\u00a0Power\u00a0Q\u00a0\u2212\u00a0L (normalized)", registerType: "read", address: 855, valueKind: "FP32" },
  { paramKey: "norm_md_reactive_power_q_c", label: "MD\u00a0Reactive\u00a0Power\u00a0Q\u00a0\u2212\u00a0C (normalized)", registerType: "read", address: 856, valueKind: "FP32" },
  { paramKey: "norm_md_apparent_power_s", label: "MD\u00a0Apparent\u00a0Power\u00a0S (normalized)", registerType: "read", address: 857, valueKind: "FP32" },
  { paramKey: "norm_md_current_i1", label: "MD\u00a0Current\u00a0I1 (normalized)", registerType: "read", address: 858, valueKind: "FP32" },
  { paramKey: "norm_md_current_i2", label: "MD\u00a0Current\u00a0I2 (normalized)", registerType: "read", address: 859, valueKind: "FP32" },
  { paramKey: "norm_md_current_i3", label: "MD\u00a0Current\u00a0I3 (normalized)", registerType: "read", address: 860, valueKind: "FP32" },
  { paramKey: "norm_md_real_power_p_positive_2", label: "MD\u00a0Real\u00a0Power\u00a0P\u00a0(positive) (normalized)", registerType: "read", address: 861, valueKind: "FP32" },
  { paramKey: "norm_md_real_power_p_negative_2", label: "MD\u00a0Real\u00a0Power\u00a0P\u00a0(negative) (normalized)", registerType: "read", address: 862, valueKind: "FP32" },
  { paramKey: "norm_md_reactive_power_q_l_2", label: "MD\u00a0Reactive\u00a0Power\u00a0Q\u00a0\u2212\u00a0L (normalized)", registerType: "read", address: 863, valueKind: "FP32" },
  { paramKey: "norm_md_reactive_power_q_c_2", label: "MD\u00a0Reactive\u00a0Power\u00a0Q\u00a0\u2212\u00a0C (normalized)", registerType: "read", address: 864, valueKind: "FP32" },
  { paramKey: "norm_md_apparent_power_s_2", label: "MD\u00a0Apparent\u00a0Power\u00a0S (normalized)", registerType: "read", address: 865, valueKind: "FP32" },
  { paramKey: "norm_md_current_i1_2", label: "MD\u00a0Current\u00a0I1 (normalized)", registerType: "read", address: 866, valueKind: "FP32" },
  { paramKey: "norm_md_current_i2_2", label: "MD\u00a0Current\u00a0I2 (normalized)", registerType: "read", address: 867, valueKind: "FP32" },
  { paramKey: "norm_md_current_i3_2", label: "MD\u00a0Current\u00a0I3 (normalized)", registerType: "read", address: 868, valueKind: "FP32" },
  { paramKey: "norm_energy_counter_1", label: "Energy\u00a0Counter\u00a01 (normalized)", registerType: "read", address: 869, valueKind: "FP32" },
  { paramKey: "norm_internal_temperature", label: "Internal\u00a0Temperature (normalized)", registerType: "read", address: 879, valueKind: "FP32" },
];
