import type { DriverRegister } from '../driverStore.js';

export const knoxAswRegisters: DriverRegister[] = [
  { paramKey: 'device_type_1_single_phase_3_three_pahse', label: 'Device Type: 1=Single phase / 3=Three pahse', registerType: 'read', address: 31001, valueKind: 'STRING', stringLengthWords: 1 },
  { paramKey: 'modbus_address_default_as_3', label: 'Modbus address：Default as 3', registerType: 'read', address: 31002, valueKind: 'U_WORD' },
  { paramKey: 'serial_number', label: 'Serial Number', registerType: 'read', address: 31003, valueKind: 'STRING', stringLengthWords: 16 },
  { paramKey: 'machine_type_for_example_asw3000_please_refer_to_the_specific_machine_in_practic', label: 'Machine type: for example, "ASW3000", please refer to the specific machine in practice', registerType: 'read', address: 31019, valueKind: 'STRING', stringLengthWords: 8 },
  { paramKey: 'current_grid_code_refer_to_section_3_5', label: 'Current grid code: refer to Section 3.5', registerType: 'read', address: 31027, valueKind: 'U_WORD' },
  { paramKey: 'rated_power', label: 'Rated Power', unit: 'W', registerType: 'read', address: 31028, valueKind: 'U_DWORD' },
  { paramKey: 'master_software_version', label: 'Master Software Version', registerType: 'read', address: 31030, valueKind: 'STRING', stringLengthWords: 7 },
  { paramKey: 'slave_software_version', label: 'Slave Software Version', registerType: 'read', address: 31037, valueKind: 'STRING', stringLengthWords: 7 },
  { paramKey: 'safety_version', label: 'Safety Version', registerType: 'read', address: 31044, valueKind: 'STRING', stringLengthWords: 7 },
  { paramKey: 'communication_protocol_version_2_1_5', label: 'Communication protocol version：2.1.5', registerType: 'read', address: 31051, valueKind: 'STRING', stringLengthWords: 6 },
  { paramKey: 'manufacturer_s_name_for_example_aiswei_refer_to_the_specific_ma_chine', label: 'Manufacturer\'s name: for example, "AISWEI", refer to the specific ma- chine', registerType: 'read', address: 31057, valueKind: 'STRING', stringLengthWords: 8 },
  { paramKey: 'brand_name_for_example_aiswei_please_refer_to_the_spe_cific_machine', label: 'Brand name: for example, "AISWEI", please refer to the spe- cific machine', registerType: 'read', address: 31065, valueKind: 'STRING', stringLengthWords: 8 },
  { paramKey: 'inverter_model_1_pv_single_phase1_3kw_2_pv_single_phase3_6kw_3_pv_three_phase3_1', label: 'Inverter model： 1-PV Single phase1-3kw 2-PV Single phase3-6kw 3-PV Three phase3-10kW 4-PV Three phase15-23kW 5-PV Three phase50-60kW 11-HY Single phase1-3kW 12-HY Single phase3-6kW', registerType: 'read', address: 31073, valueKind: 'U_WORD' },
  { paramKey: 'mppt_number', label: 'MPPT number', registerType: 'read', address: 31074, valueKind: 'U_WORD' },
  { paramKey: 'string_current_number', label: 'String current number', registerType: 'read', address: 31075, valueKind: 'U_WORD' },
  { paramKey: 'hardware_version', label: 'Hardware version', registerType: 'read', address: 31076, valueKind: 'STRING', stringLengthWords: 2 },
  { paramKey: 'master_cpu_sub_version', label: 'Master CPU sub-version', registerType: 'read', address: 31078, valueKind: 'STRING', stringLengthWords: 3 },
  { paramKey: 'slaver_cpu_version', label: 'Slaver CPU version', registerType: 'read', address: 31097, valueKind: 'STRING', stringLengthWords: 7 },
  { paramKey: 'slaver_cpu_sub_version', label: 'Slaver CPU sub-version', registerType: 'read', address: 31104, valueKind: 'STRING', stringLengthWords: 1 },
  { paramKey: 'pv1_pv4_string_current_number', label: 'PV1~PV4 string current number', registerType: 'read', address: 31117, valueKind: 'U_WORD' },
  { paramKey: 'pv5_pv8_string_current_number', label: 'PV5~PV8 string current number', registerType: 'read', address: 31118, valueKind: 'U_WORD' },
  { paramKey: 'pv9_pv12_string_current_number', label: 'PV9~PV12 string current number', registerType: 'read', address: 31119, valueKind: 'U_WORD' },
  { paramKey: 'pv13_pv16_string_current_number', label: 'PV13~PV16 string current number', registerType: 'read', address: 31120, valueKind: 'U_WORD' },
  { paramKey: 'pv17_pv20_string_current_number', label: 'PV17~PV20 string current number', registerType: 'read', address: 31121, valueKind: 'U_WORD' },
  { paramKey: 'pv21_pv24_string_current_number', label: 'PV21~PV24 string current number', registerType: 'read', address: 31122, valueKind: 'U_WORD' },
  { paramKey: 'pv25_pv28_string_current_number', label: 'PV25~PV28 string current number', registerType: 'read', address: 31123, valueKind: 'U_WORD' },
  { paramKey: 'pv29_pv32_string_current_number', label: 'PV29~PV32 string current number', registerType: 'read', address: 31124, valueKind: 'U_WORD' },
  { paramKey: 'grid_rated_voltage', label: 'Grid rated voltage', unit: 'V', registerType: 'read', address: 31301, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'grid_rated_frequency', label: 'Grid rated frequency', unit: 'Hz', registerType: 'read', address: 31302, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'e_today_of_inverter', label: 'E-Today of inverter', unit: 'kWh', registerType: 'read', address: 31303, valueKind: 'U_DWORD', scale: 0.1 },
  { paramKey: 'e_total_of_inverter', label: 'E-Total of inverter', unit: 'kWh', registerType: 'read', address: 31305, valueKind: 'U_DWORD', scale: 0.1 },
  { paramKey: 'h_total', label: 'H-Total', unit: 'H', registerType: 'read', address: 31307, valueKind: 'U_DWORD' },
  { paramKey: 'device_state_0_wait_1_normal_2_fault_4_checking', label: 'Device State: 0 = Wait 1 = Normal 2 = Fault 4  = Checking', registerType: 'read', address: 31309, valueKind: 'U_WORD' },
  { paramKey: 'connect_time', label: 'Connect time', unit: 's', registerType: 'read', address: 31310, valueKind: 'U_WORD' },
  { paramKey: 'internal_temperature', label: 'Internal temperature', unit: '°C', registerType: 'read', address: 31311, valueKind: 'S_WORD', scale: 0.1 },
  { paramKey: 'inverter_u_phase_temperature', label: 'Inverter U phase temperature', unit: '°C', registerType: 'read', address: 31312, valueKind: 'S_WORD', scale: 0.1 },
  { paramKey: 'inverter_v_phase_temperature', label: 'Inverter V phase temperature', unit: '°C', registerType: 'read', address: 31313, valueKind: 'S_WORD', scale: 0.1 },
  { paramKey: 'inverter_w_phase_temperature', label: 'Inverter W phase temperature', unit: '°C', registerType: 'read', address: 31314, valueKind: 'S_WORD', scale: 0.1 },
  { paramKey: 'boost_temperature', label: 'Boost temperature', unit: '°C', registerType: 'read', address: 31315, valueKind: 'S_WORD', scale: 0.1 },
  { paramKey: 'bidirectional_dc_dc_converter_tem_perature', label: 'Bidirectional DC/DC Converter tem- perature(*)', unit: '°C', registerType: 'read', address: 31316, valueKind: 'S_WORD', scale: 0.1 },
  { paramKey: 'bus_voltage', label: 'Bus voltage', unit: 'V', registerType: 'read', address: 31317, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'pv1_voltage', label: 'PV1 voltage', unit: 'V', registerType: 'read', address: 31319, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'pv1_current', label: 'PV1 current', unit: 'A', registerType: 'read', address: 31320, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'pv2_voltage', label: 'PV2 voltage', unit: 'V', registerType: 'read', address: 31321, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'pv2_current', label: 'PV2 current', unit: 'A', registerType: 'read', address: 31322, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'pv3_voltage', label: 'PV3 voltage(*)', unit: 'V', registerType: 'read', address: 31323, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'pv3_current', label: 'PV3 current(*)', unit: 'A', registerType: 'read', address: 31324, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'pv4_voltage', label: 'PV4 voltage(*)', unit: 'V', registerType: 'read', address: 31325, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'pv4_current', label: 'PV4 current(*)', unit: 'A', registerType: 'read', address: 31326, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'pv5_voltage', label: 'PV5 voltage(*)', unit: 'V', registerType: 'read', address: 31327, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'pv5_current', label: 'PV5 current(*)', unit: 'A', registerType: 'read', address: 31328, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'pv6_voltage', label: 'PV6 voltage(*)', unit: 'V', registerType: 'read', address: 31329, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'pv6_current', label: 'PV6 current(*)', unit: 'A', registerType: 'read', address: 31330, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'pv7_voltage', label: 'PV7 voltage(*)', unit: 'V', registerType: 'read', address: 31331, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'pv7_current', label: 'PV7 current(*)', unit: 'A', registerType: 'read', address: 31332, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'pv8_voltage', label: 'PV8 voltage(*)', unit: 'V', registerType: 'read', address: 31333, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'pv8_current', label: 'PV8 current(*)', unit: 'A', registerType: 'read', address: 31334, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'pv9_voltage', label: 'PV9 voltage(*)', unit: 'V', registerType: 'read', address: 31335, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'pv9_current', label: 'PV9 current(*)', unit: 'A', registerType: 'read', address: 31336, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'pv10_voltage', label: 'PV10 voltage(*)', unit: 'V', registerType: 'read', address: 31337, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'pv10_current', label: 'PV10 current(*)', unit: 'A', registerType: 'read', address: 31338, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'string_1_current', label: 'String 1 current(*)', unit: 'A', registerType: 'read', address: 31339, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'string_2_current', label: 'String 2 current(*)', unit: 'A', registerType: 'read', address: 31340, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'string_3_current', label: 'String 3 current(*)', unit: 'A', registerType: 'read', address: 31341, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'string_4_current', label: 'String 4 current(*)', unit: 'A', registerType: 'read', address: 31342, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'string_5_current', label: 'String 5 current(*)', unit: 'A', registerType: 'read', address: 31343, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'string_6_current', label: 'String 6 current(*)', unit: 'A', registerType: 'read', address: 31344, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'string_7_current', label: 'String 7 current(*)', unit: 'A', registerType: 'read', address: 31345, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'string_8_current', label: 'String 8 current(*)', unit: 'A', registerType: 'read', address: 31346, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'string_9_current', label: 'String 9 current(*)', unit: 'A', registerType: 'read', address: 31347, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'string_10_current', label: 'String 10 current(*)', unit: 'A', registerType: 'read', address: 31348, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'string_11_current', label: 'String 11 current(*)', unit: 'A', registerType: 'read', address: 31349, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'string_12_current', label: 'String 12 current(*)', unit: 'A', registerType: 'read', address: 31350, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'string_13_current', label: 'String 13 current(*)', unit: 'A', registerType: 'read', address: 31351, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'string_14_current', label: 'String 14 current(*)', unit: 'A', registerType: 'read', address: 31352, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'string_15_current', label: 'String 15 current(*)', unit: 'A', registerType: 'read', address: 31353, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'string_16_current', label: 'String 16 current(*)', unit: 'A', registerType: 'read', address: 31354, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'string_17_current', label: 'String 17 current(*)', unit: 'A', registerType: 'read', address: 31355, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'string_18_current', label: 'String 18 current(*)', unit: 'A', registerType: 'read', address: 31356, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'string_19_current', label: 'String 19 current(*)', unit: 'A', registerType: 'read', address: 31357, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'string_20_current', label: 'String 20 current(*)', unit: 'A', registerType: 'read', address: 31358, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'l1_phase_voltage', label: 'L1 Phase voltage', unit: 'V', registerType: 'read', address: 31359, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'l1_phase_current', label: 'L1 Phase current', unit: 'A', registerType: 'read', address: 31360, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'l2_phase_voltage', label: 'L2 Phase voltage(*)', unit: 'V', registerType: 'read', address: 31361, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'l2_phase_current', label: 'L2 Phase current(*)', unit: 'A', registerType: 'read', address: 31362, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'l3_phase_voltage', label: 'L3 Phase voltage(*)', unit: 'V', registerType: 'read', address: 31363, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'l3_phase_current', label: 'L3 Phase current(*)', unit: 'A', registerType: 'read', address: 31364, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'rs_line_voltage', label: 'RS Line voltage(*)', unit: 'V', registerType: 'read', address: 31365, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'rt_line_voltage', label: 'RT Line voltage(*)', unit: 'V', registerType: 'read', address: 31366, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'st_line_voltage', label: 'ST Line voltage(*)', unit: 'V', registerType: 'read', address: 31367, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'grid_frequency', label: 'Grid frequency', unit: 'Hz', registerType: 'read', address: 31368, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'apparent_power', label: 'Apparent power', unit: 'VA', registerType: 'read', address: 31369, valueKind: 'U_DWORD' },
  { paramKey: 'active_power', label: 'Active power', unit: 'W', registerType: 'read', address: 31371, valueKind: 'S_DWORD' },
  { paramKey: 'reactive_power', label: 'Reactive power', unit: 'Var', registerType: 'read', address: 31373, valueKind: 'S_DWORD' },
  { paramKey: 'power_factor', label: 'Power factor', registerType: 'read', address: 31375, valueKind: 'S_WORD', scale: 0.01 },
  { paramKey: 'fault_state_of_inverter_itself_0_no_internal_fault_1_internal_fault', label: 'Fault state of inverter itself： 0 = No internal fault 1 = Internal fault', registerType: 'read', address: 31377, valueKind: 'U_WORD' },
  { paramKey: 'error_message_please_refer_to_sec_tion_3_4', label: 'Error message:please refer to sec- tion 3.4', registerType: 'read', address: 31378, valueKind: 'U_WORD' },
  { paramKey: 'warning_message_please_refer_to_section_3_4', label: 'Warning message:please refer to section 3.4', registerType: 'read', address: 31379, valueKind: 'U_WORD' },
  { paramKey: 'ios_measure_value', label: 'IOS measure value', registerType: 'read', address: 31389, valueKind: 'U_WORD' },
  { paramKey: 'power_limitation_master_slave_status_0_not_available_power_limitation_disable_1_', label: 'Power limitation master-slave status： 0 = Not available（Power limitation disable） 1 = Master（Power limitation enable） 2 = Slave（Power limitation enable）', registerType: 'read', address: 31390, valueKind: 'U_WORD' },
  { paramKey: 'grid_connection_status_0_disconnection_1_connection', label: 'Grid connection status： 0 = disconnection 1 = connection', registerType: 'read', address: 31391, valueKind: 'U_WORD' },
  { paramKey: 'pv_total_power', label: 'PV total power', unit: 'W', registerType: 'read', address: 31601, valueKind: 'U_DWORD' },
  { paramKey: 'pv_e_today', label: 'PV E-Today', unit: 'kWh', registerType: 'read', address: 31603, valueKind: 'U_DWORD', scale: 0.1 },
  { paramKey: 'pv_e_total', label: 'PV E-Total', unit: 'kWh', registerType: 'read', address: 31605, valueKind: 'U_DWORD', scale: 0.1 },
  { paramKey: 'battery_communication_status_0x000a_normal_0x0005_error', label: 'Battery communication status: 0x000A=Normal 0x0005=Error', registerType: 'read', address: 31607, valueKind: 'U_WORD' },
  { paramKey: 'battery_status_0_not_available_1_idle_2_charging_3_discharging_4_error', label: 'Battery status: 0 = Not available 1 = Idle 2 = Charging 3 = Discharging 4 = Error', registerType: 'read', address: 31608, valueKind: 'U_WORD' },
  { paramKey: 'battery_error_status_1_bit0_communication_data_error_0_valid_1_invalid_bit1_cell', label: 'Battery Error Status 1: bit0 communication data error 0- valid 1-invalid bit1 cell or module voltage is too high 0-valid 1-invalid bit2 Cell or module voltage is too low 0-valid 1-invalid bit3 battery temperature is too high 0-valid 1-invalid bit4 battery temperature is too low 0-valid 1-invalid bit5 discharging current over limit 0-valid 1-invalid bit6 charging current over limit 0- valid 1-invalid', registerType: 'read', address: 31609, valueKind: 'U_WORD' },
  { paramKey: 'battery_error_status_2_bit0_self_test_failure_for_battery_voltage_0_valid_1_fail', label: 'Battery Error Status 2: bit0 Self-test failure for battery voltage  0-valid 1-failure bit1 Self-test failure for system voltage 0-valid 1-invalid bit2 Self-test failure for system in- sulation resistance 0-valid 1-invalid bit3 RTC invalid 0-valid 1-invalid bit4 EEPROM failure 0-valid 1-inva- lid bit5 Flash failure 0-valid 1-invalid bit6 AFE invalid 0-valid 1-invalid bit7 Chip failure for insulation re- sistance dectect 0-valid 1-invalid bit9 Chip failure for current sam- pling  0-valid 1-invalid bit10 HDC failure 0-valid 1-invalid bit11 Daisy chain failure 0-valid 1- invalid bit12 Failure for precharge 0-valid 1-invalid The default value of undefined bit is 1', registerType: 'read', address: 31610, valueKind: 'U_WORD' },
  { paramKey: 'battery_error_status3_bit0_the_battery_is_damaged_0_valid_1_invalid_bit1_the_inp', label: 'Battery error status3： bit0   The battery is damaged  0- valid 1-invalid bit1   The input overvoltage fails 0-valid 1-invalid bit2   The input is reversed and invalidated   0-valid 1-invalid bit3    The circuit breaker fails 0-valid 1-invalid The default value of undefined bit is 1', registerType: 'read', address: 31611, valueKind: 'U_WORD' },
  { paramKey: 'battery_warning_status_1_bit0_communication_data_error_0_valid_1_invalid_bit1_ba', label: 'Battery warning status 1: bit0 Communication data error 0- valid 1-invalid bit1 Battery or module voltage is too high 0-valid 1-invalid bit2 Battery or module voltage is too low 0-valid 1-invalid bit3 Battery temperature is too high 0-valid 1-invalid bit4 Battery temperature is too low 0-valid 1-invalid bit5 discharging current over limit 0-valid 1-invalid bit6 charging current over limit 0- valid 1-invalid bit7 Internal communication failure 0-valid 1-invalid bit8 Internal cell voltage is unbal- ance  0-valid 1-invalid The default value of undefined bit is 1', registerType: 'read', address: 31613, valueKind: 'U_WORD' },
  { paramKey: 'battery_voltage', label: 'Battery voltage', unit: 'V', registerType: 'read', address: 31617, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'battery_current', label: 'Battery current', unit: 'A', registerType: 'read', address: 31618, valueKind: 'S_WORD', scale: 0.1 },
  { paramKey: 'battery_power', label: 'Battery power', unit: 'w', registerType: 'read', address: 31619, valueKind: 'S_DWORD' },
  { paramKey: 'battery_temperature', label: 'Battery temperature', unit: '°C', registerType: 'read', address: 31621, valueKind: 'S_WORD', scale: 0.1 },
  { paramKey: 'battery_soc', label: 'Battery SOC', registerType: 'read', address: 31622, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'battery_soh', label: 'Battery SOH', registerType: 'read', address: 31623, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'battery_charging_current_limit', label: 'Battery charging current limit', unit: 'A', registerType: 'read', address: 31624, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'battery_discharge_current_limit', label: 'Battery discharge current limit', unit: 'A', registerType: 'read', address: 31625, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'battery_e_charge_today', label: 'Battery E-Charge-Today', unit: 'kWh', registerType: 'read', address: 31626, valueKind: 'U_DWORD', scale: 0.1 },
  { paramKey: 'battery_e_discharge_today', label: 'Battery E-Discharge-Today', unit: 'kWh', registerType: 'read', address: 31628, valueKind: 'U_DWORD', scale: 0.1 },
  { paramKey: 'e_consumption_today_at_ac_side', label: 'E-Consumption-Today at AC side', unit: 'kWh', registerType: 'read', address: 31630, valueKind: 'U_DWORD', scale: 0.1 },
  { paramKey: 'e_generation_today_at_ac_side', label: 'E-Generation-Today at AC side', unit: 'kWh', registerType: 'read', address: 31632, valueKind: 'U_DWORD', scale: 0.1 },
  { paramKey: 'eps_load_voltage', label: 'EPS load voltage', unit: 'V', registerType: 'read', address: 31634, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'eps_load_current', label: 'EPS load current', unit: 'A', registerType: 'read', address: 31635, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'eps_load_frequency', label: 'EPS load frequency', unit: 'Hz', registerType: 'read', address: 31636, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'eps_load_active_power', label: 'EPS load active power', unit: 'w', registerType: 'read', address: 31637, valueKind: 'S_DWORD' },
  { paramKey: 'eps_load_reactive_power', label: 'EPS load reactive power', unit: 'Var', registerType: 'read', address: 31639, valueKind: 'S_DWORD' },
  { paramKey: 'e_consumption_today_at_eps_load_side', label: 'E-Consumption-Today at EPS load side', unit: 'kWh', registerType: 'read', address: 31641, valueKind: 'U_DWORD', scale: 0.1 },
  { paramKey: 'e_consumption_total_at_eps_load_side', label: 'E-Consumption-Total at EPS load side', unit: 'kWh', registerType: 'read', address: 31643, valueKind: 'U_DWORD', scale: 0.1 },
  { paramKey: 'phase_1_voltage_for_eps_load', label: 'Phase 1 voltage for EPS Load', unit: 'V', registerType: 'read', address: 31645, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'phase_1_cuurent_for_eps_load', label: 'Phase 1 cuurent for EPS Load', unit: 'A', registerType: 'read', address: 31646, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'phase_2_voltage_for_eps_load', label: 'Phase 2 voltage for EPS Load', unit: 'V', registerType: 'read', address: 31647, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'phase_2_cuurent_for_eps_load', label: 'Phase 2 cuurent for EPS Load', unit: 'A', registerType: 'read', address: 31648, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'phase_3_voltage_for_eps_load', label: 'Phase 3 voltage for EPS Load', unit: 'V', registerType: 'read', address: 31649, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'phase_3_cuurent_for_eps_load', label: 'Phase 3 cuurent for EPS Load', unit: 'A', registerType: 'read', address: 31650, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'phase_1_active_power_for_eps_load', label: 'Phase 1 active power for EPS Load', unit: 'w', registerType: 'read', address: 31651, valueKind: 'U_DWORD' },
  { paramKey: 'phase_1_reactive_power_for_eps_load', label: 'Phase 1 reactive power for EPS Load', unit: 'Var', registerType: 'read', address: 31653, valueKind: 'S_DWORD' },
  { paramKey: 'phase_2_active_power_for_eps_load', label: 'Phase 2 active power for EPS Load', unit: 'w', registerType: 'read', address: 31655, valueKind: 'U_DWORD' },
  { paramKey: 'phase_2_reactive_power_for_eps_load', label: 'Phase 2 reactive power for EPS Load', unit: 'Var', registerType: 'read', address: 31657, valueKind: 'S_DWORD' },
  { paramKey: 'phase_3_active_power_for_eps_load', label: 'Phase 3 active power for EPS Load', unit: 'w', registerType: 'read', address: 31659, valueKind: 'U_DWORD' },
  { paramKey: 'phase_3_reactive_power_for_eps_load', label: 'Phase 3 reactive power for EPS Load', unit: 'Var', registerType: 'read', address: 31661, valueKind: 'S_DWORD' },
  { paramKey: 'phase_1_active_power_for_grid', label: 'Phase 1 active power for Grid', unit: 'w', registerType: 'read', address: 31663, valueKind: 'U_DWORD' },
  { paramKey: 'phase_1_reactive_power_for_grid', label: 'Phase 1 reactive power for Grid', unit: 'Var', registerType: 'read', address: 31665, valueKind: 'S_DWORD' },
  { paramKey: 'phase_2_active_power_for_grid', label: 'Phase 2 active power for Grid', unit: 'w', registerType: 'read', address: 31667, valueKind: 'U_DWORD' },
  { paramKey: 'phase_2_reactive_power_for_grid', label: 'Phase 2 reactive power for Grid', unit: 'Var', registerType: 'read', address: 31669, valueKind: 'S_DWORD' },
  { paramKey: 'phase_3_active_power_for_grid', label: 'Phase 3 active power for Grid', unit: 'w', registerType: 'read', address: 31671, valueKind: 'U_DWORD' },
  { paramKey: 'phase_3_reactive_power_for_grid', label: 'Phase 3 reactive power for Grid', unit: 'Var', registerType: 'read', address: 31673, valueKind: 'S_DWORD' },
  { paramKey: 'energy_charge_today_for_grid', label: 'Energy charge today for Grid', unit: 'kWh', registerType: 'read', address: 31675, valueKind: 'U_DWORD', scale: 0.1 },
  { paramKey: 'energy_charge_total_for_grid', label: 'Energy charge total for Grid', unit: 'kWh', registerType: 'read', address: 31677, valueKind: 'U_DWORD', scale: 0.1 },
  { paramKey: 'battery_insulation_resistance', label: 'Battery insulation resistance', unit: 'kΩ', registerType: 'read', address: 31679, valueKind: 'U_WORD' },
  { paramKey: 'battery_charge_discharge_cycles', label: 'Battery charge/discharge cycles', registerType: 'read', address: 31680, valueKind: 'U_WORD' },
  { paramKey: 'environment_temperature', label: 'Environment temperature', unit: '%', registerType: 'read', address: 31681, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'remote_switch_com_mand_0_power_off_1_power_on_170_initialization_status', label: 'Remote switch com- mand: 0 = POWER OFF 1 = POWER ON 170 = Initialization status', registerType: 'read', address: 40201, valueKind: 'U_WORD' },
  { paramKey: 'rtc_year', label: 'RTC:Year', registerType: 'read', address: 41001, valueKind: 'U_WORD' },
  { paramKey: 'rtc_month', label: 'RTC:Month', registerType: 'read', address: 41002, valueKind: 'U_WORD' },
  { paramKey: 'rtc_day', label: 'RTC:Day', registerType: 'read', address: 41003, valueKind: 'U_WORD' },
  { paramKey: 'rtc_hour', label: 'RTC:Hour', registerType: 'read', address: 41004, valueKind: 'U_WORD' },
  { paramKey: 'rtc_minute', label: 'RTC:Minute', registerType: 'read', address: 41005, valueKind: 'U_WORD' },
  { paramKey: 'rtc_seconds', label: 'RTC:Seconds', registerType: 'read', address: 41006, valueKind: 'U_WORD' },
  { paramKey: 'storage_inverter_switch_1_off_2_on', label: 'Storage Inverter Switch： 1 - OFF 2 - ON', registerType: 'read', address: 41102, valueKind: 'U_WORD' },
  { paramKey: 'type_selection_of_energy_storage_machine_0_invalid_1_energy_storage_ma_chine_2_g', label: 'Type selection of energy storage machine： 0 - Invalid 1 - Energy storage ma- chine 2 - Grid off inveter 3 - Grid connected in- verter 4 - Force charge with City electricity (battery wake- up)', registerType: 'read', address: 41103, valueKind: 'U_WORD' },
  { paramKey: 'run_mode_0_invalid_1_off_2_self_generating_self_use_3_backup_power_supply_4_cust', label: 'Run mode： 0 - Invalid 1 - Off 2 - Self generating self use 3 - Backup power supply 4 - Customer defined', registerType: 'read', address: 41104, valueKind: 'U_WORD' },
  { paramKey: 'battery_manufacturer', label: 'Battery manufacturer：', registerType: 'read', address: 41105, valueKind: 'U_WORD' },
  { paramKey: 'smart_meter_status_0x000a_meter_online_0x0005_meter_offline', label: 'Smart meter status： 0x000A - Meter Online 0x0005 - Meter Offline', registerType: 'read', address: 41108, valueKind: 'U_WORD' },
  { paramKey: 'smart_meter_adjustment_flag_bit_0x000a_start_0x0005_stop', label: 'Smart meter adjustment flag bit： 0x000A = Start 0x0005 = Stop', registerType: 'read', address: 41109, valueKind: 'U_WORD' },
  { paramKey: 'set_target_power_value', label: 'Set target power value', unit: 'w', registerType: 'read', address: 41110, valueKind: 'S_DWORD' },
  { paramKey: 'current_power_value_of_smart_meter', label: 'Current power value of smart meter', unit: 'w', registerType: 'read', address: 41112, valueKind: 'S_DWORD' },
  { paramKey: 'anti_reverse_current_flag_0x000a_on_0x0005_off', label: 'Anti reverse current flag： 0x000A = ON 0x0005 = OFF', registerType: 'read', address: 41114, valueKind: 'U_WORD' },
  { paramKey: 'battery_wake_up_force_charge_sign_0x000a_on_0x0005_off_0xffff_not_triggered', label: 'Battery wake-up (Force charge) sign： 0x000A = ON 0x0005 = OFF 0xFFFF =Not triggered', registerType: 'read', address: 41115, valueKind: 'U_WORD' },
  { paramKey: 'ups_function_0_enable_eps_function_1_enable_ups_function', label: 'UPS function： 0 = Enable EPS function 1 = Enable UPS function', registerType: 'read', address: 41116, valueKind: 'U_WORD' },
  { paramKey: 'commbox_and_cloud_communication_status_0x000a_cloud_online_0x0005_cloud_offline_', label: 'Commbox and cloud communication status： 0x000A = Cloud Online 0x0005 = Cloud Offline 0x00AF = Network not configured', registerType: 'read', address: 41151, valueKind: 'U_WORD' },
  { paramKey: 'charge_discharge_flag_bit_1_stop_2_charging_3_discharge', label: 'Charge discharge flag bit： 1 - Stop 2 - Charging 3 - Discharge', registerType: 'read', address: 41152, valueKind: 'U_WORD' },
  { paramKey: 'charge_and_discharge_power_command_charging_power', label: 'Charge and discharge power command： ‘ – ’- charging power', unit: 'W', registerType: 'read', address: 41153, valueKind: 'S_WORD' },
  { paramKey: 'charging_soc_upper_limit', label: 'Charging SOC upper  limit', unit: '%', registerType: 'read', address: 41154, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'discharge_soc_lower_limit', label: 'Discharge SOC lower limit', unit: '%', registerType: 'read', address: 41155, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'obtaining_power_ratio_of_power_grid', label: 'Obtaining power ratio of power grid', unit: '%', registerType: 'read', address: 41156, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'active_power_control_function_0_disable_1_enable', label: 'Active power control function： 0 = Disable 1 = Enable', registerType: 'read', address: 44001, valueKind: 'U_WORD' },
  { paramKey: 'eeg_control_function_0_disable_1_enable', label: 'EEG control function： 0 = Disable 1 = Enable', registerType: 'read', address: 44002, valueKind: 'U_WORD' },
  { paramKey: 'slope_load_function_0_disable_1_enable', label: 'Slope load function： 0 = Disable 1 = Enable', registerType: 'read', address: 44003, valueKind: 'U_WORD' },
  { paramKey: 'overvoltage_reduce_power_function_0_disable_1_enable', label: 'Overvoltage reduce power function： 0 = Disable 1 = Enable', registerType: 'read', address: 44004, valueKind: 'U_WORD' },
  { paramKey: 'overfrequency_reduce_power_function_0_disable_1_enable', label: 'Overfrequency reduce power function： 0 = Disable 1 = Enable', registerType: 'read', address: 44005, valueKind: 'U_WORD' },
  { paramKey: 'reactive_power_control_fucntion_0_disable_1_enable', label: 'Reactive power control fucntion： 0 = Disable 1 = Enable', registerType: 'read', address: 44006, valueKind: 'U_WORD' },
  { paramKey: 'lvrt_function_0_disable_1_enable', label: 'LVRT Function： 0 = Disable 1 = Enable', registerType: 'read', address: 44007, valueKind: 'U_WORD' },
  { paramKey: 'hvrt_function_0_disable_1_enable', label: 'HVRT Function： 0 = Disable 1 = Enable', registerType: 'read', address: 44008, valueKind: 'U_WORD' },
  { paramKey: '10_minutes_average_overvoltage_protect_fucntion_0_disable_1_enable', label: '10 Minutes Average Overvoltage protect fucntion 0 = Disable 1 = Enable', registerType: 'read', address: 44009, valueKind: 'U_WORD' },
  { paramKey: 'islanding_protect_func_tion', label: 'Islanding protect func- tion：', registerType: 'read', address: 44010, valueKind: 'U_WORD' },
  { paramKey: 'pe_connnection_check_function_0_disable_1_enable', label: 'PE connnection check function： 0 = Disable 1 = Enable', registerType: 'read', address: 44012, valueKind: 'U_WORD' },
  { paramKey: 'afci_function_0_disable_1_enable', label: 'AFCI function： 0 = Disable 1 = Enable', registerType: 'read', address: 44014, valueKind: 'U_WORD' },
  { paramKey: 'pv_string_current_moni_toring_function_0_disable_1_enable', label: 'PV string current moni- toring function： 0 = Disable 1 = Enable', registerType: 'read', address: 44015, valueKind: 'U_WORD' },
  { paramKey: 'overload_function_0_disable_1_enable', label: 'Overload function： 0 = Disable 1 = Enable', registerType: 'read', address: 44017, valueKind: 'U_WORD' },
  { paramKey: 'spd_detection_function_0_disable_1_enable', label: 'SPD detection function： 0 = Disable 1 = Enable', registerType: 'read', address: 44019, valueKind: 'U_WORD' },
  { paramKey: 'low_voltage_increase_power_function_0_disable_1_enable', label: 'Low voltage increase power function： 0 = Disable 1 = Enable', registerType: 'read', address: 44020, valueKind: 'U_WORD' },
  { paramKey: 'low_frequency_increase_power_function_0_disable_1_enable', label: 'Low frequency increase power function： 0 = Disable 1 = Enable', registerType: 'read', address: 44021, valueKind: 'U_WORD' },
  { paramKey: 'primary_low_frequency_function_0_disable_1_enable', label: 'Primary low frequency function(*)： 0 = Disable 1 = Enable', registerType: 'read', address: 44023, valueKind: 'U_WORD' },
  { paramKey: 'communication_loss_de_tection_function_0_disable_1_enable', label: 'Communication loss de- tection function(*)： 0 = Disable 1 = Enable', registerType: 'read', address: 44024, valueKind: 'U_WORD' },
  { paramKey: 'shadow_mppt_function_0_disable_1_enable', label: 'Shadow MPPT function: 0 = Disable 1 = Enable', registerType: 'read', address: 44025, valueKind: 'U_WORD' },
  { paramKey: 'external_input_signal_function', label: 'External input signal function：', registerType: 'read', address: 44026, valueKind: 'U_WORD' },
  { paramKey: 'sunspec_write_function_0_disable_1_enable', label: 'Sunspec write function： 0 = Disable 1 = Enable', registerType: 'read', address: 44027, valueKind: 'U_WORD' },
  { paramKey: 'grid_code_please_refer_to_section_3_5', label: 'Grid code：please refer to section 3.5', registerType: 'read', address: 45201, valueKind: 'U_WORD' },
  { paramKey: 'overvoltage_protection_value_of_the_first_grid_con_nection', label: 'Overvoltage protection value of the first grid con- nection', unit: 'V', registerType: 'read', address: 45202, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'overvoltage_protection_value_of_the_first_grid_con_nection_2', label: 'Overvoltage protection value of the first grid con- nection', unit: 'V', registerType: 'read', address: 45203, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'overvoltage_protection_value_of_the_first_grid_con_nection_3', label: 'Overvoltage protection value of the first grid con- nection', unit: 'Hz', registerType: 'read', address: 45204, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'underfrequency_protec_tion_value_for_first_grid_connection', label: 'Underfrequency protec- tion value for first grid connection', unit: 'Hz', registerType: 'read', address: 45205, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'grid_voltage_high_limit3', label: 'Grid Voltage High Limit3', unit: 'V', registerType: 'read', address: 45206, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'grid_voltage_high_limit_time3', label: 'Grid Voltage High Limit Time3', unit: 'ms', registerType: 'read', address: 45207, valueKind: 'U_DWORD' },
  { paramKey: 'grid_voltage_high_limit2', label: 'Grid Voltage High Limit2', unit: 'V', registerType: 'read', address: 45209, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'grid_voltage_high_limit_time2', label: 'Grid Voltage High Limit Time2', unit: 'ms', registerType: 'read', address: 45210, valueKind: 'U_DWORD' },
  { paramKey: 'grid_voltage_high_limit1', label: 'Grid Voltage High Limit1', unit: 'V', registerType: 'read', address: 45212, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'grid_voltage_high_limit_time1', label: 'Grid Voltage High Limit Time1', unit: 'ms', registerType: 'read', address: 45213, valueKind: 'U_DWORD' },
  { paramKey: 'grid_voltage_low_limit3', label: 'Grid Voltage Low Limit3', unit: 'V', registerType: 'read', address: 45215, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'grid_voltage_low_limit_time3', label: 'Grid Voltage Low Limit Time3', unit: 'ms', registerType: 'read', address: 45216, valueKind: 'U_DWORD' },
  { paramKey: 'grid_voltage_low_limit2', label: 'Grid Voltage Low Limit2', unit: 'V', registerType: 'read', address: 45218, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'grid_voltage_low_limit_time2', label: 'Grid Voltage Low Limit Time2', unit: 'ms', registerType: 'read', address: 45219, valueKind: 'U_DWORD' },
  { paramKey: 'grid_voltage_low_limit1', label: 'Grid Voltage Low Limit1', unit: 'V', registerType: 'read', address: 45221, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'grid_voltage_low_limit_time1', label: 'Grid Voltage Low Limit Time1', unit: 'ms', registerType: 'read', address: 45222, valueKind: 'U_DWORD' },
  { paramKey: '10_minutes_average_overvoltage_threshold', label: '10 Minutes Average Overvoltage Threshold', unit: 'V', registerType: 'read', address: 45224, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: '10_minutes_average_overvoltage_portect_time', label: '10 Minutes Average Overvoltage Portect Time', unit: 'ms', registerType: 'read', address: 45225, valueKind: 'U_WORD' },
  { paramKey: 'overvoltage_recover_value', label: 'Overvoltage recover value', unit: 'V', registerType: 'read', address: 45226, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'undervoltage_recover_value', label: 'Undervoltage recover value', unit: 'V', registerType: 'read', address: 45227, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'grid_frequency_high_limit3', label: 'Grid Frequency High Limit3', unit: 'Hz', registerType: 'read', address: 45228, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'grid_frequency_high_limit_time3', label: 'Grid Frequency High Limit Time3', unit: 'ms', registerType: 'read', address: 45229, valueKind: 'U_DWORD' },
  { paramKey: 'grid_frequency_high_limit2', label: 'Grid Frequency High Limit2', unit: 'Hz', registerType: 'read', address: 45231, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'grid_frequency_high_limit_time2', label: 'Grid Frequency High Limit Time2', unit: 'ms', registerType: 'read', address: 45232, valueKind: 'U_DWORD' },
  { paramKey: 'grid_frequency_high_limit1', label: 'Grid Frequency High Limit1', unit: 'Hz', registerType: 'read', address: 45234, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'grid_frequency_high_limit_time1', label: 'Grid Frequency High Limit Time1', unit: 'ms', registerType: 'read', address: 45235, valueKind: 'U_DWORD' },
  { paramKey: 'grid_frequency_low_limit3', label: 'Grid Frequency Low Limit3', unit: 'Hz', registerType: 'read', address: 45237, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'grid_frequency_low_limit_time3', label: 'Grid Frequency Low Limit Time3', unit: 'ms', registerType: 'read', address: 45238, valueKind: 'U_DWORD' },
  { paramKey: 'grid_frequency_low_limit2', label: 'Grid Frequency Low Limit2', unit: 'Hz', registerType: 'read', address: 45240, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'grid_frequency_low_limit_time2', label: 'Grid Frequency Low Limit Time2', unit: 'ms', registerType: 'read', address: 45241, valueKind: 'U_DWORD' },
  { paramKey: 'grid_frequency_low_limit1', label: 'Grid Frequency Low Limit1', unit: 'Hz', registerType: 'read', address: 45243, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'grid_frequency_low_limit_time1', label: 'Grid Frequency Low Limit Time1', unit: 'ms', registerType: 'read', address: 45244, valueKind: 'U_DWORD' },
  { paramKey: 'vary_rate_of_frequecny_protect_value', label: 'Vary rate of Frequecny protect value', unit: 'Hz/s', registerType: 'read', address: 45246, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'vary_rate_of_frequecny_protect_time', label: 'Vary rate of Frequecny protect time', unit: 'ms', registerType: 'read', address: 45247, valueKind: 'U_DWORD' },
  { paramKey: 'overfrequency_recover_value', label: 'Overfrequency recover value', unit: 'Hz', registerType: 'read', address: 45249, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'underfrequency_recover_value', label: 'Underfrequency recover value', unit: 'Hz', registerType: 'read', address: 45250, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'time_of_first_connection_to_grid', label: 'Time of first connection to grid', unit: 's', registerType: 'read', address: 45251, valueKind: 'U_WORD' },
  { paramKey: 'time_of_re_connection_to_grid', label: 'Time of re-connection to grid', unit: 's', registerType: 'read', address: 45252, valueKind: 'U_WORD' },
  { paramKey: 'iso_protect_threshold', label: 'ISO protect threshold', unit: 'kΩ', registerType: 'read', address: 45253, valueKind: 'U_WORD' },
  { paramKey: 'dci_protect_threshold', label: 'DCI protect threshold', unit: 'mA', registerType: 'read', address: 45254, valueKind: 'U_WORD' },
  { paramKey: 'dci_protect_time', label: 'DCI protect time', unit: 'ms', registerType: 'read', address: 45255, valueKind: 'U_WORD' },
  { paramKey: 'load_rate_of_first_connec_tion_to_grid', label: 'Load rate of first connec- tion to grid', unit: '%Pn/min', registerType: 'read', address: 45401, valueKind: 'U_WORD' },
  { paramKey: 'load_rate_of_re_connec_tion_to_grid', label: 'Load rate of re-connec- tion to grid', unit: '%Pn/min', registerType: 'read', address: 45402, valueKind: 'U_WORD' },
  { paramKey: 'active_power_set', label: 'Active Power Set', unit: '%Pn', registerType: 'read', address: 45403, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'increase_rate_of_active_power', label: 'Increase rate of active power', unit: '%Pn/min', registerType: 'read', address: 45404, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'decrease_rate_of_active_power', label: 'Decrease rate of active power', unit: '%Pn/min', registerType: 'read', address: 45405, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'over_frequency_reduce_power_mode_0_none_1_fixed_reduction_ratio_non_hysteresis_2', label: 'Over frequency reduce power mode： 0 = None 1 = Fixed reduction ratio, non – hysteresis 2 = Fixed reduction ratio, hysteresis 3 = Not fixed reduction ratio, non – hysteresis 4 = Not fixed reduction ratio, hysteresis 5 = Three points over fre- quency reduce power, non – hysteresis 6 = Three points over fre- quency reduce power, hysteresis 7 = Energy storage Italy over frequency reduce power, non – hysteresis', registerType: 'read', address: 45408, valueKind: 'U_WORD' },
  { paramKey: 'over_frequency_reduce_power_start_frequency', label: 'Over frequency reduce power: Start frequency', unit: 'Hz', registerType: 'read', address: 45409, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'over_frequency_reduce_power_stop_frequecny', label: 'Over frequency reduce power: Stop frequecny', unit: 'Hz', registerType: 'read', address: 45410, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'over_frequency_reduce_power_back_frequency', label: 'Over frequency reduce power: Back frequency', unit: 'Hz', registerType: 'read', address: 45411, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'the_reduce_ratio_of_over_frequency_reduce_power', label: 'The reduce ratio of over frequency reduce power', unit: '%Pnor%Pm', registerType: 'read', address: 45412, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'over_frequency_reduce_power_reduce_power_de_lay_time', label: 'Over frequency reduce power :reduce power de- lay time', unit: 's', registerType: 'read', address: 45413, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'over_frequency_reduce_power_recover_power_de_lay_time', label: 'Over frequency reduce power:recover power de- lay time', unit: 's', registerType: 'read', address: 45414, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'speed_of_over_frequency_recover_to_pn', label: 'Speed of Over frequency recover to Pn', unit: '%Pn/min', registerType: 'read', address: 45416, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'over_frequency_reduce_power_0_power_frequency_point', label: 'Over frequency reduce power(*): 0 power frequency point', unit: 'Hz', registerType: 'read', address: 45417, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'over_voltage_reduce_power_mode_0_none_1_not_fixed_reduction_ratio_non_hysteresis', label: 'Over voltage reduce power mode： 0 = None 1 = Not fixed reduction ratio, non – hysteresis 2 = Not fixed reduction ratio, hysteresis 3 = Fixed reduction ratio, non – hysteresis 4 = Fixed reduction ratio, hysteresis 5 = Taiwan\'s autonomous power regulation 6 = Trina Solar customiza- tion mode', registerType: 'read', address: 45419, valueKind: 'U_WORD' },
  { paramKey: 'over_voltage_reduce_power_start_voltage', label: 'Over voltage reduce power: Start voltage', unit: '%Un', registerType: 'read', address: 45420, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'over_voltage_reduce_power_stop_voltage', label: 'Over voltage reduce power: Stop voltage', unit: '%Un', registerType: 'read', address: 45422, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'over_voltage_reduce_power_back_voltage', label: 'Over voltage reduce power: Back voltage', unit: '%Un', registerType: 'read', address: 45424, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'the_reduce_ratio_of_over_voltage_reduce_power', label: 'The reduce ratio of over voltage reduce power', unit: '%Pnor%Pm', registerType: 'read', address: 45426, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'over_voltage_reduce_power_delay_time', label: 'Over voltage reduce power delay time', unit: 's', registerType: 'read', address: 45427, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'over_voltage_recover_power_delay_time', label: 'Over voltage recover power delay time', unit: 's', registerType: 'read', address: 45428, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'speed_of_over_voltage_re_cover_to_pn', label: 'Speed of Over voltage re- cover to Pn', unit: '%Pn/min', registerType: 'read', address: 45429, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'under_frequency_in_crease_power_mode_0_none_1_fixed_reduction_ratio_non_hysteres', label: 'Under frequency in- crease power mode： 0 = None 1 = Fixed reduction ratio, non – hysteresis 2 = Fixed reduction ratio, hysteresis 3 = Not fixed reduction ratio, non – hysteresis 4 = Not fixed reduction ratio, hysteresis 5 = Three points under frequency increase power, non – hysteresis 6 = Three points under frequency increase power, hysteresis 7 = Energy storage Italy under frequency increase power, non – hysteresis 8 = Energy storage Italy under frequency increase power, hysteresis', registerType: 'read', address: 45432, valueKind: 'U_WORD' },
  { paramKey: 'under_frequency_in_crease_power_start_frequency', label: 'Under frequency in- crease power: Start frequency', unit: 'Hz', registerType: 'read', address: 45433, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'under_frequency_in_crease_power_stop_frequecny', label: 'Under frequency in- crease power: Stop frequecny', unit: 'Hz', registerType: 'read', address: 45434, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'under_frequency_in_crease_power_back_frequency', label: 'Under frequency in- crease power: Back frequency', unit: 'Hz', registerType: 'read', address: 45435, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'the_increase_ratio_of_un_der_frequency_increase_power', label: 'The increase ratio of un- der frequency increase power', unit: '%Pnor%Pm', registerType: 'read', address: 45436, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'under_frequency_in_crease_power_delay_time', label: 'Under frequency in- crease power delay time', unit: 's', registerType: 'read', address: 45437, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'under_frequency_recover_power_delay_time', label: 'Under frequency recover power delay time', unit: 's', registerType: 'read', address: 45438, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'speed_of_under_fre_quency_recover_to_pn', label: 'Speed of Under fre- quency recover to Pn', unit: '%Pn/min', registerType: 'read', address: 45440, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'under_frequency_in_crease_power_0_power_frequency_point', label: 'Under frequency in- crease power 0 power frequency point', unit: 'Hz', registerType: 'read', address: 45441, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'under_voltage_increase_power_mode_0_none_1_fixed_increase_ratio_non_hysteresis_2', label: 'Under voltage increase power mode： 0 = None 1 = Fixed increase ratio, non – hysteresis 2 = Fixed increase ratio, hysteresis 3 = Not fixed increase ra- tio, non – hysteresis 4 = Not fixed increase ra- tio, hysteresis', registerType: 'read', address: 45443, valueKind: 'U_WORD' },
  { paramKey: 'under_voltage_increase_power_start_voltage', label: 'Under voltage increase power: Start voltage', unit: '%Un', registerType: 'read', address: 45444, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'under_voltage_increase_power_stop_voltage', label: 'Under voltage increase power: Stop voltage', unit: '%Un', registerType: 'read', address: 45445, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'under_voltage_increase_power', label: 'Under voltage increase power:', unit: '%Un', registerType: 'read', address: 45446, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'the_increase_ratio_of_un_der_voltage_increase_power', label: 'The increase ratio of un- der voltage increase power', unit: '%Pnor%Pm', registerType: 'read', address: 45447, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'under_voltage_increase_power_delay_time', label: 'Under voltage increase power delay time', unit: 's', registerType: 'read', address: 45448, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'under_voltage_increase_power_delay_time_2', label: 'Under voltage increase power delay time', unit: 's', registerType: 'read', address: 45449, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'speed_of_under_voltage_recover_to_pn', label: 'Speed of under voltage recover to Pn', unit: '%Pn/min', registerType: 'read', address: 45450, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'pav', label: 'Pav(*)', unit: '%Pn', registerType: 'read', address: 45451, valueKind: 'S_WORD', scale: 0.01 },
  { paramKey: 'drms_pval', label: 'DRMs Pval(*)', unit: '%Pn', registerType: 'read', address: 45452, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'reactive_power_control_mode_0_none_1_fixed_power_factor_2_cos_p_curve_3_fixed_q_', label: 'Reactive power control mode： 0 = None 1 = Fixed power factor 2 = cos φ(P) curve 3 = Fixed Q value 4 = Fixed Q value of AU DRMs 5 = Linear Q(U) curve 6 = Hysteresis Q(U) curve 7 = Taiwan\'s autonomous control and regulation', registerType: 'read', address: 45501, valueKind: 'U_WORD' },
  { paramKey: 'time_constant_of_reactive_power_curve', label: 'Time constant of reactive power curve', unit: 's', registerType: 'read', address: 45502, valueKind: 'U_WORD' },
  { paramKey: 'power_factor_2', label: 'Power factor', registerType: 'read', address: 45503, valueKind: 'S_WORD', scale: 0.0001 },
  { paramKey: 'cos_p_curve_active_power_of_the_first_point', label: 'cos φ(P) curve： Active power of the first point', unit: '%Pn', registerType: 'read', address: 45504, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'cos_p_curve_cos_of_the_first_point', label: 'cos φ(P) curve： cos φ of the first point', registerType: 'read', address: 45505, valueKind: 'S_WORD', scale: 0.0001 },
  { paramKey: 'cos_p_curve_active_power_of_the_sec_ond_point', label: 'cos φ(P) curve： Active power of the sec- ond point', unit: '%Pn', registerType: 'read', address: 45506, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'cos_p_curve_cos_of_the_second_point', label: 'cos φ(P) curve： cos φ of the second point', registerType: 'read', address: 45507, valueKind: 'S_WORD', scale: 0.0001 },
  { paramKey: 'cos_p_curve', label: 'cos φ(P) curve：', unit: '%Pn', registerType: 'read', address: 45508, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'cos_p_curve_cos_of_the_third_point', label: 'cos φ(P) curve： cos φ of the third point', registerType: 'read', address: 45509, valueKind: 'S_WORD', scale: 0.0001 },
  { paramKey: 'cos_p_curve_active_power_of_the_fourth_point', label: 'cos φ(P) curve： Active power of the fourth point', unit: '%Pn', registerType: 'read', address: 45510, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'cos_p_curve_cos_of_the_fourth_point', label: 'cos φ(P) curve： cos φ of the fourth point', registerType: 'read', address: 45511, valueKind: 'S_WORD', scale: 0.0001 },
  { paramKey: 'lock_in_voltage_for_cos_p_curve', label: 'Lock in voltage (for cos φ(P) curve）', unit: '%Un', registerType: 'read', address: 45512, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'lock_out_voltage_for_cos_p_curve', label: 'Lock out voltage (for cos φ(P) curve)', unit: '%Un', registerType: 'read', address: 45513, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'q_set_value', label: 'Q Set Value', unit: '%Sn', registerType: 'read', address: 45516, valueKind: 'S_WORD', scale: 0.01 },
  { paramKey: 'q_u_curve_u_of_the_first_point', label: 'Q(U) curve： U  of the first point', unit: '%Un', registerType: 'read', address: 45518, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'q_u_curve_q_of_the_first_point', label: 'Q(U) curve： Q of the first point', unit: '%Sn', registerType: 'read', address: 45519, valueKind: 'S_WORD', scale: 0.01 },
  { paramKey: 'q_u_curve_u_of_the_second_point', label: 'Q(U) curve： U  of the second point', unit: '%Un', registerType: 'read', address: 45520, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'q_u_curve_q_of_the_second_point', label: 'Q(U) curve： Q of the second point', unit: '%Sn', registerType: 'read', address: 45521, valueKind: 'S_WORD', scale: 0.01 },
  { paramKey: 'q_u_curve_u_of_the_third_point', label: 'Q(U) curve： U  of the third point', unit: '%Un', registerType: 'read', address: 45522, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'q_u_curve_q_of_the_third_point', label: 'Q(U) curve： Q of the third point', unit: '%Sn', registerType: 'read', address: 45523, valueKind: 'S_WORD', scale: 0.01 },
  { paramKey: 'q_u_curve_u_of_the_fourth_point', label: 'Q(U) curve： U  of the fourth point', unit: '%Un', registerType: 'read', address: 45524, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'q_u_curve_q_of_the_fourth_point', label: 'Q(U) curve： Q of the fourth point', unit: '%Sn', registerType: 'read', address: 45525, valueKind: 'S_WORD', scale: 0.01 },
  { paramKey: 'lock_in_power_for_q_u_curve', label: 'Lock in power（for Q(U) curve）', unit: '%Pn', registerType: 'read', address: 45526, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'lock_outpower_for_q_u_curve', label: 'Lock outpower（for Q(U) curve）', unit: '%Pn', registerType: 'read', address: 45527, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'lvrt_reactive_current_cal_culation_mode_0_none_1_gb_t_19964', label: 'LVRT reactive current cal- culation mode： 0 = None 1 = GB/T 19964', registerType: 'read', address: 45601, valueKind: 'U_WORD' },
  { paramKey: 'lvrt_three_phase_fault_reactive_current_limit', label: 'LVRT three phase fault reactive current limit', unit: '%In', registerType: 'read', address: 45602, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'lvrt_single_double_phase_fault_reactive_current_limit', label: 'LVRT single/double phase fault reactive current limit', unit: '%In', registerType: 'read', address: 45603, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'lvrt_fault_detection_volt_age_type_0_phase_voltage_1_line_voltage_2_positive_seq', label: 'LVRT fault detection volt- age type： 0 = Phase voltage 1 = Line voltage 2 = Positive sequence voltage', registerType: 'read', address: 45604, valueKind: 'U_WORD' },
  { paramKey: 'threshold_of_insensitive_area_of_positive_sequence_voltage_jump', label: 'Threshold of insensitive area of positive sequence voltage jump', unit: '%Un', registerType: 'read', address: 45605, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'lvrt_trigger_voltage', label: 'LVRT Trigger voltage', unit: '%Un', registerType: 'read', address: 45606, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'k_factor_of_positive_se_quence_reactive_current', label: 'K-factor of positive se- quence reactive current', registerType: 'read', address: 45607, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'reactive_power_mainte_nance_after_lvrt_voltage_recovery', label: 'reactive power mainte- nance after LVRT voltage recovery', unit: 'ms', registerType: 'read', address: 45608, valueKind: 'U_WORD' },
  { paramKey: 'lvrt_active_power_limit_mode_0_active_power_first_1_active_power_reduced_to_belo', label: 'LVRT active power limit mode： 0 = Active power first 1 = Active power reduced to below 10% In 2 = Unlimited active power', registerType: 'read', address: 45609, valueKind: 'U_WORD' },
  { paramKey: 'hvrt_reactive_current_calculation_mode_0_none_1_gb_t_19964_2_bdew', label: 'HVRT reactive current calculation mode： 0 = None 1 = GB/T 19964 2 = BDEW', registerType: 'read', address: 45610, valueKind: 'U_WORD' },
  { paramKey: 'hvrt_three_phase_fault_reactive_current_limit', label: 'HVRT three phase fault reactive current limit', unit: '%In', registerType: 'read', address: 45611, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'hvrt_single_double_phase_fault_reactive_cur_rent_limit', label: 'HVRT single/double phase fault reactive cur- rent limit', unit: '%In', registerType: 'read', address: 45612, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'hvrt_fault_detection_voltage_type', label: 'HVRT fault detection voltage type:', registerType: 'read', address: 45613, valueKind: 'U_WORD' },
  { paramKey: 'threshold_of_insensitive_area_of_negative_se_quence_voltage_jump', label: 'Threshold of insensitive area of negative se- quence voltage jump', unit: '%Un', registerType: 'read', address: 45614, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'hvrt_trigger_voltage', label: 'HVRT Trigger voltage', unit: '%Un', registerType: 'read', address: 45615, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'k_factor_of_negative_se_quence_reactive_current', label: 'K-factor of negative se- quence reactive current', registerType: 'read', address: 45616, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'reactive_power_mainte_nance_after_hvrt_voltage_recovery', label: 'reactive power mainte- nance after HVRT voltage recovery', unit: 'ms', registerType: 'read', address: 45617, valueKind: 'U_WORD' },
  { paramKey: 'hvrt_active_power_limit_mode_0_active_power_first_1_active_power_reduced_to_belo', label: 'HVRT active power limit mode: 0 = Active power first 1 = Active power reduced to below 10% In 2 = Unlimited active power', registerType: 'read', address: 45618, valueKind: 'U_WORD' },
  { paramKey: 'zero_current_threshold', label: 'Zero current threshold', unit: '%Un', registerType: 'read', address: 45619, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'afci_self_test_status_0_self_test_failed_1_self_test_successful', label: 'AFCI self-test status: 0 = self-test failed 1 = self-test successful', registerType: 'read', address: 46520, valueKind: 'U_WORD' },
  { paramKey: 'afci_detection_sensitivity_settings_0_high_detection_accuracy_1_low_detection_ac', label: 'AFCI detection sensitivity settings: 0 = high detection accuracy 1 = low detection accuracy', registerType: 'read', address: 46521, valueKind: 'U_WORD' },
  { paramKey: 'afci_fault_reset_method_selection_0_automatic_mode_1_manual_mode', label: 'AFCI fault reset method selection: 0 = automatic mode 1 = manual mode', registerType: 'read', address: 46522, valueKind: 'U_WORD' },
  { paramKey: 'reset_faults_manually_0_no_need_1_manual_clear_fault_active_in_arc_fault_and_man', label: 'Reset faults manually: 0 = no need 1 = Manual clear fault (active in arc fault and manual reset mode)', registerType: 'read', address: 46523, valueKind: 'U_WORD' },
  { paramKey: 'phase_1_line_to_neutral_volts', label: 'Phase 1 line to neutral volts', unit: 'V', registerType: 'read', address: 46401, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'phase_2_line_to_neutral_volts', label: 'Phase 2 line to neutral volts', unit: 'V', registerType: 'read', address: 46402, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'phase_3_line_to_neutral_volts', label: 'Phase 3 line to neutral volts', unit: 'V', registerType: 'read', address: 46403, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'phase_1_current', label: 'Phase 1 current', unit: 'A', registerType: 'read', address: 46404, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'phase_2_current', label: 'Phase 2 current', unit: 'A', registerType: 'read', address: 46405, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'phase_3_current', label: 'Phase 3 current', unit: 'A', registerType: 'read', address: 46406, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'phase_1_power', label: 'Phase 1 power', unit: 'w', registerType: 'read', address: 46407, valueKind: 'S_DWORD' },
  { paramKey: 'phase_2_power', label: 'Phase 2 power', unit: 'w', registerType: 'read', address: 46409, valueKind: 'S_DWORD' },
  { paramKey: 'phase_3_power', label: 'Phase 3 power', unit: 'w', registerType: 'read', address: 46411, valueKind: 'S_DWORD' },
  { paramKey: 'phase_1_volt_amps', label: 'Phase 1 volt amps', unit: 'VA', registerType: 'read', address: 46413, valueKind: 'U_DWORD' },
  { paramKey: 'phase_2_volt_amps', label: 'Phase 2 volt amps', unit: 'VA', registerType: 'read', address: 46415, valueKind: 'U_DWORD' },
  { paramKey: 'phase_3_volt_amps', label: 'Phase 3 volt amps', unit: 'VA', registerType: 'read', address: 46417, valueKind: 'U_DWORD' },
  { paramKey: 'phase_1_volt_amps_reactive', label: 'Phase 1 volt amps reactive', unit: 'Var', registerType: 'read', address: 46419, valueKind: 'S_DWORD' },
  { paramKey: 'phase_2_volt_amps_reactive', label: 'Phase 2 volt amps reactive', unit: 'Var', registerType: 'read', address: 46421, valueKind: 'S_DWORD' },
  { paramKey: 'phase_3_volt_amps_reactive', label: 'Phase 3 volt amps reactive', unit: 'Var', registerType: 'read', address: 46423, valueKind: 'S_DWORD' },
  { paramKey: 'phase_1_power_factor', label: 'Phase 1 power factor', registerType: 'read', address: 46425, valueKind: 'S_WORD', scale: 0.01 },
  { paramKey: 'phase_2_power_factor', label: 'Phase 2 power factor', registerType: 'read', address: 46426, valueKind: 'S_WORD', scale: 0.01 },
  { paramKey: 'phase_3_power_factor', label: 'Phase 3 power factor', registerType: 'read', address: 46427, valueKind: 'S_WORD', scale: 0.01 },
  { paramKey: 'phase_1_phase_angle', label: 'Phase 1 phase angle', unit: '°', registerType: 'read', address: 46428, valueKind: 'U_WORD' },
  { paramKey: 'phase_2_phase_angle', label: 'Phase 2 phase angle', unit: '°', registerType: 'read', address: 46429, valueKind: 'U_WORD' },
  { paramKey: 'phase_3_phase_angle', label: 'Phase 3 phase angle', unit: '°', registerType: 'read', address: 46430, valueKind: 'U_WORD' },
  { paramKey: 'average_line_to_neutral_volts', label: 'Average line to neutral volts', unit: 'V', registerType: 'read', address: 46431, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'average_line_current', label: 'Average line current', unit: 'A', registerType: 'read', address: 46432, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'sum_of_line_currents', label: 'Sum of line currents', unit: 'A', registerType: 'read', address: 46433, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'total_systempower', label: 'Total systempower', unit: 'w', registerType: 'read', address: 46434, valueKind: 'S_DWORD' },
  { paramKey: 'total_systemvolt_amps', label: 'Total systemvolt amps', unit: 'VA', registerType: 'read', address: 46436, valueKind: 'U_DWORD' },
  { paramKey: 'total_system_var', label: 'Total system VAr', unit: 'Var', registerType: 'read', address: 46438, valueKind: 'S_DWORD' },
  { paramKey: 'total_systempower_factor', label: 'Total systempower factor', registerType: 'read', address: 46440, valueKind: 'S_WORD', scale: 0.01 },
  { paramKey: 'total_systemphase_angle', label: 'Total systemphase angle', unit: '°', registerType: 'read', address: 46441, valueKind: 'U_WORD' },
  { paramKey: 'frequency_of_supply_voltages', label: 'Frequency of supply voltages', unit: 'Hz', registerType: 'read', address: 46442, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'import_wh_since_last_reset', label: 'Import Wh since last reset', unit: 'Wh', registerType: 'read', address: 46443, valueKind: 'U_DWORD' },
  { paramKey: 'export_wh_since_last_reset', label: 'Export Wh since last reset', unit: 'Wh', registerType: 'read', address: 46445, valueKind: 'U_DWORD' },
  { paramKey: 'import_varh_since_last_reset', label: 'Import Varh since last reset', unit: 'Varh', registerType: 'read', address: 46447, valueKind: 'U_DWORD' },
  { paramKey: 'export_varh_since_lastreset', label: 'Export Varh since lastreset', unit: 'Varh', registerType: 'read', address: 46449, valueKind: 'U_DWORD' },
];
