import type { DriverRegister } from '../driverStore.js';

export const m4mRegisters: DriverRegister[] = [
  { paramKey: "active_energy_import", label: "Active energy - import", unit: "kWh", registerType: "read", address: 20480, valueKind: "S_QWORD", scale: 0.01, precision: 2 },
  { paramKey: "active_energy_export", label: "Active energy - export", unit: "kWh", registerType: "read", address: 20484, valueKind: "S_QWORD", scale: 0.01, precision: 2 },
  { paramKey: "active_energy_net", label: "Active energy - net", unit: "kWh", registerType: "read", address: 20488, valueKind: "S_QWORD", scale: 0.01, precision: 2 },
  { paramKey: "reactive_energy_import", label: "Reactive energy - import", unit: "kvarh", registerType: "read", address: 20492, valueKind: "S_QWORD", scale: 0.01, precision: 2 },
  { paramKey: "reactive_energy_export", label: "Reactive energy - export", unit: "kvarh", registerType: "read", address: 20496, valueKind: "S_QWORD", scale: 0.01, precision: 2 },
  { paramKey: "reactive_energy_net", label: "Reactive energy - net", unit: "kvarh", registerType: "read", address: 20500, valueKind: "S_QWORD", scale: 0.01, precision: 2 },
  { paramKey: "apparent_energy_import", label: "Apparent energy - import", unit: "kVA", registerType: "read", address: 20504, valueKind: "S_QWORD", scale: 0.01, precision: 2 },
  { paramKey: "apparent_energy_export", label: "Apparent energy - export", unit: "kVA", registerType: "read", address: 20508, valueKind: "S_QWORD", scale: 0.01, precision: 2 },
  { paramKey: "apparent_energy_net", label: "Apparent energy - net", unit: "kVA", registerType: "read", address: 20512, valueKind: "S_QWORD", scale: 0.01, precision: 2 },
  { paramKey: "active_energy_import_co2_conversion_factor", label: "Active energy - import (CO2 conversion factor)", unit: "kg / kWh", registerType: "read", address: 20516, valueKind: "S_QWORD", scale: 0.001, precision: 3 },
  { paramKey: "active_energy_import_currency_conversion_factor", label: "Active energy - import (Currency conversion factor)", unit: "Currency / kWh", registerType: "read", address: 20532, valueKind: "S_QWORD", scale: 0.001, precision: 3 },
  { paramKey: "active_energy_import_tariffs_tariff_from_1_to_6", label: "Active energy - import (Tariffs) (Tariff from 1 to 6)", unit: "kWh", registerType: "read", address: 20848, valueKind: "S_QWORD", scale: 0.01, precision: 2 },
  { paramKey: "active_energy_export_tariffs_tariff_from_1_to_6", label: "Active energy - export (Tariffs) (Tariff from 1 to 6)", unit: "kWh", registerType: "read", address: 20880, valueKind: "S_QWORD", scale: 0.01, precision: 2 },
  { paramKey: "reactive_energy_import_tariffs_tariff_from_1_to_6", label: "Reactive energy - import (Tariffs) (Tariff from 1 to 6)", unit: "kvarh", registerType: "read", address: 20912, valueKind: "S_QWORD", scale: 0.01, precision: 2 },
  { paramKey: "reactive_energy_export_tariffs_tariff_from_1_to_6", label: "Reactive energy - export (Tariffs) (Tariff from 1 to 6)", unit: "kvarh", registerType: "read", address: 20944, valueKind: "S_QWORD", scale: 0.01, precision: 2 },
  { paramKey: "active_energy_import_l1_l2_l3", label: "Active energy - import (L1, L2, L3)", unit: "kWh", registerType: "read", address: 21600, valueKind: "S_QWORD", scale: 0.01, precision: 2 },
  { paramKey: "active_energy_export_l1_l2_l3", label: "Active energy - export (L1, L2, L3)", unit: "kWh", registerType: "read", address: 21612, valueKind: "S_QWORD", scale: 0.01, precision: 2 },
  { paramKey: "active_energy_net_l1_l2_l3", label: "Active energy - net (L1, L2, L3)", unit: "kWh", registerType: "read", address: 21624, valueKind: "S_QWORD", scale: 0.01, precision: 2 },
  { paramKey: "reactive_energy_import_l1_l2_l3", label: "Reactive energy - import (L1, L2, L3)", unit: "kvarh", registerType: "read", address: 21636, valueKind: "S_QWORD", scale: 0.01, precision: 2 },
  { paramKey: "reactive_energy_export_l1_l2_l3", label: "Reactive energy - export (L1, L2, L3)", unit: "kvarh", registerType: "read", address: 21648, valueKind: "S_QWORD", scale: 0.01, precision: 2 },
  { paramKey: "reactive_energy_net_l1_l2_l3", label: "Reactive energy - net (L1, L2, L3)", unit: "kvarh", registerType: "read", address: 21660, valueKind: "S_QWORD", scale: 0.01, precision: 2 },
  { paramKey: "apparent_energy_import_l1_l2_l3", label: "Apparent energy - import (L1, L2, L3)", unit: "kVA", registerType: "read", address: 21672, valueKind: "S_QWORD", scale: 0.01, precision: 2 },
  { paramKey: "apparent_energy_export_l1_l2_l3", label: "Apparent energy - export (L1, L2, L3)", unit: "kVA", registerType: "read", address: 21684, valueKind: "S_QWORD", scale: 0.01, precision: 2 },
  { paramKey: "apparent_energy_net_l1_l2_l3", label: "Apparent energy - net (L1, L2, L3)", unit: "kVA", registerType: "read", address: 21696, valueKind: "S_QWORD", scale: 0.01, precision: 2 },
  { paramKey: "three_phase_system_voltage", label: "Three phase system voltage", unit: "V", registerType: "read", address: 23296, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "phase_voltage_l1_l1", label: "Phase voltage L1 (L1)", unit: "V", registerType: "read", address: 23298, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "phase_voltage_l2_l2", label: "Phase voltage L2 (L2)", unit: "V", registerType: "read", address: 23300, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "phase_voltage_l3_l3", label: "Phase voltage L3 (L3)", unit: "V", registerType: "read", address: 23302, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "line_voltage_l1_l2_l1_l2", label: "Line voltage L1-L2 (L1-L2)", unit: "V", registerType: "read", address: 23304, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "line_voltage_l3_l2_l3_l2", label: "Line voltage L3-L2 (L3-L2)", unit: "V", registerType: "read", address: 23306, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "line_voltage_l1_l3_l1_l3", label: "Line voltage L1-L3 (L1-L3)", unit: "V", registerType: "read", address: 23308, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "three_phase_system_current", label: "Three phase system current", unit: "A", registerType: "read", address: 23310, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "current_l1", label: "Current (L1)", unit: "A", registerType: "read", address: 23312, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "current_l2", label: "Current (L2)", unit: "A", registerType: "read", address: 23314, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "current_l3", label: "Current (L3)", unit: "A", registerType: "read", address: 23316, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "current_n", label: "Current (N)", unit: "A", registerType: "read", address: 23318, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "active_power_total", label: "Active power (Total)", unit: "W", registerType: "read", address: 23322, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "active_power_l1", label: "Active power (L1)", unit: "W", registerType: "read", address: 23324, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "active_power_l2", label: "Active power (L2)", unit: "W", registerType: "read", address: 23326, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "active_power_l3", label: "Active power (L3)", unit: "W", registerType: "read", address: 23328, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "reactive_power_total", label: "Reactive power (Total)", unit: "var", registerType: "read", address: 23330, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "reactive_power_l1", label: "Reactive power (L1)", unit: "var", registerType: "read", address: 23332, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "reactive_power_l2", label: "Reactive power (L2)", unit: "var", registerType: "read", address: 23334, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "reactive_power_l3", label: "Reactive power (L3)", unit: "var", registerType: "read", address: 23336, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "apparent_power_total", label: "Apparent power (Total)", unit: "VA", registerType: "read", address: 23338, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "apparent_power_l1", label: "Apparent power (L1)", unit: "VA", registerType: "read", address: 23340, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "apparent_power_l2", label: "Apparent power (L2)", unit: "VA", registerType: "read", address: 23342, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "apparent_power_l3", label: "Apparent power (L3)", unit: "VA", registerType: "read", address: 23344, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "frequency", label: "Frequency", unit: "Hz", registerType: "read", address: 23346, valueKind: "S_WORD", scale: 0.01, precision: 2 },
  { paramKey: "phase_angles_power_total_l1_l2_l3", label: "Phase angles power (Total, L1, L2, L3)", unit: "\u00b0", registerType: "read", address: 23347, valueKind: "S_QWORD", scale: 0.1, precision: 1 },
  { paramKey: "phase_angles_voltage_l1_l2_l3", label: "Phase angles voltage (L1, L2, L3)", unit: "\u00b0", registerType: "read", address: 23351, valueKind: "S_WORD", scale: 0.1, precision: 1 },
  { paramKey: "phase_angles_current_l1_l2_l3", label: "Phase angles current (L1, L2, L3)", unit: "\u00b0", registerType: "read", address: 23357, valueKind: "S_WORD", scale: 0.1, precision: 1 },
  { paramKey: "power_factors_total", label: "Power factors (Total)", registerType: "read", address: 23360, valueKind: "S_WORD", scale: 0.001, precision: 3 },
  { paramKey: "power_factors_l1", label: "Power factors (L1)", registerType: "read", address: 23361, valueKind: "S_WORD", scale: 0.001, precision: 3 },
  { paramKey: "power_factors_l2", label: "Power factors (L2)", registerType: "read", address: 23362, valueKind: "S_WORD", scale: 0.001, precision: 3 },
  { paramKey: "power_factors_l3", label: "Power factors (L3)", registerType: "read", address: 23363, valueKind: "S_WORD", scale: 0.001, precision: 3 },
  { paramKey: "current_quadrant_total_l1_l2_l3", label: "Current quadrant (Total, L1, L2, L3)", registerType: "read", address: 23364, valueKind: "S_QWORD", scale: 1.0, precision: 0 },
  { paramKey: "cosphi_displacement_factor_total", label: "Cosphi (displacement factor) (Total)", unit: "\u00b0", registerType: "read", address: 23368, valueKind: "S_WORD", scale: 0.001, precision: 3 },
  { paramKey: "cosphi_displacement_factor_l1", label: "Cosphi (displacement factor) (L1)", unit: "\u00b0", registerType: "read", address: 23369, valueKind: "S_WORD", scale: 0.001, precision: 3 },
  { paramKey: "cosphi_displacement_factor_l2", label: "Cosphi (displacement factor) (L2)", unit: "\u00b0", registerType: "read", address: 23370, valueKind: "S_WORD", scale: 0.001, precision: 3 },
  { paramKey: "cosphi_displacement_factor_l3", label: "Cosphi (displacement factor) (L3)", unit: "\u00b0", registerType: "read", address: 23371, valueKind: "S_WORD", scale: 0.001, precision: 3 },
  { paramKey: "average_current_l1_data_value", label: "Average current L1 (Data value)", unit: "A", registerType: "read", address: 23508, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "average_current_l2_data_value", label: "Average current L2 (Data value)", unit: "A", registerType: "read", address: 23510, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "average_current_l3_data_value", label: "Average current L3 (Data value)", unit: "A", registerType: "read", address: 23512, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "average_current_neutral_data_value", label: "Average current neutral (Data value)", unit: "A", registerType: "read", address: 23514, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "average_voltage_l1_data_value", label: "Average voltage L1 (Data value)", unit: "V", registerType: "read", address: 23516, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "average_voltage_l2_data_value", label: "Average voltage L2 (Data value)", unit: "V", registerType: "read", address: 23518, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "average_voltage_l3_data_value", label: "Average voltage L3 (Data value)", unit: "V", registerType: "read", address: 23520, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "average_voltage_l1_l2_data_value", label: "Average voltage L1-L2 (Data value)", unit: "V", registerType: "read", address: 23522, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "average_voltage_l2_l3_data_value", label: "Average voltage L2-L3 (Data value)", unit: "V", registerType: "read", address: 23524, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "average_voltage_l1_l3_data_value", label: "Average voltage L1-L3 (Data value)", unit: "V", registerType: "read", address: 23526, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "average_active_power_total_data_value", label: "Average active power total (Data value)", unit: "W", registerType: "read", address: 23528, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "average_active_power_l1_data_value", label: "Average active power L1 (Data value)", unit: "W", registerType: "read", address: 23530, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "average_active_power_l2_data_value", label: "Average active power L2 (Data value)", unit: "W", registerType: "read", address: 23532, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "average_active_power_l3_data_value", label: "Average active power L3 (Data value)", unit: "W", registerType: "read", address: 23534, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "average_reactive_power_total_data_value", label: "Average reactive power total (Data value)", unit: "var", registerType: "read", address: 23536, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "average_reactive_power_l1_data_value", label: "Average reactive power L1 (Data value)", unit: "var", registerType: "read", address: 23538, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "average_reactive_power_l2_data_value", label: "Average reactive power L2 (Data value)", unit: "var", registerType: "read", address: 23540, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "average_reactive_power_l3_data_value", label: "Average reactive power L3 (Data value)", unit: "var", registerType: "read", address: 23542, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "average_apparent_power_total_data_value", label: "Average apparent power total (Data value)", unit: "VA", registerType: "read", address: 23544, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "average_apparent_power_l1_data_value", label: "Average apparent power L1 (Data value)", unit: "VA", registerType: "read", address: 23546, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "average_apparent_power_l2_data_value", label: "Average apparent power L2 (Data value)", unit: "VA", registerType: "read", address: 23548, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "average_apparent_power_l3_data_value", label: "Average apparent power L3 (Data value)", unit: "VA", registerType: "read", address: 23550, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "maximum_current_l1_data_value", label: "Maximum current L1 (Data value)", unit: "A", registerType: "read", address: 23568, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "maximum_current_l2_data_value", label: "Maximum current L2 (Data value)", unit: "A", registerType: "read", address: 23570, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "maximum_current_l3_data_value", label: "Maximum current L3 (Data value)", unit: "A", registerType: "read", address: 23572, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "maximum_current_neutral_data_value", label: "Maximum current neutral (Data value)", unit: "A", registerType: "read", address: 23574, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "maximum_voltage_l1_data_value", label: "Maximum voltage L1 (Data value)", unit: "V", registerType: "read", address: 23576, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "maximum_voltage_l2_data_value", label: "Maximum voltage L2 (Data value)", unit: "V", registerType: "read", address: 23578, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "maximum_voltage_l3_data_value", label: "Maximum voltage L3 (Data value)", unit: "V", registerType: "read", address: 23580, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "maximum_voltage_l1_l2_data_value", label: "Maximum voltage L1-L2 (Data value)", unit: "V", registerType: "read", address: 23582, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "maximum_voltage_l2_l3_data_value", label: "Maximum voltage L2-L3 (Data value)", unit: "V", registerType: "read", address: 23584, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "maximum_voltage_l1_l3_data_value", label: "Maximum voltage L1-L3 (Data value)", unit: "V", registerType: "read", address: 23586, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "maximum_active_power_total_data_value", label: "Maximum active power total (Data value)", unit: "W", registerType: "read", address: 23588, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "maximum_active_power_l1_data_value", label: "Maximum active power L1 (Data value)", unit: "W", registerType: "read", address: 23590, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "maximum_active_power_l2_data_value", label: "Maximum active power L2 (Data value)", unit: "W", registerType: "read", address: 23592, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "maximum_active_power_l3_data_value", label: "Maximum active power L3 (Data value)", unit: "W", registerType: "read", address: 23594, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "maximum_reactive_power_total_data_value", label: "Maximum reactive power total (Data value)", unit: "var", registerType: "read", address: 23596, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "maximum_reactive_power_l1_data_value", label: "Maximum reactive power L1 (Data value)", unit: "var", registerType: "read", address: 23598, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "maximum_reactive_power_l2_data_value", label: "Maximum reactive power L2 (Data value)", unit: "var", registerType: "read", address: 23600, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "maximum_reactive_power_l3_data_value", label: "Maximum reactive power L3 (Data value)", unit: "var", registerType: "read", address: 23602, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "maximum_apparent_power_total_data_value", label: "Maximum apparent power total (Data value)", unit: "VA", registerType: "read", address: 23604, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "maximum_apparent_power_l1_data_value", label: "Maximum apparent power L1 (Data value)", unit: "VA", registerType: "read", address: 23606, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "maximum_apparent_power_l2_data_value", label: "Maximum apparent power L2 (Data value)", unit: "VA", registerType: "read", address: 23608, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "maximum_apparent_power_l3_data_value", label: "Maximum apparent power L3 (Data value)", unit: "VA", registerType: "read", address: 23610, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "maximum_current_l1_timestamp_timestamp", label: "Maximum current L1 timestamp (Timestamp)", registerType: "read", address: 23628, valueKind: "S_DWORD" },
  { paramKey: "maximum_current_l2_timestamp_timestamp", label: "Maximum current L2 timestamp (Timestamp)", registerType: "read", address: 23630, valueKind: "S_DWORD" },
  { paramKey: "maximum_current_l3_timestamp_timestamp", label: "Maximum current L3 timestamp (Timestamp)", registerType: "read", address: 23632, valueKind: "S_DWORD" },
  { paramKey: "maximum_current_neutral_timestamp_timestamp", label: "Maximum current neutral timestamp (Timestamp)", registerType: "read", address: 23634, valueKind: "S_DWORD" },
  { paramKey: "maximum_voltage_l1_timestamp_timestamp", label: "Maximum voltage L1 timestamp (Timestamp)", registerType: "read", address: 23636, valueKind: "S_DWORD" },
  { paramKey: "maximum_voltage_l2_timestamp_timestamp", label: "Maximum voltage L2 timestamp (Timestamp)", registerType: "read", address: 23638, valueKind: "S_DWORD" },
  { paramKey: "maximum_voltage_l3_timestamp_timestamp", label: "Maximum voltage L3 timestamp (Timestamp)", registerType: "read", address: 23640, valueKind: "S_DWORD" },
  { paramKey: "maximum_voltage_l1_l2_timestamp_timestamp", label: "Maximum voltage L1-L2 timestamp (Timestamp)", registerType: "read", address: 23642, valueKind: "S_DWORD" },
  { paramKey: "maximum_voltage_l2_l3_timestamp_timestamp", label: "Maximum voltage L2-L3 timestamp (Timestamp)", registerType: "read", address: 23644, valueKind: "S_DWORD" },
  { paramKey: "maximum_voltage_l1_l3_timestamp_timestamp", label: "Maximum voltage L1-L3 timestamp (Timestamp)", registerType: "read", address: 23646, valueKind: "S_DWORD" },
  { paramKey: "maximum_active_power_total_timestamp_timestamp", label: "Maximum active power total timestamp (Timestamp)", registerType: "read", address: 23648, valueKind: "S_DWORD" },
  { paramKey: "maximum_active_power_l1_timestamp_timestamp", label: "Maximum active power L1 timestamp (Timestamp)", registerType: "read", address: 23650, valueKind: "S_DWORD" },
  { paramKey: "maximum_active_power_l2_timestamp_timestamp", label: "Maximum active power L2 timestamp (Timestamp)", registerType: "read", address: 23652, valueKind: "S_DWORD" },
  { paramKey: "maximum_active_power_l3_timestamp_timestamp", label: "Maximum active power L3 timestamp (Timestamp)", registerType: "read", address: 23654, valueKind: "S_DWORD" },
  { paramKey: "maximum_reactive_power_total_timestamp_timestamp", label: "Maximum reactive power total timestamp (Timestamp)", registerType: "read", address: 23656, valueKind: "S_DWORD" },
  { paramKey: "maximum_reactive_power_l1_timestamp_timestamp", label: "Maximum reactive power L1 timestamp (Timestamp)", registerType: "read", address: 23658, valueKind: "S_DWORD" },
  { paramKey: "maximum_reactive_power_l2_timestamp_timestamp", label: "Maximum reactive power L2 timestamp (Timestamp)", registerType: "read", address: 23660, valueKind: "S_DWORD" },
  { paramKey: "maximum_reactive_power_l3_timestamp_timestamp", label: "Maximum reactive power L3 timestamp (Timestamp)", registerType: "read", address: 23662, valueKind: "S_DWORD" },
  { paramKey: "maximum_apparent_power_total_timestamp_timestamp", label: "Maximum apparent power total timestamp (Timestamp)", registerType: "read", address: 23664, valueKind: "S_DWORD" },
  { paramKey: "maximum_apparent_power_l1_timestamp_timestamp", label: "Maximum apparent power L1 timestamp (Timestamp)", registerType: "read", address: 23666, valueKind: "S_DWORD" },
  { paramKey: "maximum_apparent_power_l2_timestamp_timestamp", label: "Maximum apparent power L2 timestamp (Timestamp)", registerType: "read", address: 23668, valueKind: "S_DWORD" },
  { paramKey: "maximum_apparent_power_l3_timestamp_timestamp", label: "Maximum apparent power L3 timestamp (Timestamp)", registerType: "read", address: 23670, valueKind: "S_DWORD" },
  { paramKey: "minimum_current_l1_data_value", label: "Minimum current L1 (Data value)", unit: "A", registerType: "read", address: 23688, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "minimum_current_l2_data_value", label: "Minimum current L2 (Data value)", unit: "A", registerType: "read", address: 23690, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "minimum_current_l3_data_value", label: "Minimum current L3 (Data value)", unit: "A", registerType: "read", address: 23692, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "minimum_current_neutral_data_value", label: "Minimum current neutral (Data value)", unit: "A", registerType: "read", address: 23694, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "minimum_voltage_l1_data_value", label: "Minimum voltage L1 (Data value)", unit: "V", registerType: "read", address: 23696, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "minimum_voltage_l2_data_value", label: "Minimum voltage L2 (Data value)", unit: "V", registerType: "read", address: 23698, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "minimum_voltage_l3_data_value", label: "Minimum voltage L3 (Data value)", unit: "V", registerType: "read", address: 23700, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "minimum_voltage_l1_l2_data_value", label: "Minimum voltage L1-L2 (Data value)", unit: "V", registerType: "read", address: 23702, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "minimum_voltage_l2_l3_data_value", label: "Minimum voltage L2-L3 (Data value)", unit: "V", registerType: "read", address: 23704, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "minimum_voltage_l1_l3_data_value", label: "Minimum voltage L1-L3 (Data value)", unit: "V", registerType: "read", address: 23706, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "minimum_active_power_total_data_value", label: "Minimum active power total (Data value)", unit: "W", registerType: "read", address: 23708, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "minimum_active_power_l1_data_value", label: "Minimum active power L1 (Data value)", unit: "W", registerType: "read", address: 23710, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "minimum_active_power_l2_data_value", label: "Minimum active power L2 (Data value)", unit: "W", registerType: "read", address: 23712, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "minimum_active_power_l3_data_value", label: "Minimum active power L3 (Data value)", unit: "W", registerType: "read", address: 23714, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "minimum_reactive_power_total_data_value", label: "Minimum reactive power total (Data value)", unit: "var", registerType: "read", address: 23716, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "minimum_reactive_power_l1_data_value", label: "Minimum reactive power L1 (Data value)", unit: "var", registerType: "read", address: 23718, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "minimum_reactive_power_l2_data_value", label: "Minimum reactive power L2 (Data value)", unit: "var", registerType: "read", address: 23720, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "minimum_reactive_power_l3_data_value", label: "Minimum reactive power L3 (Data value)", unit: "var", registerType: "read", address: 23722, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "minimum_apparent_power_total_data_value", label: "Minimum apparent power total (Data value)", unit: "VA", registerType: "read", address: 23724, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "minimum_apparent_power_l1_data_value", label: "Minimum apparent power L1 (Data value)", unit: "VA", registerType: "read", address: 23726, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "minimum_apparent_power_l2_data_value", label: "Minimum apparent power L2 (Data value)", unit: "VA", registerType: "read", address: 23728, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "minimum_apparent_power_l3_data_value", label: "Minimum apparent power L3 (Data value)", unit: "VA", registerType: "read", address: 23730, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "minimum_current_l1_timestamp_timestamp", label: "Minimum current L1 timestamp (Timestamp)", registerType: "read", address: 23748, valueKind: "S_DWORD" },
  { paramKey: "minimum_current_l2_timestamp_timestamp", label: "Minimum current L2 timestamp (Timestamp)", registerType: "read", address: 23750, valueKind: "S_DWORD" },
  { paramKey: "minimum_current_l3_timestamp_timestamp", label: "Minimum current L3 timestamp (Timestamp)", registerType: "read", address: 23752, valueKind: "S_DWORD" },
  { paramKey: "minimum_current_neutral_timestamp_timestamp", label: "Minimum current neutral timestamp (Timestamp)", registerType: "read", address: 23754, valueKind: "S_DWORD" },
  { paramKey: "minimum_voltage_l1_timestamp_timestamp", label: "Minimum voltage L1 timestamp (Timestamp)", registerType: "read", address: 23756, valueKind: "S_DWORD" },
  { paramKey: "minimum_voltage_l2_timestamp_timestamp", label: "Minimum voltage L2 timestamp (Timestamp)", registerType: "read", address: 23758, valueKind: "S_DWORD" },
  { paramKey: "minimum_voltage_l3_timestamp_timestamp", label: "Minimum voltage L3 timestamp (Timestamp)", registerType: "read", address: 23760, valueKind: "S_DWORD" },
  { paramKey: "minimum_voltage_l1_l2_timestamp_timestamp", label: "Minimum voltage L1-L2 timestamp (Timestamp)", registerType: "read", address: 23762, valueKind: "S_DWORD" },
  { paramKey: "minimum_voltage_l2_l3_timestamp_timestamp", label: "Minimum voltage L2-L3 timestamp (Timestamp)", registerType: "read", address: 23764, valueKind: "S_DWORD" },
  { paramKey: "minimum_voltage_l1_l3_timestamp_timestamp", label: "Minimum voltage L1-L3 timestamp (Timestamp)", registerType: "read", address: 23766, valueKind: "S_DWORD" },
  { paramKey: "minimum_active_power_total_timestamp_timestamp", label: "Minimum active power total timestamp (Timestamp)", registerType: "read", address: 23768, valueKind: "S_DWORD" },
  { paramKey: "minimum_active_power_l1_timestamp_timestamp", label: "Minimum active power L1 timestamp (Timestamp)", registerType: "read", address: 23770, valueKind: "S_DWORD" },
  { paramKey: "minimum_active_power_l2_timestamp_timestamp", label: "Minimum active power L2 timestamp (Timestamp)", registerType: "read", address: 23772, valueKind: "S_DWORD" },
  { paramKey: "minimum_active_power_l3_timestamp_timestamp", label: "Minimum active power L3 timestamp (Timestamp)", registerType: "read", address: 23774, valueKind: "S_DWORD" },
  { paramKey: "minimum_reactive_power_total_timestamp_timestamp", label: "Minimum reactive power total timestamp (Timestamp)", registerType: "read", address: 23776, valueKind: "S_DWORD" },
  { paramKey: "minimum_reactive_power_l1_timestamp_timestamp", label: "Minimum reactive power L1 timestamp (Timestamp)", registerType: "read", address: 23778, valueKind: "S_DWORD" },
  { paramKey: "minimum_reactive_power_l2_timestamp_timestamp", label: "Minimum reactive power L2 timestamp (Timestamp)", registerType: "read", address: 23780, valueKind: "S_DWORD" },
  { paramKey: "minimum_reactive_power_l3_timestamp_timestamp", label: "Minimum reactive power L3 timestamp (Timestamp)", registerType: "read", address: 23782, valueKind: "S_DWORD" },
  { paramKey: "minimum_apparent_power_total_timestamp_timestamp", label: "Minimum apparent power total timestamp (Timestamp)", registerType: "read", address: 23784, valueKind: "S_DWORD" },
  { paramKey: "minimum_apparent_power_l1_timestamp_timestamp", label: "Minimum apparent power L1 timestamp (Timestamp)", registerType: "read", address: 23786, valueKind: "S_DWORD" },
  { paramKey: "minimum_apparent_power_l2_timestamp_timestamp", label: "Minimum apparent power L2 timestamp (Timestamp)", registerType: "read", address: 23788, valueKind: "S_DWORD" },
  { paramKey: "minimum_apparent_power_l3_timestamp_timestamp", label: "Minimum apparent power L3 timestamp (Timestamp)", registerType: "read", address: 23790, valueKind: "S_DWORD" },
  { paramKey: "voltage_thd_harmonics_l1_thd", label: "Voltage THD harmonics (L1 (THD))", unit: "%", registerType: "read", address: 23808, valueKind: "S_WORD", scale: 0.1, precision: 1 },
  { paramKey: "current_harmonics_l1_thd", label: "Current harmonics (L1 (THD))", unit: "%", registerType: "read", address: 24576, valueKind: "S_WORD", scale: 0.1, precision: 1 },
  { paramKey: "unbalances_line_voltage", label: "Unbalances (Line voltage)", unit: "%", registerType: "read", address: 25088, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "outputs_output_1", label: "Outputs (Output 1)", unit: "0: OFF, 1: ON", registerType: "read", address: 25344, valueKind: "U_WORD" },
  { paramKey: "inputs_input_1", label: "Inputs (Input 1)", unit: "0: OFF, 1: ON", registerType: "read", address: 25352, valueKind: "U_WORD" },
  { paramKey: "inputs_counter_input_counter_1", label: "Inputs Counter (Input Counter 1)", registerType: "read", address: 25368, valueKind: "U_QWORD" },
  { paramKey: "errors_log_header_get_next_entry", label: "Errors Log (Header - Get next entry)", registerType: "read", address: 25856, valueKind: "S_WORD" },
  { paramKey: "alarms_log_header_get_next_entry", label: "Alarms log (Header - Get next entry)", registerType: "read", address: 26032, valueKind: "S_WORD" },
  { paramKey: "audit_log_header_get_next_entry", label: "Audit Log (Header - Get next entry)", registerType: "read", address: 26208, valueKind: "S_WORD" },
  { paramKey: "warnings_log_header_get_next_entry", label: "Warnings log (Header - Get next entry)", registerType: "read", address: 26384, valueKind: "S_WORD" },
  { paramKey: "power_outage_log_header_get_next_entry", label: "Power Outage Log (Header - Get next entry)", registerType: "read", address: 26560, valueKind: "S_WORD" },
  { paramKey: "energy_cumulative_header_get_next_entry", label: "Energy Cumulative (Header - Get next entry)", registerType: "read", address: 32768, valueKind: "U_WORD" },
  { paramKey: "energy_snapshots_header_get_next_entry", label: "Energy Snapshots (Header - Get next entry)", registerType: "read", address: 33536, valueKind: "U_WORD" },
  { paramKey: "load_profile_header_get_next_block", label: "Load profile (Header - Get next block)", registerType: "read", address: 34560, valueKind: "U_WORD" },
  { paramKey: "serial_number_s", label: "Serial number(s)", registerType: "read", address: 35072, valueKind: "U_WORD" },
  { paramKey: "meter_firmware_version", label: "Meter firmware version", registerType: "read", address: 35080, valueKind: "U_WORD" },
  { paramKey: "product_type_number_id_see_details_sheet", label: "Product type number ID (See Details sheet)", registerType: "read", address: 35088, valueKind: "U_WORD" },
  { paramKey: "slave_id", label: "Slave ID", registerType: "read", address: 35089, valueKind: "U_WORD" },
  { paramKey: "product_tag_name", label: "Product tag name", registerType: "read", address: 35097, valueKind: "U_WORD" },
  { paramKey: "type_designation_e_g_m4m30sma", label: "Type designation (E.g. M4M30SMA)", registerType: "read", address: 35168, valueKind: "U_WORD" },
  { paramKey: "product_name_e_g_m4m_30_modbus", label: "Product Name (E.g. M4M 30 MODBUS)", registerType: "read", address: 35174, valueKind: "U_WORD" },
  { paramKey: "date_time_yymmdd_hhmmss", label: "Date Time (YYMMDD:HHMMSS)", registerType: "read", address: 35328, valueKind: "U_WORD" },
  { paramKey: "day_of_week", label: "Day of week", registerType: "read", address: 35331, valueKind: "U_DWORD" },
  { paramKey: "active_day_type_read_only", label: "Active day type (Read only)", registerType: "read", address: 35333, valueKind: "U_WORD" },
  { paramKey: "active_season_read_only", label: "Active season (Read only)", registerType: "read", address: 35334, valueKind: "U_WORD" },
  { paramKey: "current_tariff_current_active_tariff_form_1_to_6", label: "Current tariff (Current active tariff (form 1 to 6))", registerType: "read", address: 35335, valueKind: "S_WORD" },
  { paramKey: "error_flags_64_bits_flags", label: "Error flags (64 bits flags)", registerType: "read", address: 35347, valueKind: "U_QWORD" },
  { paramKey: "information_flags_64_bits_flags", label: "Information flags (64 bits flags)", unit: "25 Alarm flags", registerType: "read", address: 35353, valueKind: "U_QWORD" },
  { paramKey: "warning_flags_64_bits_flags", label: "Warning flags (64 bits flags)", registerType: "read", address: 35359, valueKind: "U_QWORD" },
  { paramKey: "alarm_flags_simple_and_complex_64_bits_flags_25_alarm_flags_", label: "Alarm flags (simple and complex) (64 bits flags (25 Alarm flags used))", registerType: "read", address: 35365, valueKind: "U_QWORD" },
  { paramKey: "transformer_ratios_ct_l1_l2_l3_ratio_numerator", label: "Transformer ratios (CT L1,L2,L3 ratio (Numerator))", registerType: "read", address: 35840, valueKind: "S_DWORD" },
  { paramKey: "i_o_settings_function_i_o_port_1", label: "I/O settings - Function (I/O port 1)", registerType: "read", address: 35852, valueKind: "U_WORD" },
  { paramKey: "i_o_settings_pulse_input_output_instance_pulse_input_output_", label: "I/O settings - Pulse input/output instance (Pulse input/output instance)", registerType: "read", address: 35858, valueKind: "U_WORD" },
  { paramKey: "i_o_settings_pulse_outputs_configuration_port_number", label: "I/O settings - Pulse outputs configuration (Port number)", registerType: "read", address: 35859, valueKind: "U_WORD" },
  { paramKey: "load_profile_settings_channel_number", label: "Load profile settings (Channel number)", registerType: "read", address: 35872, valueKind: "U_WORD" },
  { paramKey: "max_min_demand_settings_number_of_quantities", label: "Max/Min Demand settings (Number of quantities)", registerType: "read", address: 35888, valueKind: "U_WORD" },
  { paramKey: "energy_cumulative_snapshots_settings_number_of_channel", label: "Energy Cumulative/Snapshots settings (Number of channel)", registerType: "read", address: 35920, valueKind: "U_WORD" },
  { paramKey: "alarm_settings_channel_alarm_number", label: "Alarm settings (Channel alarm number)", registerType: "read", address: 35936, valueKind: "U_WORD" },
  { paramKey: "complex_alarms_channel_complex_alarm_number", label: "Complex Alarms (Channel complex alarm number)", registerType: "read", address: 35968, valueKind: "U_WORD" },
  { paramKey: "tariff_settings_tariffs_source", label: "Tariff settings (Tariffs source)", registerType: "read", address: 35984, valueKind: "U_WORD" },
  { paramKey: "co2_conversion_factor_actiive_energy_range_0_001_9_999", label: "CO2 conversion factor actIive energy (Range: 0.001 - 9.999)", unit: "kg / kWh", registerType: "read", address: 36064, valueKind: "S_DWORD", scale: 0.001, precision: 3 },
  { paramKey: "currency_conversion_factor_active_enenrgy_range_0_001_999999", label: "Currency conversion factor active enenrgy (Range: 0.001 - 999999.000)", unit: "Currency / kWh", registerType: "read", address: 36066, valueKind: "S_DWORD", scale: 0.001, precision: 3 },
  { paramKey: "led_source_0_active_energy_1_reactive_energy", label: "LED source (0 = Active energy, 1 = Reactive energy)", registerType: "read", address: 36068, valueKind: "U_WORD" },
  { paramKey: "wires_see_details_sheet", label: "Wires (See Details sheet)", registerType: "read", address: 36069, valueKind: "S_WORD" },
  { paramKey: "dst_start_month_day_of_month_day_of_week_hour", label: "DST start (month, day of month, day of week, hour)", registerType: "read", address: 36070, valueKind: "U_DWORD" },
  { paramKey: "dst_end_month_day_of_month_day_of_week_hour", label: "DST end (month, day of month, day of week, hour)", registerType: "read", address: 36072, valueKind: "U_DWORD" },
  { paramKey: "dst_enabled_0_disabled_1_enabled", label: "DST enabled (0 = disabled, 1 = enabled)", registerType: "read", address: 36074, valueKind: "U_WORD" },
  { paramKey: "modbus_rtu_address_1_247", label: "Modbus RTU (Address: 1 - 247)", registerType: "read", address: 36075, valueKind: "S_WORD" },
  { paramKey: "modbus_tcp_ip_dhcp_0_disable_1_enable", label: "Modbus TCP/IP (DHCP: 0-disable; 1- enable)", registerType: "read", address: 36079, valueKind: "S_WORD" },
  { paramKey: "up_down_counters_up_counter", label: "Up/Down Counters (Up Counter)", registerType: "read", address: 36087, valueKind: "S_DWORD" },
  { paramKey: "hmi_config_brightness_range_0_255", label: "HMI Config (Brightness (range: 0 - 255))", registerType: "read", address: 36093, valueKind: "S_WORD" },
  { paramKey: "bluetooth_enable", label: "Bluetooth Enable", registerType: "read", address: 36604, valueKind: "S_WORD" },
  { paramKey: "i_o_settings_pulse_input_ratio_scaler_of_pulse_input_counter", label: "I/O settings - Pulse input ratio (Scaler of pulse input counter)", registerType: "read", address: 36624, valueKind: "S_WORD" },
  { paramKey: "i_o_settings_pulse_input_unit_unit_visible_on_hmi_see_manual", label: "I/O settings - Pulse input unit (Unit visible on HMI. See manual for the list of available values.)", registerType: "read", address: 36626, valueKind: "S_WORD" },
  { paramKey: "reset_logs_write_1_to_perform_the_reset", label: "Reset Logs (Write 1 to perform the reset)", registerType: "read", address: 36695, valueKind: "S_WORD" },
  { paramKey: "reset_historical_functionality_write_1_to_perform_the_reset", label: "Reset historical functionality (Write 1 to perform the reset)", registerType: "read", address: 36696, valueKind: "S_WORD" },
  { paramKey: "reset_timer_write_1_to_perform_the_reset", label: "Reset Timer (Write 1 to perform the reset)", registerType: "read", address: 36697, valueKind: "S_WORD" },
  { paramKey: "reset_energy_write_1_to_perform_the_reset", label: "Reset Energy (Write 1 to perform the reset)", registerType: "read", address: 36698, valueKind: "S_WORD" },
  { paramKey: "reset_factory_setting_default_write_1_to_perform_the_reset", label: "Reset Factory setting default (Write 1 to perform the reset)", registerType: "read", address: 36699, valueKind: "S_WORD" },
  { paramKey: "reset_max_min_average_write_1_to_perform_the_reset", label: "Reset Max / Min / Average (Write 1 to perform the reset)", registerType: "read", address: 36700, valueKind: "S_WORD" },
  { paramKey: "max_min_demand_header_get_next_entry", label: "Max/Min Demand (Header - Get next entry)", registerType: "read", address: 36722, valueKind: "U_WORD" },
  { paramKey: "active_power_total_scaler_1_data_value_available_from_fw_ver", label: "Active power total Scaler 1 (Data value - available from FW version P1.3.10.0)", unit: "W", registerType: "read", address: 51994, valueKind: "S_DWORD", scale: 1.0, precision: 0 },
  { paramKey: "active_power_l1_scaler_1_data_value_available_from_fw_versio", label: "Active power L1 Scaler 1 (Data value - available from FW version P1.3.10.0)", unit: "W", registerType: "read", address: 51996, valueKind: "S_DWORD", scale: 1.0, precision: 0 },
  { paramKey: "active_power_l2_scaler_1_data_value_available_from_fw_versio", label: "Active power L2 Scaler 1 (Data value - available from FW version P1.3.10.0)", unit: "W", registerType: "read", address: 51998, valueKind: "S_DWORD", scale: 1.0, precision: 0 },
  { paramKey: "active_power_l3_scaler_1_data_value_available_from_fw_versio", label: "Active power L3 Scaler 1 (Data value - available from FW version P1.3.10.0)", unit: "W", registerType: "read", address: 52000, valueKind: "S_DWORD", scale: 1.0, precision: 0 },
  { paramKey: "reactive_power_total_scaler_1_data_value_available_from_fw_v", label: "Reactive power total Scaler 1 (Data value - available from FW version P1.3.10.0)", unit: "VAR", registerType: "read", address: 52002, valueKind: "S_DWORD", scale: 1.0, precision: 0 },
  { paramKey: "reactive_power_l1_scaler_1_data_value_available_from_fw_vers", label: "Reactive power L1 Scaler 1 (Data value - available from FW version P1.3.10.0)", unit: "VAR", registerType: "read", address: 52004, valueKind: "S_DWORD", scale: 1.0, precision: 0 },
  { paramKey: "reactive_power_l2_scaler_1_data_value_available_from_fw_vers", label: "Reactive power L2 Scaler 1 (Data value - available from FW version P1.3.10.0)", unit: "VAR", registerType: "read", address: 52006, valueKind: "S_DWORD", scale: 1.0, precision: 0 },
  { paramKey: "reactive_power_l3_scaler_1_data_value_available_from_fw_vers", label: "Reactive power L3 Scaler 1 (Data value - available from FW version P1.3.10.0)", unit: "VAR", registerType: "read", address: 52008, valueKind: "S_DWORD", scale: 1.0, precision: 0 },
  { paramKey: "apparent_power_total_scaler_1_data_value_available_from_fw_v", label: "Apparent power total Scaler 1 (Data value - available from FW version P1.3.10.0)", unit: "VA", registerType: "read", address: 52010, valueKind: "S_DWORD", scale: 1.0, precision: 0 },
  { paramKey: "apparent_power_l1_scaler_1_data_value_available_from_fw_vers", label: "Apparent power L1 Scaler 1 (Data value - available from FW version P1.3.10.0)", unit: "VA", registerType: "read", address: 52012, valueKind: "S_DWORD", scale: 1.0, precision: 0 },
  { paramKey: "apparent_power_l2_scaler_1_data_value_available_from_fw_vers", label: "Apparent power L2 Scaler 1 (Data value - available from FW version P1.3.10.0)", unit: "VA", registerType: "read", address: 52014, valueKind: "S_DWORD", scale: 1.0, precision: 0 },
  { paramKey: "apparent_power_l3_scaler_1_data_value_available_from_fw_vers", label: "Apparent power L3 Scaler 1 (Data value - available from FW version P1.3.10.0)", unit: "VA", registerType: "read", address: 52016, valueKind: "S_DWORD", scale: 1.0, precision: 0 },
  { paramKey: "average_active_power_total_scaler_1_data_value_available_fro", label: "Average Active power total Scaler 1 (Data value - available from FW version P1.3.10.0)", unit: "W", registerType: "read", address: 52200, valueKind: "S_DWORD", scale: 1.0, precision: 0 },
  { paramKey: "average_active_power_l1_scaler_1_data_value_available_from_f", label: "Average Active power L1 Scaler 1 (Data value - available from FW version P1.3.10.0)", unit: "W", registerType: "read", address: 52202, valueKind: "S_DWORD", scale: 1.0, precision: 0 },
  { paramKey: "average_active_power_l2_scaler_1_data_value_available_from_f", label: "Average Active power L2 Scaler 1 (Data value - available from FW version P1.3.10.0)", unit: "W", registerType: "read", address: 52204, valueKind: "S_DWORD", scale: 1.0, precision: 0 },
  { paramKey: "average_active_power_l3_scaler_1_data_value_available_from_f", label: "Average Active power L3 Scaler 1 (Data value - available from FW version P1.3.10.0)", unit: "W", registerType: "read", address: 52206, valueKind: "S_DWORD", scale: 1.0, precision: 0 },
  { paramKey: "average_reactive_power_total_scaler_1_data_value_available_f", label: "Average Reactive power total Scaler 1 (Data value - available from FW version P1.3.10.0)", unit: "VAR", registerType: "read", address: 52208, valueKind: "S_DWORD", scale: 1.0, precision: 0 },
  { paramKey: "average_reactive_power_l1_scaler_1_data_value_available_from", label: "Average Reactive power L1 Scaler 1 (Data value - available from FW version P1.3.10.0)", unit: "VAR", registerType: "read", address: 52210, valueKind: "S_DWORD", scale: 1.0, precision: 0 },
  { paramKey: "average_reactive_power_l2_scaler_1_data_value_available_from", label: "Average Reactive power L2 Scaler 1 (Data value - available from FW version P1.3.10.0)", unit: "VAR", registerType: "read", address: 52212, valueKind: "S_DWORD", scale: 1.0, precision: 0 },
  { paramKey: "average_reactive_power_l3_scaler_1_data_value_available_from", label: "Average Reactive power L3 Scaler 1 (Data value - available from FW version P1.3.10.0)", unit: "VAR", registerType: "read", address: 52214, valueKind: "S_DWORD", scale: 1.0, precision: 0 },
  { paramKey: "average_apparent_power_total_scaler_1_data_value_available_f", label: "Average Apparent power total Scaler 1 (Data value - available from FW version P1.3.10.0)", unit: "VA", registerType: "read", address: 52216, valueKind: "S_DWORD", scale: 1.0, precision: 0 },
  { paramKey: "average_apparent_power_l1_scaler_1_data_value_available_from", label: "Average Apparent power L1 Scaler 1 (Data value - available from FW version P1.3.10.0)", unit: "VA", registerType: "read", address: 52218, valueKind: "S_DWORD", scale: 1.0, precision: 0 },
  { paramKey: "average_apparent_power_l2_scaler_1_data_value_available_from", label: "Average Apparent power L2 Scaler 1 (Data value - available from FW version P1.3.10.0)", unit: "VA", registerType: "read", address: 52220, valueKind: "S_DWORD", scale: 1.0, precision: 0 },
  { paramKey: "average_apparent_power_l3_scaler_1_data_value_available_from", label: "Average Apparent power L3 Scaler 1 (Data value - available from FW version P1.3.10.0)", unit: "VA", registerType: "read", address: 52222, valueKind: "S_DWORD", scale: 1.0, precision: 0 },
  { paramKey: "max_active_power_total_scaler_1_data_value_available_from_fw", label: "Max Active power total Scaler 1 (Data value - available from FW version P1.3.10.0)", unit: "W", registerType: "read", address: 52260, valueKind: "S_DWORD", scale: 1.0, precision: 0 },
  { paramKey: "max_active_power_l1_scaler_1_data_value_available_from_fw_ve", label: "Max Active power L1 Scaler 1 (Data value - available from FW version P1.3.10.0)", unit: "W", registerType: "read", address: 52262, valueKind: "S_DWORD", scale: 1.0, precision: 0 },
  { paramKey: "max_active_power_l2_scaler_1_data_value_available_from_fw_ve", label: "Max Active power L2 Scaler 1 (Data value - available from FW version P1.3.10.0)", unit: "W", registerType: "read", address: 52264, valueKind: "S_DWORD", scale: 1.0, precision: 0 },
  { paramKey: "max_active_power_l3_scaler_1_data_value_available_from_fw_ve", label: "Max Active power L3 Scaler 1 (Data value - available from FW version P1.3.10.0)", unit: "W", registerType: "read", address: 52266, valueKind: "S_DWORD", scale: 1.0, precision: 0 },
  { paramKey: "max_reactive_power_total_scaler_1_data_value_available_from_", label: "Max Reactive power total Scaler 1 (Data value - available from FW version P1.3.10.0)", unit: "VAR", registerType: "read", address: 52268, valueKind: "S_DWORD", scale: 1.0, precision: 0 },
  { paramKey: "max_reactive_power_l1_scaler_1_data_value_available_from_fw_", label: "Max Reactive power L1 Scaler 1 (Data value - available from FW version P1.3.10.0)", unit: "VAR", registerType: "read", address: 52270, valueKind: "S_DWORD", scale: 1.0, precision: 0 },
  { paramKey: "max_reactive_power_l2_scaler_1_data_value_available_from_fw_", label: "Max Reactive power L2 Scaler 1 (Data value - available from FW version P1.3.10.0)", unit: "VAR", registerType: "read", address: 52272, valueKind: "S_DWORD", scale: 1.0, precision: 0 },
  { paramKey: "max_reactive_power_l3_scaler_1_data_value_available_from_fw_", label: "Max Reactive power L3 Scaler 1 (Data value - available from FW version P1.3.10.0)", unit: "VAR", registerType: "read", address: 52274, valueKind: "S_DWORD", scale: 1.0, precision: 0 },
  { paramKey: "max_apparent_power_total_scaler_1_data_value_available_from_", label: "Max Apparent power total Scaler 1 (Data value - available from FW version P1.3.10.0)", unit: "VA", registerType: "read", address: 52276, valueKind: "S_DWORD", scale: 1.0, precision: 0 },
  { paramKey: "max_apparent_power_l1_scaler_1_data_value_available_from_fw_", label: "Max Apparent power L1 Scaler 1 (Data value - available from FW version P1.3.10.0)", unit: "VA", registerType: "read", address: 52278, valueKind: "S_DWORD", scale: 1.0, precision: 0 },
  { paramKey: "max_apparent_power_l2_scaler_1_data_value_available_from_fw_", label: "Max Apparent power L2 Scaler 1 (Data value - available from FW version P1.3.10.0)", unit: "VA", registerType: "read", address: 52280, valueKind: "S_DWORD", scale: 1.0, precision: 0 },
  { paramKey: "max_apparent_power_l3_scaler_1_data_value_available_from_fw_", label: "Max Apparent power L3 Scaler 1 (Data value - available from FW version P1.3.10.0)", unit: "VA", registerType: "read", address: 52282, valueKind: "S_DWORD", scale: 1.0, precision: 0 },
  { paramKey: "min_active_power_total_scaler_1_data_value_available_from_fw", label: "Min Active power total Scaler 1 (Data value - available from FW version P1.3.10.0)", unit: "W", registerType: "read", address: 52380, valueKind: "S_DWORD", scale: 1.0, precision: 0 },
  { paramKey: "min_active_power_l1_scaler_1_data_value_available_from_fw_ve", label: "Min Active power L1 Scaler 1 (Data value - available from FW version P1.3.10.0)", unit: "W", registerType: "read", address: 52382, valueKind: "S_DWORD", scale: 1.0, precision: 0 },
  { paramKey: "min_active_power_l2_scaler_1_data_value_available_from_fw_ve", label: "Min Active power L2 Scaler 1 (Data value - available from FW version P1.3.10.0)", unit: "W", registerType: "read", address: 52384, valueKind: "S_DWORD", scale: 1.0, precision: 0 },
  { paramKey: "min_active_power_l3_scaler_1_data_value_available_from_fw_ve", label: "Min Active power L3 Scaler 1 (Data value - available from FW version P1.3.10.0)", unit: "W", registerType: "read", address: 52386, valueKind: "S_DWORD", scale: 1.0, precision: 0 },
  { paramKey: "min_reactive_power_total_scaler_1_data_value_available_from_", label: "Min Reactive power total Scaler 1 (Data value - available from FW version P1.3.10.0)", unit: "VAR", registerType: "read", address: 52388, valueKind: "S_DWORD", scale: 1.0, precision: 0 },
  { paramKey: "min_reactive_power_l1_scaler_1_data_value_available_from_fw_", label: "Min Reactive power L1 Scaler 1 (Data value - available from FW version P1.3.10.0)", unit: "VAR", registerType: "read", address: 52390, valueKind: "S_DWORD", scale: 1.0, precision: 0 },
  { paramKey: "min_reactive_power_l2_scaler_1_data_value_available_from_fw_", label: "Min Reactive power L2 Scaler 1 (Data value - available from FW version P1.3.10.0)", unit: "VAR", registerType: "read", address: 52392, valueKind: "S_DWORD", scale: 1.0, precision: 0 },
  { paramKey: "min_reactive_power_l3_scaler_1_data_value_available_from_fw_", label: "Min Reactive power L3 Scaler 1 (Data value - available from FW version P1.3.10.0)", unit: "VAR", registerType: "read", address: 52394, valueKind: "S_DWORD", scale: 1.0, precision: 0 },
  { paramKey: "min_apparent_power_total_scaler_1_data_value_available_from_", label: "Min Apparent power total Scaler 1 (Data value - available from FW version P1.3.10.0)", unit: "VA", registerType: "read", address: 52396, valueKind: "S_DWORD", scale: 1.0, precision: 0 },
  { paramKey: "min_apparent_power_l1_scaler_1_data_value_available_from_fw_", label: "Min Apparent power L1 Scaler 1 (Data value - available from FW version P1.3.10.0)", unit: "VA", registerType: "read", address: 52398, valueKind: "S_DWORD", scale: 1.0, precision: 0 },
  { paramKey: "min_apparent_power_l2_scaler_1_data_value_available_from_fw_", label: "Min Apparent power L2 Scaler 1 (Data value - available from FW version P1.3.10.0)", unit: "VA", registerType: "read", address: 52400, valueKind: "S_DWORD", scale: 1.0, precision: 0 },
  { paramKey: "min_apparent_power_l3_scaler_1_data_value_available_from_fw_", label: "Min Apparent power L3 Scaler 1 (Data value - available from FW version P1.3.10.0)", unit: "VA", registerType: "read", address: 52402, valueKind: "S_DWORD", scale: 1.0, precision: 0 },
];
