import type { DriverRegister } from '../driverStore.js';

export const sofarCnRegisters: DriverRegister[] = [
  { paramKey: "addressmask_realtime_sysinfo1", label: "AddressMask_Realtime_SysInfo1", registerType: "holding", address: 1024, valueKind: "U_QWORD" },
  { paramKey: "sysstate", label: "SysState", registerType: "holding", address: 1028, valueKind: "U_WORD" },
  { paramKey: "fault1", label: "Fault1", registerType: "holding", address: 1029, valueKind: "U_WORD" },
  { paramKey: "fault2", label: "Fault2", registerType: "holding", address: 1030, valueKind: "U_WORD" },
  { paramKey: "fault3", label: "Fault3", registerType: "holding", address: 1031, valueKind: "U_WORD" },
  { paramKey: "fault4", label: "Fault4", registerType: "holding", address: 1032, valueKind: "U_WORD" },
  { paramKey: "fault5", label: "Fault5", registerType: "holding", address: 1033, valueKind: "U_WORD" },
  { paramKey: "fault6", label: "Fault6", registerType: "holding", address: 1034, valueKind: "U_WORD" },
  { paramKey: "fault7", label: "Fault7", registerType: "holding", address: 1035, valueKind: "U_WORD" },
  { paramKey: "fault8", label: "Fault8", registerType: "holding", address: 1036, valueKind: "U_WORD" },
  { paramKey: "fault9", label: "Fault9", registerType: "holding", address: 1037, valueKind: "U_WORD" },
  { paramKey: "fault10", label: "Fault10", registerType: "holding", address: 1038, valueKind: "U_WORD" },
  { paramKey: "fault11", label: "Fault11", registerType: "holding", address: 1039, valueKind: "U_WORD" },
  { paramKey: "fault12", label: "Fault12", registerType: "holding", address: 1040, valueKind: "U_WORD" },
  { paramKey: "fault13", label: "Fault13", registerType: "holding", address: 1041, valueKind: "U_WORD" },
  { paramKey: "fault14", label: "Fault14", registerType: "holding", address: 1042, valueKind: "U_WORD" },
  { paramKey: "fault15", label: "Fault15", registerType: "holding", address: 1043, valueKind: "U_WORD" },
  { paramKey: "fault16", label: "Fault16", registerType: "holding", address: 1044, valueKind: "U_WORD" },
  { paramKey: "fault17", label: "Fault17", registerType: "holding", address: 1045, valueKind: "U_WORD" },
  { paramKey: "fault18", label: "Fault18", registerType: "holding", address: 1046, valueKind: "U_WORD" },
  { paramKey: "countdown", label: "Countdown", unit: "\u79d2", registerType: "holding", address: 1047, valueKind: "U_WORD", precision: 1 },
  { paramKey: "temperature_env1", label: "Temperature_Env1", unit: "\u2103", registerType: "holding", address: 1048, valueKind: "U_WORD", precision: 1 },
  { paramKey: "temperature_env2", label: "Temperature_Env2", unit: "\u2103", registerType: "holding", address: 1049, valueKind: "U_WORD", precision: 1 },
  { paramKey: "temperature_heatsink1", label: "Temperature_HeatSink1", unit: "\u2103", registerType: "holding", address: 1050, valueKind: "U_WORD", precision: 1 },
  { paramKey: "temperature_heatsink2", label: "Temperature_HeatSink2", unit: "\u2103", registerType: "holding", address: 1051, valueKind: "U_WORD", precision: 1 },
  { paramKey: "temperature_heatsink3", label: "Temperature_HeatSink3", unit: "\u2103", registerType: "holding", address: 1052, valueKind: "U_WORD", precision: 1 },
  { paramKey: "temperature_heatsink4", label: "Temperature_HeatSink4", unit: "\u2103", registerType: "holding", address: 1053, valueKind: "U_WORD", precision: 1 },
  { paramKey: "temperature_heatsink5", label: "Temperature_HeatSink5", unit: "\u2103", registerType: "holding", address: 1054, valueKind: "U_WORD", precision: 1 },
  { paramKey: "temperature_heatsink6", label: "Temperature_HeatSink6", unit: "\u2103", registerType: "holding", address: 1055, valueKind: "U_WORD", precision: 1 },
  { paramKey: "temperature_inv1", label: "Temperature_Inv1", unit: "\u2103", registerType: "holding", address: 1056, valueKind: "U_WORD", precision: 1 },
  { paramKey: "temperature_inv2", label: "Temperature_Inv2", unit: "\u2103", registerType: "holding", address: 1057, valueKind: "U_WORD", precision: 1 },
  { paramKey: "temperature_inv3", label: "Temperature_Inv3", unit: "\u2103", registerType: "holding", address: 1058, valueKind: "U_WORD", precision: 1 },
  { paramKey: "temp_rsvd1", label: "Temp_Rsvd1", unit: "\u2103", registerType: "holding", address: 1059, valueKind: "U_WORD", precision: 1 },
  { paramKey: "temp_rsvd2", label: "Temp_Rsvd2", unit: "\u2103", registerType: "holding", address: 1060, valueKind: "U_WORD", precision: 1 },
  { paramKey: "temp_rsvd3", label: "Temp_Rsvd3", unit: "\u2103", registerType: "holding", address: 1061, valueKind: "U_WORD", precision: 1 },
  { paramKey: "generationtime_today", label: "GenerationTime_Today", unit: "minutes", registerType: "holding", address: 1062, valueKind: "U_WORD", precision: 1 },
  { paramKey: "generationtime_total", label: "GenerationTime_Total", unit: "minutes", registerType: "holding", address: 1063, valueKind: "U_DWORD", precision: 1 },
  { paramKey: "servicetime_total", label: "ServiceTime_Total", unit: "minutes", registerType: "holding", address: 1065, valueKind: "U_DWORD", precision: 1 },
  { paramKey: "insulationresistance", label: "InsulationResistance", unit: "k\u03a9", registerType: "holding", address: 1067, valueKind: "U_WORD", precision: 1 },
  { paramKey: "systime_year", label: "SysTime_Year", registerType: "holding", address: 1068, valueKind: "U_WORD" },
  { paramKey: "systime_month", label: "SysTime_Month", registerType: "holding", address: 1069, valueKind: "U_WORD" },
  { paramKey: "systime_date", label: "SysTime_Date", registerType: "holding", address: 1070, valueKind: "U_WORD" },
  { paramKey: "systime_hour", label: "SysTime_Hour", registerType: "holding", address: 1071, valueKind: "U_WORD" },
  { paramKey: "systime_minute", label: "SysTime_Minute", registerType: "holding", address: 1072, valueKind: "U_WORD" },
  { paramKey: "systime_second", label: "SysTime_Second", registerType: "holding", address: 1073, valueKind: "U_WORD" },
  { paramKey: "fault19", label: "Fault19", registerType: "holding", address: 1074, valueKind: "U_WORD" },
  { paramKey: "fault20", label: "Fault20", registerType: "holding", address: 1075, valueKind: "U_WORD" },
  { paramKey: "fault21", label: "Fault21", registerType: "holding", address: 1076, valueKind: "U_WORD" },
  { paramKey: "fault22", label: "Fault22", registerType: "holding", address: 1077, valueKind: "U_WORD" },
  { paramKey: "fault23", label: "Fault23", registerType: "holding", address: 1078, valueKind: "U_WORD" },
  { paramKey: "fault24", label: "Fault24", registerType: "holding", address: 1079, valueKind: "U_WORD" },
  { paramKey: "fault25", label: "Fault25", registerType: "holding", address: 1080, valueKind: "U_WORD" },
  { paramKey: "fault26", label: "Fault26", registerType: "holding", address: 1081, valueKind: "U_WORD" },
  { paramKey: "fault27", label: "Fault27", registerType: "holding", address: 1082, valueKind: "U_WORD" },
  { paramKey: "addressmask_realtime_sysinfo2", label: "AddressMask_Realtime_SysInfo2", registerType: "holding", address: 1088, valueKind: "U_QWORD" },
  { paramKey: "production_code", label: "Production_Code", registerType: "holding", address: 1092, valueKind: "U_WORD" },
  { paramKey: "serial_number0", label: "Serial_Number0", registerType: "holding", address: 1093, valueKind: "U_WORD" },
  { paramKey: "serial_number1", label: "Serial_Number1", registerType: "holding", address: 1094, valueKind: "U_WORD" },
  { paramKey: "serial_number2", label: "Serial_Number2", registerType: "holding", address: 1095, valueKind: "U_WORD" },
  { paramKey: "serial_number3", label: "Serial_Number3", registerType: "holding", address: 1096, valueKind: "U_WORD" },
  { paramKey: "serial_number4", label: "Serial_Number4", registerType: "holding", address: 1097, valueKind: "U_WORD" },
  { paramKey: "serial_number5", label: "Serial_Number5", registerType: "holding", address: 1098, valueKind: "U_WORD" },
  { paramKey: "serial_number6", label: "Serial_Number6", registerType: "holding", address: 1099, valueKind: "U_WORD" },
  { paramKey: "hardware_version0", label: "Hardware_Version0", registerType: "holding", address: 1101, valueKind: "U_WORD" },
  { paramKey: "hardware_version1", label: "Hardware_Version1", registerType: "holding", address: 1102, valueKind: "U_WORD" },
  { paramKey: "software_version_stage_com", label: "Software_Version_Stage_COM", registerType: "holding", address: 1103, valueKind: "U_WORD" },
  { paramKey: "software_version_major_com", label: "Software_Version_Major_COM", registerType: "holding", address: 1104, valueKind: "U_WORD" },
  { paramKey: "software_version_custom_com", label: "Software_Version_Custom_COM", registerType: "holding", address: 1105, valueKind: "U_WORD" },
  { paramKey: "software_version_minor_com", label: "Software_Version_Minor_COM", registerType: "holding", address: 1106, valueKind: "U_WORD" },
  { paramKey: "software_version_stage_master", label: "Software_Version_Stage_Master", registerType: "holding", address: 1107, valueKind: "U_WORD" },
  { paramKey: "software_version_major_master", label: "Software_Version_Major_Master", registerType: "holding", address: 1108, valueKind: "U_WORD" },
  { paramKey: "software_version_custom_master", label: "Software_Version_Custom_Master", registerType: "holding", address: 1109, valueKind: "U_WORD" },
  { paramKey: "software_version_minor_master", label: "Software_Version_Minor_Master", registerType: "holding", address: 1110, valueKind: "U_WORD" },
  { paramKey: "software_version_stage_slave", label: "Software_Version_Stage_Slave", registerType: "holding", address: 1111, valueKind: "U_WORD" },
  { paramKey: "software_version_major_slave", label: "Software_Version_Major_Slave", registerType: "holding", address: 1112, valueKind: "U_WORD" },
  { paramKey: "software_version_custom_slave", label: "Software_Version_Custom_Slave", registerType: "holding", address: 1113, valueKind: "U_WORD" },
  { paramKey: "software_version_minor_slave", label: "Software_Version_Minor_Slave", registerType: "holding", address: 1114, valueKind: "U_WORD" },
  { paramKey: "safety_version_major", label: "Safety_Version_Major", registerType: "holding", address: 1115, valueKind: "U_WORD" },
  { paramKey: "safety_version_minor", label: "Safety_version_Minor", registerType: "holding", address: 1116, valueKind: "U_WORD" },
  { paramKey: "addressmask_realtime_gridoutput1", label: "AddressMask_Realtime_GridOutput1", registerType: "holding", address: 1152, valueKind: "U_QWORD" },
  { paramKey: "frequency_grid", label: "Frequency_Grid", unit: "Hz", registerType: "holding", address: 1156, valueKind: "U_WORD", precision: 0 },
  { paramKey: "activepower_output_total", label: "ActivePower_Output_Total", unit: "kW", registerType: "holding", address: 1157, valueKind: "U_WORD", precision: 0 },
  { paramKey: "reactivepower_output_total", label: "ReactivePower_Output_Total", unit: "kW", registerType: "holding", address: 1158, valueKind: "U_WORD", precision: 0 },
  { paramKey: "apparentpower_output_total", label: "ApparentPower_Output_Total", unit: "kW", registerType: "holding", address: 1159, valueKind: "U_WORD", precision: 0 },
  { paramKey: "activepower_pcc_total", label: "ActivePower_PCC_Total", unit: "kW", registerType: "holding", address: 1160, valueKind: "U_WORD", precision: 0 },
  { paramKey: "reactivepower_pcc_total", label: "ReactivePower_PCC_Total", unit: "kW", registerType: "holding", address: 1161, valueKind: "U_WORD", precision: 0 },
  { paramKey: "apparentpower_pcc_total", label: "ApparentPower_PCC_Total", unit: "kW", registerType: "holding", address: 1162, valueKind: "U_WORD", precision: 0 },
  { paramKey: "voltage_phase_r", label: "Voltage_Phase_R", unit: "V", registerType: "holding", address: 1165, valueKind: "U_WORD", precision: 0 },
  { paramKey: "current_output_r", label: "Current_Output_R", unit: "A", registerType: "holding", address: 1166, valueKind: "U_WORD", precision: 0 },
  { paramKey: "activepower_output_r", label: "ActivePower_Output_R", unit: "kW", registerType: "holding", address: 1167, valueKind: "U_WORD", precision: 0 },
  { paramKey: "reactivepower_output_r", label: "ReactivePower_Output_R", unit: "kW", registerType: "holding", address: 1168, valueKind: "U_WORD", precision: 0 },
  { paramKey: "powerfactor_output_r", label: "PowerFactor_Output_R", unit: "p.u.", registerType: "holding", address: 1169, valueKind: "U_WORD", precision: 0 },
  { paramKey: "current_pcc_r", label: "Current_PCC_R", unit: "A", registerType: "holding", address: 1170, valueKind: "U_WORD", precision: 0 },
  { paramKey: "activepower_pcc_r", label: "ActivePower_PCC_R", unit: "kW", registerType: "holding", address: 1171, valueKind: "U_WORD", precision: 0 },
  { paramKey: "reactivepower_pcc_r", label: "ReactivePower_PCC_R", unit: "kW", registerType: "holding", address: 1172, valueKind: "U_WORD", precision: 0 },
  { paramKey: "powerfactor_pcc_r", label: "PowerFactor_PCC_R", unit: "p.u.", registerType: "holding", address: 1173, valueKind: "U_WORD", precision: 0 },
  { paramKey: "voltage_phase_s", label: "Voltage_Phase_S", unit: "V", registerType: "holding", address: 1176, valueKind: "U_WORD", precision: 0 },
  { paramKey: "current_output_s", label: "Current_Output_S", unit: "A", registerType: "holding", address: 1177, valueKind: "U_WORD", precision: 0 },
  { paramKey: "activepower_output_s", label: "ActivePower_Output_S", unit: "kW", registerType: "holding", address: 1178, valueKind: "U_WORD", precision: 0 },
  { paramKey: "reactivepower_output_s", label: "ReactivePower_Output_S", unit: "kW", registerType: "holding", address: 1179, valueKind: "U_WORD", precision: 0 },
  { paramKey: "powerfactor_output_s", label: "PowerFactor_Output_S", unit: "p.u.", registerType: "holding", address: 1180, valueKind: "U_WORD", precision: 0 },
  { paramKey: "current_pcc_s", label: "Current_PCC_S", unit: "A", registerType: "holding", address: 1181, valueKind: "U_WORD", precision: 0 },
  { paramKey: "activepower_pcc_s", label: "ActivePower_PCC_S", unit: "kW", registerType: "holding", address: 1182, valueKind: "U_WORD", precision: 0 },
  { paramKey: "reactivepower_pcc_s", label: "ReactivePower_PCC_S", unit: "kW", registerType: "holding", address: 1183, valueKind: "U_WORD", precision: 0 },
  { paramKey: "powerfactor_pcc_s", label: "PowerFactor_PCC_S", unit: "p.u.", registerType: "holding", address: 1184, valueKind: "U_WORD", precision: 0 },
  { paramKey: "voltage_phase_t", label: "Voltage_Phase_T", unit: "V", registerType: "holding", address: 1187, valueKind: "U_WORD", precision: 0 },
  { paramKey: "current_output_t", label: "Current_Output_T", unit: "A", registerType: "holding", address: 1188, valueKind: "U_WORD", precision: 0 },
  { paramKey: "activepower_output_t", label: "ActivePower_Output_T", unit: "kW", registerType: "holding", address: 1189, valueKind: "U_WORD", precision: 0 },
  { paramKey: "reactivepower_output_t", label: "ReactivePower_Output_T", unit: "kW", registerType: "holding", address: 1190, valueKind: "U_WORD", precision: 0 },
  { paramKey: "powerfactor_output_t", label: "PowerFactor_Output_T", unit: "p.u.", registerType: "holding", address: 1191, valueKind: "U_WORD", precision: 0 },
  { paramKey: "current_pcc_t", label: "Current_PCC_T", unit: "A", registerType: "holding", address: 1192, valueKind: "U_WORD", precision: 0 },
  { paramKey: "activepower_pcc_t", label: "ActivePower_PCC_T", unit: "kW", registerType: "holding", address: 1193, valueKind: "U_WORD", precision: 0 },
  { paramKey: "reactivepower_pcc_t", label: "ReactivePower_PCC_T", unit: "kW", registerType: "holding", address: 1194, valueKind: "U_WORD", precision: 0 },
  { paramKey: "powerfactor_pcc_t", label: "PowerFactor_PCC_T", unit: "p.u.", registerType: "holding", address: 1195, valueKind: "U_WORD", precision: 0 },
  { paramKey: "activepower_pv_ext", label: "ActivePower_PV_Ext", unit: "kW", registerType: "holding", address: 1198, valueKind: "U_WORD", precision: 0 },
  { paramKey: "activepower_load_sys", label: "ActivePower_Load_Sys", unit: "kW", registerType: "holding", address: 1199, valueKind: "U_WORD", precision: 0 },
  { paramKey: "voltage_phase_l1n", label: "Voltage_Phase_L1N", unit: "V", registerType: "holding", address: 1200, valueKind: "U_WORD", precision: 0 },
  { paramKey: "current_output_l1n", label: "Current_Output_L1N", unit: "A", registerType: "holding", address: 1201, valueKind: "U_WORD", precision: 0 },
  { paramKey: "activepower_output_l1n", label: "ActivePower_Output_L1N", unit: "kW", registerType: "holding", address: 1202, valueKind: "U_WORD", precision: 0 },
  { paramKey: "addressmask_realtime_emergencyoutput1", label: "AddressMask_Realtime_EmergencyOutput1", registerType: "holding", address: 1280, valueKind: "U_QWORD" },
  { paramKey: "activepower_load_total", label: "ActivePower_Load_Total", unit: "kW", registerType: "holding", address: 1284, valueKind: "U_WORD", precision: 0 },
  { paramKey: "reactivepower_load_total", label: "ReactivePower_Load_Total", unit: "kW", registerType: "holding", address: 1285, valueKind: "U_WORD", precision: 0 },
  { paramKey: "apparentpower_load_total", label: "ApparentPower_Load_Total", unit: "kW", registerType: "holding", address: 1286, valueKind: "U_WORD", precision: 0 },
  { paramKey: "frequency_output", label: "Frequency_Output", unit: "Hz", registerType: "holding", address: 1287, valueKind: "U_WORD", precision: 0 },
  { paramKey: "voltage_output_r", label: "Voltage_Output_R", unit: "V", registerType: "holding", address: 1290, valueKind: "U_WORD", precision: 0 },
  { paramKey: "current_load_r", label: "Current_Load_R", unit: "A", registerType: "holding", address: 1291, valueKind: "U_WORD", precision: 0 },
  { paramKey: "activepower_load_r", label: "ActivePower_Load_R", unit: "kW", registerType: "holding", address: 1292, valueKind: "U_WORD", precision: 0 },
  { paramKey: "reactivepower_load_r", label: "ReactivePower_Load_R", unit: "kW", registerType: "holding", address: 1293, valueKind: "U_WORD", precision: 0 },
  { paramKey: "apparentpower_load_r", label: "ApparentPower_Load_R", unit: "kVA", registerType: "holding", address: 1294, valueKind: "U_WORD", precision: 0 },
  { paramKey: "loadpeakratio_r", label: "LoadPeakRatio_R", unit: "p.u.", registerType: "holding", address: 1295, valueKind: "U_WORD", precision: 0 },
  { paramKey: "voltage_output_s", label: "Voltage_Output_S", unit: "V", registerType: "holding", address: 1298, valueKind: "U_WORD", precision: 0 },
  { paramKey: "current_load_s", label: "Current_Load_S", unit: "A", registerType: "holding", address: 1299, valueKind: "U_WORD", precision: 0 },
  { paramKey: "activepower_load_s", label: "ActivePower_Load_S", unit: "kW", registerType: "holding", address: 1300, valueKind: "U_WORD", precision: 0 },
  { paramKey: "reactivepower_load_s", label: "ReactivePower_Load_S", unit: "kW", registerType: "holding", address: 1301, valueKind: "U_WORD", precision: 0 },
  { paramKey: "apparentpower_load_s", label: "ApparentPower_Load_S", unit: "kVA", registerType: "holding", address: 1302, valueKind: "U_WORD", precision: 0 },
  { paramKey: "loadpeakratio_s", label: "LoadPeakRatio_S", unit: "p.u.", registerType: "holding", address: 1303, valueKind: "U_WORD", precision: 0 },
  { paramKey: "voltage_output_t", label: "Voltage_Output_T", unit: "V", registerType: "holding", address: 1306, valueKind: "U_WORD", precision: 0 },
  { paramKey: "current_load_t", label: "Current_Load_T", unit: "A", registerType: "holding", address: 1307, valueKind: "U_WORD", precision: 0 },
  { paramKey: "activepower_load_t", label: "ActivePower_Load_T", unit: "kW", registerType: "holding", address: 1308, valueKind: "U_WORD", precision: 0 },
  { paramKey: "reactivepower_load_t", label: "ReactivePower_Load_T", unit: "kW", registerType: "holding", address: 1309, valueKind: "U_WORD", precision: 0 },
  { paramKey: "apparentpower_load_t", label: "ApparentPower_Load_T", unit: "kVA", registerType: "holding", address: 1310, valueKind: "U_WORD", precision: 0 },
  { paramKey: "loadpeakratio_t", label: "LoadPeakRatio_T", unit: "p.u.", registerType: "holding", address: 1311, valueKind: "U_WORD", precision: 0 },
  { paramKey: "voltage_output_l1n", label: "Voltage_Output_L1N", unit: "V", registerType: "holding", address: 1314, valueKind: "U_WORD", precision: 0 },
  { paramKey: "current_load_l1n", label: "Current_Load_L1N", unit: "A", registerType: "holding", address: 1315, valueKind: "U_WORD", precision: 0 },
  { paramKey: "activepower_load_l1n", label: "ActivePower_Load_L1N", unit: "kW", registerType: "holding", address: 1316, valueKind: "U_WORD", precision: 0 },
  { paramKey: "voltage_output_l2n", label: "Voltage_Output_L2N", unit: "V", registerType: "holding", address: 1317, valueKind: "U_WORD", precision: 0 },
  { paramKey: "current_load_l2n", label: "Current_Load_L2N", unit: "A", registerType: "holding", address: 1318, valueKind: "U_WORD", precision: 0 },
  { paramKey: "activepower_load_l2n", label: "ActivePower_Load_L2N", unit: "kW", registerType: "holding", address: 1319, valueKind: "U_WORD", precision: 0 },
  { paramKey: "powerupspeed", label: "PowerUpSpeed", unit: "%Pn/min", registerType: "holding", address: 2049, valueKind: "U_WORD", precision: 1 },
  { paramKey: "activeoutputlimit", label: "ActiveOutputLimit", unit: "%", registerType: "holding", address: 2305, valueKind: "U_WORD", precision: 0 },
  { paramKey: "energystatistics_config", label: "EnergyStatistics_Config", registerType: "holding", address: 4147, valueKind: "U_WORD" },
  { paramKey: "parallel_control", label: "Parallel_Control", registerType: "holding", address: 4149, valueKind: "U_WORD" },
  { paramKey: "unbalancedsupport_control", label: "UnbalancedSupport_Control", registerType: "holding", address: 4152, valueKind: "U_WORD" },
];
