import type { DriverRegister } from '../driverStore.js';

export const solaxRegisters: DriverRegister[] = [
  { paramKey: "timestart", label: "launch wait time", unit: "s", registerType: "holding", address: 22, valueKind: "U_WORD" },
  { paramKey: "reconnectiontime", label: "Reconnection Time", unit: "s", registerType: "holding", address: 23, valueKind: "U_WORD" },
  { paramKey: "checkingtime", label: "CheckingTime", unit: "s", registerType: "holding", address: 24, valueKind: "U_WORD" },
  { paramKey: "vacminprotect", label: "allowed minimum grid voltage", unit: "V", registerType: "holding", address: 25, valueKind: "U_WORD", scale: 0.1 },
  { paramKey: "vacmaxprotect", label: "allowed maximum grid voltage", unit: "V", registerType: "holding", address: 26, valueKind: "U_WORD", scale: 0.1 },
  { paramKey: "facminprotect", label: "allowed minimum grid frequency", unit: "Hz", registerType: "holding", address: 27, valueKind: "U_WORD", scale: 0.01 },
  { paramKey: "facmaxprotect", label: "allowed maximum grid frequency", unit: "Hz", registerType: "holding", address: 28, valueKind: "U_WORD", scale: 0.01 },
  { paramKey: "safetycode", label: "Safety type", registerType: "holding", address: 29, valueKind: "U_WORD" },
  { paramKey: "powerfactordata", label: "Power factor data", unit: "0.01", registerType: "holding", address: 39, valueKind: "U_WORD" },
  { paramKey: "powerfactor_curve_pf1", label: "PowerFactor_Curve_PF1", unit: "0.01", registerType: "holding", address: 40, valueKind: "U_WORD" },
  { paramKey: "powerfactor_curve_pf2", label: "PowerFactor_Curve_PF2", unit: "0.01", registerType: "holding", address: 41, valueKind: "U_WORD" },
  { paramKey: "powerfactor_curve_pf3", label: "PowerFactor_Curve_PF3", unit: "0.01", registerType: "holding", address: 42, valueKind: "U_WORD" },
  { paramKey: "powerfactor_curve_pf4", label: "PowerFactor_Curve_PF4", unit: "0.01", registerType: "holding", address: 43, valueKind: "U_WORD" },
  { paramKey: "powerfactor_curve_pflockinpoint", label: "PowerFactor_Curve_PfLockInPoint", unit: "0.01", registerType: "holding", address: 48, valueKind: "U_WORD" },
  { paramKey: "powerfactor_curve_pflockoutpoint", label: "PowerFactor_Curve_PfLockOutPoint", unit: "0.01", registerType: "holding", address: 49, valueKind: "U_WORD" },
  { paramKey: "powerfactor_curve_3tau", label: "PowerFactor_Curve_3Tau", unit: "s", registerType: "holding", address: 50, valueKind: "U_WORD" },
  { paramKey: "powerfactor_qu_quresponsev1", label: "PowerFactor_Qu_QuResponseV1", unit: "V", registerType: "holding", address: 53, valueKind: "U_WORD", scale: 0.1 },
  { paramKey: "powerfactor_qu_quresponsev2", label: "PowerFactor_Qu_QuResponseV2", unit: "V", registerType: "holding", address: 54, valueKind: "U_WORD", scale: 0.1 },
  { paramKey: "powerfactor_qu_quresponsev3", label: "PowerFactor_Qu_QuResponseV3", unit: "V", registerType: "holding", address: 55, valueKind: "U_WORD", scale: 0.1 },
  { paramKey: "powerfactor_qu_quresponsev4", label: "PowerFactor_Qu_QuResponseV4", unit: "V", registerType: "holding", address: 56, valueKind: "U_WORD", scale: 0.1 },
  { paramKey: "powerfactor_qu_k", label: "PowerFactor_Qu_K", unit: "0.1", registerType: "holding", address: 57, valueKind: "S_WORD" },
  { paramKey: "powerfactor_qu_3tau", label: "PowerFactor_Qu_3Tau", unit: "s", registerType: "holding", address: 58, valueKind: "U_WORD" },
  { paramKey: "powerfactor_qu_qudelaytimer", label: "PowerFactor_Qu_QuDelayTimer", unit: "s", registerType: "holding", address: 59, valueKind: "U_WORD" },
  { paramKey: "powerfactor_fixqpower", label: "PowerFactor_FixQPower", unit: "Var", registerType: "holding", address: 63, valueKind: "S_WORD" },
  { paramKey: "powerfactor_fixqpower_max", label: "PowerFactor_FixQPower_Max", unit: "Var", registerType: "holding", address: 64, valueKind: "S_WORD" },
  { paramKey: "powerfactor_fixqpower_min", label: "PowerFactor_FixQPower_Min", unit: "Var", registerType: "holding", address: 65, valueKind: "S_WORD" },
  { paramKey: "wconnection_fl", label: "Connection Low frequency", unit: "Hz", registerType: "holding", address: 66, valueKind: "S_WORD", scale: 0.01 },
  { paramKey: "wconnection_fh", label: "Connection High frequency", unit: "Hz", registerType: "holding", address: 67, valueKind: "S_WORD", scale: 0.01 },
  { paramKey: "wconnection_vl", label: "Connection Low voltage", unit: "V", registerType: "holding", address: 68, valueKind: "S_WORD", scale: 0.1 },
  { paramKey: "wconnection_vh", label: "Connection High voltage", unit: "V", registerType: "holding", address: 69, valueKind: "S_WORD", scale: 0.1 },
  { paramKey: "wconnection_observet", label: "Connection Observation time", unit: "S", registerType: "holding", address: 70, valueKind: "S_WORD" },
  { paramKey: "wconnection_gradienten", label: "Connection Gradient Select", unit: "1", registerType: "holding", address: 71, valueKind: "S_WORD" },
  { paramKey: "wreconnection_fl", label: "Reconnection Low frequency", unit: "HZ", registerType: "holding", address: 72, valueKind: "S_WORD", scale: 0.01 },
  { paramKey: "wreconnection_fh", label: "Reconnection High frequency", unit: "Hz", registerType: "holding", address: 73, valueKind: "S_WORD", scale: 0.01 },
  { paramKey: "wreconnection_vl", label: "Reconnection Low voltage", unit: "V", registerType: "holding", address: 74, valueKind: "S_WORD", scale: 0.1 },
  { paramKey: "wreconnection_vh", label: "Reconnection High voltage", unit: "V", registerType: "holding", address: 75, valueKind: "S_WORD", scale: 0.1 },
  { paramKey: "wreconnection_observet", label: "Reconnection Observation time", unit: "S", registerType: "holding", address: 76, valueKind: "S_WORD" },
  { paramKey: "wreconnection_gradienten", label: "Reconnection Gradient Select", unit: "1", registerType: "holding", address: 77, valueKind: "S_WORD" },
  { paramKey: "firmwareversion_dsp_minor", label: "FirmwareVersion_DSP_Minor", unit: "1", registerType: "holding", address: 125, valueKind: "U_WORD" },
  { paramKey: "hardwareversion_dsp", label: "HardwareVersion_DSP", unit: "1", registerType: "holding", address: 126, valueKind: "U_WORD" },
  { paramKey: "firmwareversion_dsp_major", label: "FirmwareVersion_DSP_Major", unit: "1", registerType: "holding", address: 127, valueKind: "U_WORD" },
  { paramKey: "firmwareversion_arm_major", label: "FirmwareVersion_ARM_Major", unit: "1", registerType: "holding", address: 128, valueKind: "U_WORD" },
  { paramKey: "firmwareversion_arm_minor", label: "FirmwareVersion_ARM_Minor", unit: "1", registerType: "holding", address: 131, valueKind: "U_WORD" },
  { paramKey: "firmwareversion_arm_bootloader", label: "FirmwareVersion_ARM_Bootloader", unit: "1", registerType: "holding", address: 132, valueKind: "U_WORD" },
  { paramKey: "rtc_seconds", label: "RTC-Seconds", registerType: "holding", address: 133, valueKind: "U_WORD" },
  { paramKey: "rtc_minutes", label: "RTC-Minutes", registerType: "holding", address: 134, valueKind: "U_WORD" },
  { paramKey: "rtc_hours", label: "RTC-Hours", registerType: "holding", address: 135, valueKind: "U_WORD" },
  { paramKey: "rtc_days", label: "RTC-Days", registerType: "holding", address: 136, valueKind: "U_WORD" },
  { paramKey: "rtc_months", label: "RTC-Months", registerType: "holding", address: 137, valueKind: "U_WORD" },
  { paramKey: "rtc_years", label: "RTC-Years", registerType: "holding", address: 138, valueKind: "U_WORD" },
  { paramKey: "wbattery1_type", label: "0\uff1aLead Acid 1\uff1aLithium", unit: "1", registerType: "holding", address: 141, valueKind: "U_WORD" },
  { paramKey: "absorpt_voltage", label: "Lead-acid battery absorpt_voltage", unit: "V", registerType: "holding", address: 146, valueKind: "U_WORD", scale: 0.1 },
  { paramKey: "hotstandbyen", label: "0:enable 1:disable", unit: "1", registerType: "holding", address: 161, valueKind: "U_WORD" },
  { paramKey: "extendbmssetting", label: "0:disable 1:enable", unit: "1", registerType: "holding", address: 162, valueKind: "U_WORD" },
  { paramKey: "batteryheatingen", label: "0:disable 1:enable", registerType: "holding", address: 163, valueKind: "U_WORD" },
  { paramKey: "wbatterydischargebackupvoltage", label: "wBatteryDischargeBackupVoltage", unit: "V", registerType: "holding", address: 168, valueKind: "U_WORD", scale: 0.1 },
  { paramKey: "matchresistanceset_x3", label: "0:disable 1:enable", registerType: "holding", address: 169, valueKind: "U_WORD" },
  { paramKey: "modbusrtu_address", label: "ModBusRTU_Address", unit: "1", registerType: "holding", address: 175, valueKind: "U_WORD" },
  { paramKey: "pgridbias", label: "0:Disable 1:Grid 2:INV", registerType: "holding", address: 178, valueKind: "U_WORD" },
  { paramKey: "factorylimit", label: "Factorylimit", unit: "W", registerType: "holding", address: 181, valueKind: "U_WORD" },
  { paramKey: "off_grid_mute", label: "0(off)/1(on)", unit: "1", registerType: "holding", address: 183, valueKind: "U_WORD" },
  { paramKey: "wtuvp_l2", label: "wTuvp_L2", unit: "ms", registerType: "holding", address: 189, valueKind: "U_WORD" },
  { paramKey: "wtovp_l2", label: "wTovp_L2", unit: "ms", registerType: "holding", address: 190, valueKind: "U_WORD" },
  { paramKey: "wtufp_l2", label: "wTufp_L2", unit: "ms", registerType: "holding", address: 191, valueKind: "U_WORD" },
  { paramKey: "wtofp_l2", label: "wTofp_L2", unit: "ms", registerType: "holding", address: 192, valueKind: "U_WORD" },
  { paramKey: "wtuvp_l1", label: "wTuvp_L1", unit: "ms", registerType: "holding", address: 193, valueKind: "U_WORD" },
  { paramKey: "wtovp_l1", label: "wTovp_L1", unit: "ms", registerType: "holding", address: 194, valueKind: "U_WORD" },
  { paramKey: "wtufp_l1", label: "wTufp_L1", unit: "ms", registerType: "holding", address: 195, valueKind: "U_WORD" },
  { paramKey: "wtofp_l1", label: "wTofp_L1", unit: "ms", registerType: "holding", address: 196, valueKind: "U_WORD" },
  { paramKey: "mainbreakercurrentlimit", label: "32A~100A", unit: "A", registerType: "holding", address: 215, valueKind: "U_WORD" },
  { paramKey: "ofpl_point", label: "Overfrequency load reduction point.", unit: "Hz", registerType: "holding", address: 219, valueKind: "U_WORD", scale: 0.01 },
  { paramKey: "ofpl_fstop_disch", label: "OFPL_fstop_disch", unit: "Hz", registerType: "holding", address: 222, valueKind: "U_WORD", scale: 0.01 },
  { paramKey: "ofpl_fpmin", label: "OFPL_fPmin", unit: "Hz", registerType: "holding", address: 223, valueKind: "U_WORD", scale: 0.01 },
  { paramKey: "userpassword", label: "UserPassword", unit: "1", registerType: "holding", address: 224, valueKind: "U_WORD" },
  { paramKey: "advancepassword", label: "AdvancePassword", unit: "1", registerType: "holding", address: 225, valueKind: "U_WORD" },
  { paramKey: "ufpl_point", label: "Underfrequency load increase point.", unit: "Hz", registerType: "holding", address: 226, valueKind: "U_WORD", scale: 0.01 },
  { paramKey: "exportsoftlimiten", label: "ExportSoftLimitEn", registerType: "holding", address: 233, valueKind: "U_WORD" },
  { paramKey: "exporthardlimiten", label: "ExportHardLimitEn", registerType: "holding", address: 234, valueKind: "U_WORD" },
  { paramKey: "generalsoftlimiten", label: "GeneralSoftLimitEn", registerType: "holding", address: 235, valueKind: "U_WORD" },
  { paramKey: "generalhardlimiten", label: "GeneralHardLimitEn", registerType: "holding", address: 236, valueKind: "U_WORD" },
  { paramKey: "setpointtimeout", label: "SetpointTimeout", unit: "ms", registerType: "holding", address: 242, valueKind: "U_WORD" },
  { paramKey: "wpowerlimitgra", label: "wPowerLimitGra", unit: "0.0001", registerType: "holding", address: 243, valueKind: "U_WORD" },
  { paramKey: "pufunc_3tau", label: "PuFunc_3Tau", unit: "0.01", registerType: "holding", address: 248, valueKind: "U_WORD" },
  { paramKey: "pufuncenable", label: "0:disable 1:enable", unit: "1", registerType: "holding", address: 249, valueKind: "U_WORD" },
  { paramKey: "pu_tpye", label: "Pu_Tpye", unit: "1", registerType: "holding", address: 255, valueKind: "U_WORD" },
  { paramKey: "ufpl_fstop_ch", label: "UFPL_fstop_ch", unit: "Hz", registerType: "holding", address: 256, valueKind: "U_WORD", scale: 0.01 },
  { paramKey: "ufpl_fpmax", label: "UFPL_fPmax", unit: "Hz", registerType: "holding", address: 257, valueKind: "U_WORD", scale: 0.01 },
  { paramKey: "drmfunctionenable", label: "0:disable 1:enable", unit: "1", registerType: "holding", address: 258, valueKind: "U_WORD" },
  { paramKey: "wshadowfixfuncenable", label: "0:Off, 1:Low, 2:Middle, 3:Hight", unit: "1", registerType: "holding", address: 260, valueKind: "U_WORD" },
  { paramKey: "machinetype_x1orx3", label: "1:X1 3:X3", registerType: "holding", address: 261, valueKind: "U_WORD" },
  { paramKey: "phasepowerbalance_x3", label: "0:disable 1:enable", unit: "1", registerType: "holding", address: 262, valueKind: "U_WORD" },
  { paramKey: "wmachinestyle", label: "0:X-Hybrid 1:X-FIT", unit: "1", registerType: "holding", address: 263, valueKind: "U_WORD" },
  { paramKey: "meterfunction", label: "0:disable 1:enable", unit: "1", registerType: "holding", address: 264, valueKind: "U_WORD" },
  { paramKey: "meter1id", label: "Meter1ID 1~200", unit: "1", registerType: "holding", address: 265, valueKind: "U_WORD" },
  { paramKey: "meter2id", label: "Meter2ID 1~200", unit: "1", registerType: "holding", address: 266, valueKind: "U_WORD" },
  { paramKey: "directionmeterct1", label: "0:Positive 1:Negative", unit: "1", registerType: "holding", address: 267, valueKind: "U_WORD" },
  { paramKey: "directionmeter2", label: "0:Positive 1:Negative", unit: "1", registerType: "holding", address: 268, valueKind: "U_WORD" },
  { paramKey: "externalinv", label: "0:Enable1:Disable", unit: "1", registerType: "holding", address: 269, valueKind: "U_WORD" },
  { paramKey: "inputdi1", label: "0:\u4f4e\u7535\u5e73 1:\u9ad8\u7535\u5e73", unit: "1", registerType: "holding", address: 272, valueKind: "U_WORD" },
  { paramKey: "rev", label: "-", registerType: "holding", address: 274, valueKind: "U_WORD" },
  { paramKey: "shadowfixfuncenable2", label: "-0:Off, 1:Low, 2:Middle, 3:Hight", unit: "1", registerType: "holding", address: 276, valueKind: "U_WORD" },
  { paramKey: "fvrt_function", label: "0:Disable 1:Enable", unit: "1", registerType: "holding", address: 278, valueKind: "U_WORD" },
  { paramKey: "rev_2", label: "-", registerType: "holding", address: 281, valueKind: "U_WORD" },
  { paramKey: "rev_3", label: "-", registerType: "holding", address: 282, valueKind: "U_WORD" },
  { paramKey: "bpvconnectionmode_x1", label: "PV connection.", unit: "1", registerType: "holding", address: 283, valueKind: "U_WORD" },
  { paramKey: "shutdown_x1", label: "0:Disable 1:Enable", unit: "1", registerType: "holding", address: 284, valueKind: "U_WORD" },
  { paramKey: "microgrid_x1", label: "0:Disable 1:Enable", unit: "1", registerType: "holding", address: 285, valueKind: "U_WORD" },
  { paramKey: "selfusemodebackupen", label: "0:Disable 1:Enable", unit: "1", registerType: "holding", address: 286, valueKind: "U_WORD" },
  { paramKey: "bleasemodeenable", label: "0:Disable 1:Enable", unit: "1", registerType: "holding", address: 288, valueKind: "U_WORD" },
  { paramKey: "bdevicelockflag", label: "0:Disable 1:Enable", unit: "1", registerType: "holding", address: 289, valueKind: "U_WORD" },
  { paramKey: "manualmodecontrol", label: "0:OFF 1:ON", unit: "1", registerType: "holding", address: 290, valueKind: "U_WORD" },
  { paramKey: "feedinonpower", label: "Grid connected pull in power point", unit: "W", registerType: "holding", address: 291, valueKind: "U_WORD" },
  { paramKey: "consumeoffpower", label: "Power consumption off trigger point", unit: "W", registerType: "holding", address: 293, valueKind: "U_WORD" },
  { paramKey: "minimumperonsignal", label: "Minimum duration of single pull in", unit: "min", registerType: "holding", address: 295, valueKind: "U_WORD" },
  { paramKey: "bscheduleenable", label: "0:Disable 1:Enable", unit: "1", registerType: "holding", address: 297, valueKind: "U_WORD" },
  { paramKey: "workmode", label: "0:Disable 1:manual 2:SmartSave", unit: "1", registerType: "holding", address: 302, valueKind: "U_WORD" },
  { paramKey: "externalgenen", label: "0:Disable 1:Enable", unit: "1", registerType: "holding", address: 305, valueKind: "U_WORD" },
  { paramKey: "485commfunselect", label: "0:modbus 485 1:EV Charge", unit: "1", registerType: "holding", address: 318, valueKind: "U_WORD" },
  { paramKey: "subsystem_num", label: "Subsystem_Num", unit: "1", registerType: "holding", address: 512, valueKind: "U_WORD" },
  { paramKey: "gridvoltage_x1", label: "GridVoltage", unit: "V", registerType: "holding", address: 0, valueKind: "U_WORD", scale: 0.1 },
  { paramKey: "gridcurrent_x1", label: "GridCurrent", unit: "A", registerType: "holding", address: 1, valueKind: "S_WORD", scale: 0.1 },
  { paramKey: "gridpower_x1", label: "GridPower", unit: "W", registerType: "holding", address: 2, valueKind: "S_WORD" },
  { paramKey: "pvvoltage1", label: "PvVoltage1", unit: "V", registerType: "holding", address: 3, valueKind: "U_WORD", scale: 0.1 },
  { paramKey: "pvvoltage2", label: "PvVoltage2", unit: "V", registerType: "holding", address: 4, valueKind: "U_WORD", scale: 0.1 },
  { paramKey: "pvcurrent1", label: "PvCurrent1", unit: "A", registerType: "holding", address: 5, valueKind: "U_WORD", scale: 0.1 },
  { paramKey: "pvcurrent2", label: "PvCurrent2", unit: "A", registerType: "holding", address: 6, valueKind: "U_WORD", scale: 0.1 },
  { paramKey: "gridfrequency_x1", label: "GridFrequency", unit: "Hz", registerType: "holding", address: 7, valueKind: "U_WORD", scale: 0.01 },
  { paramKey: "runmode", label: "Table 2-2 Run mode description", registerType: "holding", address: 9, valueKind: "U_WORD" },
  { paramKey: "powerdc1", label: "Powerdc1", unit: "W", registerType: "holding", address: 10, valueKind: "U_WORD" },
  { paramKey: "powerdc2", label: "Powerdc2", unit: "W", registerType: "holding", address: 11, valueKind: "U_WORD" },
  { paramKey: "pv1voltfaultvalue", label: "Pv1VoltFaultValue", unit: "V", registerType: "holding", address: 13, valueKind: "U_WORD", scale: 0.1 },
  { paramKey: "pv2voltfaultvalue", label: "Pv2VoltFaultValue", unit: "V", registerType: "holding", address: 14, valueKind: "U_WORD", scale: 0.1 },
  { paramKey: "gfcifaultvalue", label: "GfciFaultValue", unit: "mA", registerType: "holding", address: 15, valueKind: "U_WORD" },
  { paramKey: "gridvoltfaultvalue", label: "GridVoltFaultValue", unit: "V", registerType: "holding", address: 16, valueKind: "U_WORD", scale: 0.1 },
  { paramKey: "gridfreqfaultvaluet", label: "GridFreqFaultValueT", unit: "Hz", registerType: "holding", address: 17, valueKind: "U_WORD", scale: 0.01 },
  { paramKey: "dcifaultvalue", label: "DciFaultValue", unit: "mA", registerType: "holding", address: 18, valueKind: "U_WORD" },
  { paramKey: "timecountdown", label: "TimeCountDown", unit: "ms", registerType: "holding", address: 19, valueKind: "U_WORD" },
  { paramKey: "batvoltage_charge1", label: "BatVoltage_Charge1", unit: "V", registerType: "holding", address: 20, valueKind: "S_WORD", scale: 0.1 },
  { paramKey: "batcurrent_charge1", label: "BatCurrent_Charge1", unit: "A", registerType: "holding", address: 21, valueKind: "S_WORD", scale: 0.1 },
  { paramKey: "batpower_charge1", label: "Batpower_Charge1", unit: "W", registerType: "holding", address: 22, valueKind: "S_WORD" },
  { paramKey: "bdcstatus", label: "0: discharge 1: charge", registerType: "holding", address: 25, valueKind: "U_WORD" },
  { paramKey: "gridstatus", label: "0: OnGrid 1: OffGrid", registerType: "holding", address: 26, valueKind: "U_WORD" },
  { paramKey: "mpptcount", label: "MPPTCount", unit: "1", registerType: "holding", address: 27, valueKind: "U_WORD" },
  { paramKey: "outputenergy_charge_lsb", label: "OutputEnergy_Charge", unit: "kWh", registerType: "holding", address: 29, valueKind: "U_WORD", scale: 0.1 },
  { paramKey: "outputenergy_charge_msb", label: "OutputEnergy_Charge", unit: "kWh", registerType: "holding", address: 30, valueKind: "U_WORD", scale: 0.1 },
  { paramKey: "outputenergy_charge_today", label: "OutputEnergy_Charge_today", unit: "kWh", registerType: "holding", address: 32, valueKind: "U_WORD", scale: 0.1 },
  { paramKey: "inputenergy_charge_lsb", label: "InputEnergy_Charge", unit: "kWh", registerType: "holding", address: 33, valueKind: "U_WORD", scale: 0.1 },
  { paramKey: "inputenergy_charge_msb", label: "InputEnergy_Charge", unit: "kWh", registerType: "holding", address: 34, valueKind: "U_WORD", scale: 0.1 },
  { paramKey: "inputenergy_charge_today", label: "InputEnergy_Charge_today", unit: "kWh", registerType: "holding", address: 35, valueKind: "U_WORD", scale: 0.1 },
  { paramKey: "pcsmajorfault", label: "PCSMajorFault", registerType: "holding", address: 62, valueKind: "U_WORD" },
  { paramKey: "batterymajorfault", label: "BatteryMajorFault", registerType: "holding", address: 63, valueKind: "U_WORD" },
  { paramKey: "rev_4", label: "REV", registerType: "holding", address: 66, valueKind: "U_WORD" },
  { paramKey: "bat_bms_faultmessage_lsb", label: "Table 2-6 BMS error code", registerType: "holding", address: 68, valueKind: "U_WORD" },
  { paramKey: "off_gridvoltage_x1", label: "Off-grid Voltage", unit: "V", registerType: "holding", address: 76, valueKind: "U_WORD", scale: 0.1 },
  { paramKey: "off_gridcurrent_x1", label: "Off-grid Current", unit: "A", registerType: "holding", address: 77, valueKind: "U_WORD", scale: 0.1 },
  { paramKey: "off_gridpower_x1", label: "Off-grid power", unit: "VA", registerType: "holding", address: 78, valueKind: "U_WORD" },
  { paramKey: "off_gridfrequency_x1", label: "Off-grid _Frequency", unit: "Hz", registerType: "holding", address: 79, valueKind: "U_WORD", scale: 0.01 },
  { paramKey: "busvolt", label: "BusVolt", unit: "V", registerType: "holding", address: 102, valueKind: "U_WORD", scale: 0.1 },
  { paramKey: "wdcvfaultval", label: "wDcvFaultVal", unit: "V", registerType: "holding", address: 103, valueKind: "U_WORD", scale: 0.1 },
  { paramKey: "woverloadfaultval", label: "wOverLoadFaultval", unit: "W", registerType: "holding", address: 104, valueKind: "U_WORD" },
  { paramKey: "wbatteryvoltfaultval", label: "wBatteryVoltFaultVal", unit: "V", registerType: "holding", address: 105, valueKind: "U_WORD", scale: 0.1 },
  { paramKey: "gridvoltage_r_x3", label: "GridVoltage_R", unit: "V", registerType: "holding", address: 106, valueKind: "U_WORD", scale: 0.1 },
  { paramKey: "gridcurrent_r_x3", label: "GridCurrent_R", unit: "A", registerType: "holding", address: 107, valueKind: "S_WORD", scale: 0.1 },
  { paramKey: "gridpower_r_x3", label: "GridPower_R", unit: "W", registerType: "holding", address: 108, valueKind: "S_WORD" },
  { paramKey: "gridfrequency_r_x3", label: "GridFrequency_R", unit: "Hz", registerType: "holding", address: 109, valueKind: "U_WORD", scale: 0.01 },
  { paramKey: "gridvoltage_s_x3", label: "GridVoltage_S", unit: "V", registerType: "holding", address: 110, valueKind: "U_WORD", scale: 0.1 },
  { paramKey: "gridcurrent_s_x3", label: "GridCurrent_S", unit: "A", registerType: "holding", address: 111, valueKind: "S_WORD", scale: 0.1 },
  { paramKey: "gridpower_s_x3", label: "GridPower_S", unit: "W", registerType: "holding", address: 112, valueKind: "S_WORD" },
  { paramKey: "gridfrequency_s_x3", label: "GridFrequency_S", unit: "Hz", registerType: "holding", address: 113, valueKind: "U_WORD", scale: 0.01 },
  { paramKey: "gridvoltage_t_x3", label: "GridVoltage_T", unit: "V", registerType: "holding", address: 114, valueKind: "U_WORD", scale: 0.1 },
  { paramKey: "gridcurrent_t_x3", label: "GridCurrent_T", unit: "A", registerType: "holding", address: 115, valueKind: "S_WORD", scale: 0.1 },
  { paramKey: "gridpower_t_x3", label: "GridPower_T", unit: "W", registerType: "holding", address: 116, valueKind: "S_WORD" },
  { paramKey: "gridfrequency_t_x3", label: "GridFrequency_T", unit: "Hz", registerType: "holding", address: 117, valueKind: "U_WORD", scale: 0.01 },
  { paramKey: "off_grid_volt_r_x3", label: "Off-grid_Volt_R", unit: "V", registerType: "holding", address: 118, valueKind: "U_WORD", scale: 0.1 },
  { paramKey: "off_grid_current_r_x3", label: "Off-grid_Current_R", unit: "A", registerType: "holding", address: 119, valueKind: "U_WORD", scale: 0.1 },
  { paramKey: "off_grid_poweractive_r_x3", label: "Off-grid_PowerActive_R", unit: "W", registerType: "holding", address: 120, valueKind: "S_WORD" },
  { paramKey: "off_grid_powers_r_x3", label: "Off-grid_PowerS_R", unit: "VA", registerType: "holding", address: 121, valueKind: "U_WORD" },
  { paramKey: "off_grid_volt_s_x3", label: "Off-grid_Volt_S", unit: "V", registerType: "holding", address: 122, valueKind: "U_WORD", scale: 0.1 },
  { paramKey: "off_grid_current_s_x3", label: "Off-grid_Current_S", unit: "A", registerType: "holding", address: 123, valueKind: "U_WORD", scale: 0.1 },
  { paramKey: "off_gridpoweractive_s_x3", label: "Off-gridPowerActive_S", unit: "W", registerType: "holding", address: 124, valueKind: "S_WORD" },
  { paramKey: "off_gridpowers_s_x3", label: "Off-gridPowerS_S", unit: "VA", registerType: "holding", address: 125, valueKind: "U_WORD" },
  { paramKey: "off_grid_volt_t_x3", label: "Off-grid_Volt_T", unit: "V", registerType: "holding", address: 126, valueKind: "U_WORD", scale: 0.1 },
  { paramKey: "off_grid_current_t_x3", label: "Off-grid_Current_T", unit: "A", registerType: "holding", address: 127, valueKind: "U_WORD", scale: 0.1 },
  { paramKey: "off_gridpoweractive_t_x3", label: "Off-gridPowerActive_T", unit: "W", registerType: "holding", address: 128, valueKind: "S_WORD" },
  { paramKey: "off_gridpowers_t_x3", label: "Off-gridPowerS_T", unit: "VA", registerType: "holding", address: 129, valueKind: "U_WORD" },
  { paramKey: "off_gridyieldtoday", label: "Off-gridYieldToday", unit: "kWh", registerType: "holding", address: 144, valueKind: "U_WORD", scale: 0.1 },
  { paramKey: "solarenergytoday", label: "SolarEnergyToday", unit: "kWh", registerType: "holding", address: 150, valueKind: "U_WORD", scale: 0.1 },
  { paramKey: "rev_5", label: "-", registerType: "holding", address: 151, valueKind: "U_WORD" },
  { paramKey: "invvoltr_x3", label: "InvVoltR(X3)", unit: "V", registerType: "holding", address: 156, valueKind: "U_WORD", scale: 0.1 },
  { paramKey: "invvolts_x3", label: "InvVoltS(X3)", unit: "V", registerType: "holding", address: 157, valueKind: "U_WORD", scale: 0.1 },
  { paramKey: "invvoltt_x3", label: "InvVoltT(X3)", unit: "V", registerType: "holding", address: 158, valueKind: "U_WORD", scale: 0.1 },
  { paramKey: "feedin_energy_total_meter2", label: "energy to the grid", unit: "kWh", registerType: "holding", address: 170, valueKind: "U_DWORD", scale: 0.01 },
  { paramKey: "meter1communicationsate", label: "0:Com Error 1:Normal", unit: "1", registerType: "holding", address: 184, valueKind: "U_WORD" },
  { paramKey: "meter2communicationsate", label: "0:Com Error 1:Normal", unit: "1", registerType: "holding", address: 185, valueKind: "U_WORD" },
  { paramKey: "cell_voltage_high", label: "Cell_Voltage_High", unit: "V", registerType: "holding", address: 188, valueKind: "U_WORD", scale: 0.001 },
  { paramKey: "cell_voltage_low", label: "Cell_Voltage_Low", unit: "V", registerType: "holding", address: 189, valueKind: "U_WORD", scale: 0.001 },
  { paramKey: "gridreactivepower_total_meter", label: "GridReactivePower_Total_Meter", unit: "Var", registerType: "holding", address: 192, valueKind: "S_WORD" },
  { paramKey: "gridreactivepower_r_meter", label: "GridReactivePower_R_Meter", unit: "Var", registerType: "holding", address: 193, valueKind: "S_WORD" },
  { paramKey: "gridreactivepower_s_meter", label: "GridReactivePower_S_Meter", unit: "Var", registerType: "holding", address: 194, valueKind: "S_WORD" },
  { paramKey: "gridreactivepower_t_meter", label: "GridReactivePower_T_Meter", unit: "Var", registerType: "holding", address: 195, valueKind: "S_WORD" },
  { paramKey: "gridpowerfactor_total_meter", label: "GridPowerFactor_Total_Meter", unit: "0.01", registerType: "holding", address: 196, valueKind: "S_WORD" },
  { paramKey: "gridpowerfactor_r_meter", label: "GridPowerFactor_R_Meter", unit: "0.01", registerType: "holding", address: 197, valueKind: "S_WORD" },
  { paramKey: "gridpowerfactor_s_meter", label: "GridPowerFactor_S_Meter", unit: "0.01", registerType: "holding", address: 198, valueKind: "S_WORD" },
  { paramKey: "gridpowerfactor_t_meter", label: "GridPowerFactor_T_Meter", unit: "0.01", registerType: "holding", address: 199, valueKind: "S_WORD" },
  { paramKey: "gridfrequency_meter", label: "GridFrequency_Meter", unit: "Hz", registerType: "holding", address: 200, valueKind: "U_WORD", scale: 0.01 },
  { paramKey: "gridvoltage_total_meter", label: "GridVoltage_Total_Meter", unit: "V", registerType: "holding", address: 201, valueKind: "U_WORD", scale: 0.1 },
  { paramKey: "gridvoltage_r_meter", label: "GridVoltage_R_Meter", unit: "V", registerType: "holding", address: 202, valueKind: "U_WORD", scale: 0.1 },
  { paramKey: "gridvoltage_s_meter", label: "GridVoltage_S_Meter", unit: "V", registerType: "holding", address: 203, valueKind: "U_WORD", scale: 0.1 },
  { paramKey: "gridvoltage_t_meter", label: "GridVoltage_T_Meter", unit: "V", registerType: "holding", address: 204, valueKind: "U_WORD", scale: 0.1 },
  { paramKey: "gridcurrent_total_meter", label: "GridCurrent_Total_Meter", unit: "A", registerType: "holding", address: 205, valueKind: "S_WORD", scale: 0.1 },
  { paramKey: "gridcurrent_r_meter", label: "GridCurrent_R_Meter", unit: "A", registerType: "holding", address: 206, valueKind: "S_WORD", scale: 0.1 },
  { paramKey: "gridcurrent_s_meter", label: "GridCurrent_S_Meter", unit: "A", registerType: "holding", address: 207, valueKind: "S_WORD", scale: 0.1 },
  { paramKey: "gridcurrent_t_meter", label: "GridCurrent_T_Meter", unit: "A", registerType: "holding", address: 208, valueKind: "S_WORD", scale: 0.1 },
  { paramKey: "targetfinishflag", label: "0:unfinished 1:finish", registerType: "holding", address: 257, valueKind: "U_WORD" },
  { paramKey: "time_of_duration", label: "Time_of_Duration", unit: "s", registerType: "holding", address: 282, valueKind: "U_WORD" },
  { paramKey: "wbatteryforcechargeflag", label: "0:No Action 1:Force Charge", unit: "1", registerType: "holding", address: 287, valueKind: "U_WORD" },
  { paramKey: "wbmsrelaystate", label: "0:OFF 1:ON", unit: "1", registerType: "holding", address: 288, valueKind: "U_WORD" },
  { paramKey: "systeminvnum", label: "SystemInvNum", unit: "1", registerType: "holding", address: 477, valueKind: "U_WORD" },
  { paramKey: "rev_6", label: "Rev", unit: "1", registerType: "holding", address: 478, valueKind: "U_WORD" },
  { paramKey: "rev_7", label: "Rev", unit: "1", registerType: "holding", address: 479, valueKind: "U_WORD" },
  { paramKey: "rev_8", label: "Rev", registerType: "holding", address: 514, valueKind: "U_WORD" },
  { paramKey: "rev_9", label: "Rev", registerType: "holding", address: 515, valueKind: "U_WORD" },
  { paramKey: "unlockpassword", label: "UnlockPassword", unit: "1", registerType: "holding", address: 0, valueKind: "U_WORD" },
  { paramKey: "inverter_clear_history", label: "1 effect", unit: "1", registerType: "holding", address: 30, valueKind: "U_WORD" },
  { paramKey: "adjust_ct_zero_x3", label: "1 effect", unit: "1", registerType: "holding", address: 52, valueKind: "U_WORD" },
  { paramKey: "epsphaseseqdetect", label: "0:disable 1:enable", unit: "1", registerType: "holding", address: 56, valueKind: "U_WORD" },
  { paramKey: "ageingmode", label: "1:Enable 0:Disable", unit: "1", registerType: "holding", address: 70, valueKind: "U_WORD" },
  { paramKey: "enablemppt", label: "1:Enable 0:Disable", unit: "1", registerType: "holding", address: 72, valueKind: "U_WORD" },
  { paramKey: "reset_mgr_ee", label: "1:Reset normal configuration.", unit: "1", registerType: "holding", address: 95, valueKind: "U_WORD" },
  { paramKey: "reseterrorlog", label: "Write 1 effcet", registerType: "holding", address: 219, valueKind: "U_WORD" },
  { paramKey: "resetinvenergy", label: "Write 1 effcet", registerType: "holding", address: 220, valueKind: "U_WORD" },
];
