import type { DriverRegister } from '../driverStore.js';

export const solisRegisters: DriverRegister[] = [
  { paramKey: 'ac_output_type', label: 'AC output type', registerType: 'read', address: 3003, valueKind: 'U_WORD' },
  { paramKey: 'dc_input_type', label: 'DC input type', registerType: 'read', address: 3004, valueKind: 'U_WORD' },
  { paramKey: 'energy_today', label: 'Energy today', registerType: 'read', address: 3015, valueKind: 'U_WORD' },
  { paramKey: 'energy_last_day', label: 'Energy last day', registerType: 'read', address: 3016, valueKind: 'U_WORD' },
  { paramKey: 'hmi_version', label: 'HMI version', registerType: 'read', address: 3021, valueKind: 'U_WORD' },
  { paramKey: 'dc_voltage_1', label: 'DC voltage 1', unit: 'V', registerType: 'read', address: 3022, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'dc_current_1', label: 'DC current 1', unit: 'A', registerType: 'read', address: 3023, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'dc_current_2', label: 'DC current 2', unit: 'A', registerType: 'read', address: 3025, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'dc_voltage_3', label: 'DC voltage 3', unit: 'V', registerType: 'read', address: 3026, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'dc_current_3', label: 'DC current 3', unit: 'A', registerType: 'read', address: 3027, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'dc_voltage_4', label: 'DC voltage 4', unit: 'V', registerType: 'read', address: 3028, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'dc_current_4', label: 'DC current 4', unit: 'A', registerType: 'read', address: 3029, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'alarm_code_data', label: 'Alarm code data', registerType: 'read', address: 3030, valueKind: 'U_WORD' },
  { paramKey: 'a_phase_current', label: 'A phase current', unit: 'A', registerType: 'read', address: 3037, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'b_phase_current', label: 'B phase current', unit: 'A', registerType: 'read', address: 3038, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'c_phase_current', label: 'C phase current', unit: 'A', registerType: 'read', address: 3039, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'working_mode', label: 'Working Mode', registerType: 'read', address: 3041, valueKind: 'U_WORD' },
  { paramKey: 'grid_frequency', label: 'Grid Frequency', unit: 'Hz', registerType: 'read', address: 3043, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'inverter_status', label: 'Inverter status', registerType: 'read', address: 3044, valueKind: 'U_WORD' },
  { paramKey: 'power_curve_code', label: 'Power curve code', registerType: 'read', address: 3055, valueKind: 'U_WORD' },
  { paramKey: 'inverter_sn_1', label: 'Inverter SN_1', registerType: 'read', address: 3061, valueKind: 'U_WORD' },
  { paramKey: 'inverter_sn_2', label: 'Inverter SN_2', registerType: 'read', address: 3062, valueKind: 'U_WORD' },
  { paramKey: 'inverter_sn_3', label: 'Inverter SN_3', registerType: 'read', address: 3063, valueKind: 'U_WORD' },
  { paramKey: 'setting_flag', label: 'Setting Flag', registerType: 'read', address: 3066, valueKind: 'U_WORD' },
  { paramKey: 'fault_code_02', label: 'Fault code 02', registerType: 'read', address: 3068, valueKind: 'U_WORD' },
  { paramKey: 'fault_code_04', label: 'Fault code 04', registerType: 'read', address: 3070, valueKind: 'U_WORD' },
  { paramKey: 'fault_code_05', label: 'Fault code 05', registerType: 'read', address: 3071, valueKind: 'U_WORD' },
  { paramKey: 'working_status', label: 'Working status', registerType: 'read', address: 3072, valueKind: 'U_WORD' },
  { paramKey: 'system_time_day', label: 'System Time(day)', registerType: 'read', address: 3075, valueKind: 'U_WORD' },
  { paramKey: 'system_time_sec', label: 'System Time(sec)', registerType: 'read', address: 3078, valueKind: 'U_WORD' },
  { paramKey: 'meter_v_oltage', label: 'Meter V oltage', registerType: 'read', address: 3082, valueKind: 'U_WORD' },
  { paramKey: 'meter_current', label: 'Meter Current', registerType: 'read', address: 3083, valueKind: 'U_WORD' },
  { paramKey: 'fault_word_00', label: 'Fault Word 00', registerType: 'read', address: 3095, valueKind: 'U_WORD' },
  { paramKey: 'batch_upgrade_flag', label: 'Batch upgrade flag', registerType: 'read', address: 3220, valueKind: 'U_WORD' },
  { paramKey: 'param', label: '保留', registerType: 'read', address: 3222, valueKind: 'U_WORD' },
  { paramKey: 'param_2', label: '保留', registerType: 'read', address: 3223, valueKind: 'U_WORD' },
  { paramKey: 'param_3', label: '保留', registerType: 'read', address: 3224, valueKind: 'U_WORD' },
  { paramKey: 'param_4', label: '保留', registerType: 'read', address: 3225, valueKind: 'U_WORD' },
  { paramKey: 'param_5', label: '保留', registerType: 'read', address: 3226, valueKind: 'U_WORD' },
  { paramKey: 'param_6', label: '保留', registerType: 'read', address: 3227, valueKind: 'U_WORD' },
  { paramKey: 'meter_ac_i_a', label: 'Meter AC I A', unit: 'A', registerType: 'read', address: 3252, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'meter_ac_v_b', label: 'Meter AC V B', registerType: 'read', address: 3253, valueKind: 'U_WORD' },
  { paramKey: 'meter_ac_i_b', label: 'Meter AC I B', unit: 'A', registerType: 'read', address: 3254, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'meter_ac_v_c', label: 'Meter AC V C', unit: 'V', registerType: 'read', address: 3255, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'meter_ac_i_c', label: 'Meter AC I C', unit: 'A', registerType: 'read', address: 3256, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'meter_p_a', label: 'Meter P A', unit: 'kW', registerType: 'read', address: 3257, valueKind: 'S_DWORD', scale: 0.001 },
  { paramKey: 'meter_p_b', label: 'Meter P B', unit: 'kW', registerType: 'read', address: 3259, valueKind: 'S_DWORD', scale: 0.001 },
  { paramKey: 'meter_p_c', label: 'Meter P C', unit: 'kW', registerType: 'read', address: 3261, valueKind: 'S_DWORD', scale: 0.001 },
  { paramKey: 'meter_total_p', label: 'Meter Total P', unit: 'kW', registerType: 'read', address: 3263, valueKind: 'S_DWORD', scale: 0.001 },
  { paramKey: 'meter_q_a', label: 'Meter Q A', unit: 'Var', registerType: 'read', address: 3265, valueKind: 'S_DWORD', scale: 1.0 },
  { paramKey: 'meter_q_b', label: 'Meter Q B', unit: 'Var', registerType: 'read', address: 3267, valueKind: 'S_DWORD', scale: 1.0 },
  { paramKey: 'meter_q_c', label: 'Meter Q C', unit: 'Var', registerType: 'read', address: 3269, valueKind: 'S_DWORD', scale: 1.0 },
  { paramKey: 'meter_total_q', label: 'Meter Total Q', unit: 'Var', registerType: 'read', address: 3271, valueKind: 'S_DWORD', scale: 1.0 },
  { paramKey: 'meter_s_a', label: 'Meter S A', registerType: 'read', address: 3273, valueKind: 'S_DWORD' },
  { paramKey: 'meter_s_b', label: 'Meter S B', registerType: 'read', address: 3275, valueKind: 'S_DWORD' },
  { paramKey: 'meter_s_c', label: 'Meter S C', registerType: 'read', address: 3277, valueKind: 'S_DWORD' },
  { paramKey: 'meter_total_s', label: 'Meter Total S', registerType: 'read', address: 3279, valueKind: 'S_DWORD' },
  { paramKey: 'meter_pf', label: 'Meter PF', registerType: 'read', address: 3281, valueKind: 'S_WORD' },
  { paramKey: 'pv22i', label: 'PV22I', unit: 'A', registerType: 'read', address: 3290, valueKind: 'S_WORD', scale: 0.1 },
  { paramKey: 'pv24i', label: 'PV24I', unit: 'A', registerType: 'read', address: 3292, valueKind: 'S_WORD', scale: 0.1 },
  { paramKey: 'pv25i', label: 'PV25I', unit: 'A', registerType: 'read', address: 3293, valueKind: 'S_WORD', scale: 0.1 },
  { paramKey: 'total_pv_i', label: 'Total PV I', unit: 'A', registerType: 'read', address: 3300, valueKind: 'S_WORD', scale: 0.1 },
  { paramKey: 'pv1_i', label: 'PV1 I', unit: 'A', registerType: 'read', address: 3301, valueKind: 'S_WORD', scale: 0.1 },
  { paramKey: 'pv2_i', label: 'PV2 I', unit: 'A', registerType: 'read', address: 3302, valueKind: 'S_WORD', scale: 0.1 },
  { paramKey: 'pv3_i', label: 'PV3 I', unit: 'A', registerType: 'read', address: 3303, valueKind: 'S_WORD', scale: 0.1 },
  { paramKey: 'pv4_i', label: 'PV4 I', unit: 'A', registerType: 'read', address: 3304, valueKind: 'S_WORD', scale: 0.1 },
  { paramKey: 'pv5_i', label: 'PV5 I', unit: 'A', registerType: 'read', address: 3305, valueKind: 'S_WORD', scale: 0.1 },
  { paramKey: 'pv6_i', label: 'PV6 I', unit: 'A', registerType: 'read', address: 3306, valueKind: 'S_WORD', scale: 0.1 },
  { paramKey: 'pv7_i', label: 'PV7 I', unit: 'A', registerType: 'read', address: 3307, valueKind: 'S_WORD', scale: 0.1 },
  { paramKey: 'pv8_i', label: 'PV8 I', unit: 'A', registerType: 'read', address: 3308, valueKind: 'S_WORD', scale: 0.1 },
  { paramKey: 'pv9_i', label: 'PV9 I', unit: 'A', registerType: 'read', address: 3309, valueKind: 'S_WORD', scale: 0.1 },
  { paramKey: 'pv10_i', label: 'PV10 I', unit: 'A', registerType: 'read', address: 3310, valueKind: 'S_WORD', scale: 0.1 },
  { paramKey: 'pv11_i', label: 'PV11 I', unit: 'A', registerType: 'read', address: 3311, valueKind: 'S_WORD', scale: 0.1 },
  { paramKey: 'pv12_i', label: 'PV12 I', unit: 'A', registerType: 'read', address: 3312, valueKind: 'S_WORD', scale: 0.1 },
  { paramKey: 'pv13_i', label: 'PV13 I', unit: 'A', registerType: 'read', address: 3313, valueKind: 'S_WORD', scale: 0.1 },
  { paramKey: 'pv14_i', label: 'PV14 I', unit: 'A', registerType: 'read', address: 3314, valueKind: 'S_WORD', scale: 0.1 },
  { paramKey: 'pv15_i', label: 'PV15 I', unit: 'A', registerType: 'read', address: 3315, valueKind: 'S_WORD', scale: 0.1 },
  { paramKey: 'pv16_i', label: 'PV16 I', unit: 'A', registerType: 'read', address: 3316, valueKind: 'S_WORD', scale: 0.1 },
  { paramKey: 'pv17_i', label: 'PV17 I', unit: 'A', registerType: 'read', address: 3317, valueKind: 'S_WORD', scale: 0.1 },
  { paramKey: 'pv18_i', label: 'PV18 I', unit: 'A', registerType: 'read', address: 3318, valueKind: 'S_WORD', scale: 0.1 },
  { paramKey: 'pv19_i', label: 'PV19 I', unit: 'A', registerType: 'read', address: 3319, valueKind: 'S_WORD', scale: 0.1 },
  { paramKey: 'pv20_i', label: 'PV20 I', unit: 'A', registerType: 'read', address: 3320, valueKind: 'S_WORD', scale: 0.1 },
  { paramKey: 'pv1_v', label: 'PV1 V', registerType: 'read', address: 3321, valueKind: 'U_WORD' },
  { paramKey: 'pv2_v', label: 'PV2 V', unit: 'V', registerType: 'read', address: 3322, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'pv3_v', label: 'PV3 V', unit: 'V', registerType: 'read', address: 3323, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'pv4_v', label: 'PV4 V', unit: 'V', registerType: 'read', address: 3324, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'pv5_v', label: 'PV5 V', unit: 'V', registerType: 'read', address: 3325, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'pv6_v', label: 'PV6 V', unit: 'V', registerType: 'read', address: 3326, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'pv7_v', label: 'PV7 V', unit: 'V', registerType: 'read', address: 3327, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'pv8_v', label: 'PV8 V', unit: 'V', registerType: 'read', address: 3328, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'pv9_v', label: 'PV9 V', unit: 'V', registerType: 'read', address: 3329, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'pv10_v', label: 'PV10 V', unit: 'V', registerType: 'read', address: 3330, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'pvv1', label: 'PVV1', unit: 'V', registerType: 'read', address: 3343, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'pvi1', label: 'PVI1', unit: 'A', registerType: 'read', address: 3344, valueKind: 'S_WORD', scale: 0.1 },
  { paramKey: 'pvv2', label: 'PVV2', unit: 'V', registerType: 'read', address: 3345, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'pvi2', label: 'PVI2', unit: 'A', registerType: 'read', address: 3346, valueKind: 'S_WORD', scale: 0.1 },
  { paramKey: 'pvi3', label: 'PVI3', unit: 'A', registerType: 'read', address: 3348, valueKind: 'S_WORD', scale: 0.1 },
  { paramKey: 'pvv4', label: 'PVV4', unit: 'V', registerType: 'read', address: 3349, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'pvi4', label: 'PVI4', unit: 'A', registerType: 'read', address: 3350, valueKind: 'S_WORD', scale: 0.1 },
  { paramKey: 'pvv5', label: 'PVV5', unit: 'V', registerType: 'read', address: 3351, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'pvi5', label: 'PVI5', unit: 'A', registerType: 'read', address: 3352, valueKind: 'S_WORD', scale: 0.1 },
  { paramKey: 'pvv60', label: 'PVV60', unit: 'V', registerType: 'read', address: 3461, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'mppt_1v', label: 'MPPT 1V', unit: 'V', registerType: 'read', address: 3500, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'mppt_2v', label: 'MPPT 2V', unit: 'V', registerType: 'read', address: 3501, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'mppt_3v', label: 'MPPT 3V', unit: 'V', registerType: 'read', address: 3502, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'mppt_4v', label: 'MPPT 4V', unit: 'V', registerType: 'read', address: 3503, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'mppt_5v', label: 'MPPT 5V', unit: 'V', registerType: 'read', address: 3504, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'mppt_6v', label: 'MPPT 6V', unit: 'V', registerType: 'read', address: 3505, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'mppt_7v', label: 'MPPT 7V', unit: 'V', registerType: 'read', address: 3506, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'mppt_8v', label: 'MPPT 8V', unit: 'V', registerType: 'read', address: 3507, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'mppt_9v', label: 'MPPT 9V', unit: 'V', registerType: 'read', address: 3508, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'mppt_10v', label: 'MPPT 10V', unit: 'V', registerType: 'read', address: 3509, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'mppt_11v', label: 'MPPT 11V', unit: 'V', registerType: 'read', address: 3510, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'mppt_12v', label: 'MPPT 12V', unit: 'V', registerType: 'read', address: 3511, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'mppt_14v', label: 'MPPT 14V', unit: 'V', registerType: 'read', address: 3513, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'mppt_15v', label: 'MPPT 15V', unit: 'V', registerType: 'read', address: 3514, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'mppt_1i', label: 'MPPT 1I', unit: 'A', registerType: 'read', address: 3530, valueKind: 'S_WORD', scale: 0.1 },
  { paramKey: 'mppt_2i', label: 'MPPT 2I', unit: 'A', registerType: 'read', address: 3531, valueKind: 'S_WORD', scale: 0.1 },
  { paramKey: 'mppt_3i', label: 'MPPT 3I', unit: 'A', registerType: 'read', address: 3532, valueKind: 'S_WORD', scale: 0.1 },
  { paramKey: 'mppt_4i', label: 'MPPT 4I', unit: 'A', registerType: 'read', address: 3533, valueKind: 'S_WORD', scale: 0.1 },
  { paramKey: 'mppt_5i', label: 'MPPT 5I', unit: 'A', registerType: 'read', address: 3534, valueKind: 'S_WORD', scale: 0.1 },
  { paramKey: 'mppt_6i', label: 'MPPT 6I', unit: 'A', registerType: 'read', address: 3535, valueKind: 'S_WORD', scale: 0.1 },
  { paramKey: 'mppt_7i', label: 'MPPT 7I', unit: 'A', registerType: 'read', address: 3536, valueKind: 'S_WORD', scale: 0.1 },
  { paramKey: 'mppt_8i', label: 'MPPT 8I', unit: 'A', registerType: 'read', address: 3537, valueKind: 'S_WORD', scale: 0.1 },
  { paramKey: 'mppt_10i', label: 'MPPT 10I', unit: 'A', registerType: 'read', address: 3539, valueKind: 'S_WORD', scale: 0.1 },
  { paramKey: 'mppt_11i', label: 'MPPT 11I', unit: 'A', registerType: 'read', address: 3540, valueKind: 'S_WORD', scale: 0.1 },
  { paramKey: 'mppt_12i', label: 'MPPT 12I', unit: 'A', registerType: 'read', address: 3541, valueKind: 'S_WORD', scale: 0.1 },
  { paramKey: 'mppt_13i', label: 'MPPT 13I', unit: 'A', registerType: 'read', address: 3542, valueKind: 'S_WORD', scale: 0.1 },
  { paramKey: 'mppt_14i', label: 'MPPT 14I', unit: 'A', registerType: 'read', address: 3543, valueKind: 'S_WORD', scale: 0.1 },
  { paramKey: 'mppt_15i', label: 'MPPT 15I', unit: 'A', registerType: 'read', address: 3544, valueKind: 'S_WORD', scale: 0.1 },
  { paramKey: 'dc_bus_voltage', label: 'DC bus voltage', unit: 'V', registerType: 'read', address: 5002, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'ct_ratio', label: 'CT ratio', registerType: 'read', address: 36016, valueKind: 'U_WORD' },
  { paramKey: 'year', label: 'Year', registerType: 'read', address: 36019, valueKind: 'U_WORD' },
  { paramKey: 'month', label: 'Month', registerType: 'read', address: 36020, valueKind: 'U_WORD' },
  { paramKey: 'day', label: 'Day', registerType: 'read', address: 36021, valueKind: 'U_WORD' },
  { paramKey: 'batch_upgrade_flag_2', label: 'Batch upgrade flag', registerType: 'read', address: 36059, valueKind: 'U_WORD' },
  { paramKey: 'month_2', label: 'Month', registerType: 'holding', address: 3001, valueKind: 'U_WORD' },
  { paramKey: 'day_2', label: 'Day', registerType: 'holding', address: 3002, valueKind: 'U_WORD' },
  { paramKey: 'hours', label: 'Hours', registerType: 'holding', address: 3003, valueKind: 'U_WORD' },
  { paramKey: 'mins', label: 'Mins', registerType: 'holding', address: 3004, valueKind: 'U_WORD' },
  { paramKey: 'seconds', label: 'Seconds', registerType: 'holding', address: 3005, valueKind: 'U_WORD' },
  { paramKey: 'on_off', label: 'ON/OFF', registerType: 'holding', address: 3007, valueKind: 'U_WORD' },
  { paramKey: '81_s1', label: '81>S1', registerType: 'holding', address: 3010, valueKind: 'U_WORD' },
  { paramKey: '81_s1_2', label: '81<S1', registerType: 'holding', address: 3012, valueKind: 'U_WORD' },
  { paramKey: '81_s2f', label: '81>S2F', registerType: 'holding', address: 3014, valueKind: 'U_WORD' },
  { paramKey: 'pf_setting', label: 'PF Setting', registerType: 'holding', address: 3053, valueKind: 'S_WORD' },
  { paramKey: 'startup_time', label: 'Startup time', registerType: 'holding', address: 3106, valueKind: 'U_WORD' },
  { paramKey: 'recover_f', label: 'Recover F', registerType: 'holding', address: 3111, valueKind: 'U_WORD' },
  { paramKey: 'month_3', label: 'Month', registerType: 'holding', address: 36501, valueKind: 'U_WORD' },
  { paramKey: 'day_3', label: 'Day', registerType: 'holding', address: 36502, valueKind: 'U_WORD' },
  { paramKey: 'hours_2', label: 'Hours', registerType: 'holding', address: 36503, valueKind: 'U_WORD' },
  { paramKey: 'slave_address', label: 'Slave Address', registerType: 'holding', address: 36506, valueKind: 'U_WORD' },
  { paramKey: 'ct_ratio_2', label: 'CT ratio', registerType: 'holding', address: 36507, valueKind: 'U_WORD' },
  { paramKey: 'inverter_number', label: 'Inverter number', registerType: 'holding', address: 36509, valueKind: 'U_WORD' },
  { paramKey: 'epm_mode', label: 'EPM mode', registerType: 'holding', address: 36510, valueKind: 'U_WORD' },
];
