import type { DriverRegister } from '../driverStore.js';

export const sungrowRegisters: DriverRegister[] = [
  { paramKey: 'sn', label: 'SN', registerType: 'read', address: 4989, valueKind: 'STRING', stringLengthWords: 10 },
  { paramKey: 'device_type_code', label: 'Device type code', unit: 'A', registerType: 'read', address: 4999, valueKind: 'U_WORD' },
  { paramKey: 'output_type', label: 'Output type', registerType: 'read', address: 5001, valueKind: 'U_WORD' },
  { paramKey: 'daily_power_yields', label: 'Daily power yields', unit: 'kWh', registerType: 'read', address: 5002, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'total_power_yields', label: 'Total power yields', unit: 'kWh', registerType: 'read', address: 5003, valueKind: 'U_DWORD' },
  { paramKey: 'total_running_time', label: 'Total running time', unit: 'h', registerType: 'read', address: 5005, valueKind: 'U_DWORD' },
  { paramKey: 'internal_temperature', label: 'Internal temperature', unit: '°C', registerType: 'read', address: 5007, valueKind: 'S_WORD', scale: 0.1 },
  { paramKey: 'mppt_1_voltage', label: 'MPPT 1 voltage', unit: 'V', registerType: 'read', address: 5010, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'mppt_1_current', label: 'MPPT 1 current', unit: 'A', registerType: 'read', address: 5011, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'mppt_2_voltage', label: 'MPPT 2 voltage', unit: 'V', registerType: 'read', address: 5012, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'mppt_2_current', label: 'MPPT 2 current', unit: 'A', registerType: 'read', address: 5013, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'mppt_3_voltage', label: 'MPPT 3 voltage', unit: 'V', registerType: 'read', address: 5014, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'mppt_3_current', label: 'MPPT 3 current', unit: 'A', registerType: 'read', address: 5015, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'total_dc_power', label: 'Total DC power', unit: 'W', registerType: 'read', address: 5016, valueKind: 'U_DWORD' },
  { paramKey: 'phase_a_current', label: 'Phase A current', unit: 'A', registerType: 'read', address: 5021, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'phase_b_current', label: 'Phase B current', unit: 'A', registerType: 'read', address: 5022, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'phase_c_current', label: 'Phase C current', unit: 'A', registerType: 'read', address: 5023, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'total_active_power', label: 'Total active power', unit: 'W', registerType: 'read', address: 5030, valueKind: 'U_DWORD' },
  { paramKey: 'total_reactive_power', label: 'Total reactive power', unit: 'Var', registerType: 'read', address: 5032, valueKind: 'S_DWORD' },
  { paramKey: 'power_factor', label: 'Power factor', registerType: 'read', address: 5034, valueKind: 'S_WORD', scale: 0.001 },
  { paramKey: 'grid_frequency', label: 'Grid frequency', unit: 'Hz', registerType: 'read', address: 5035, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'work_state', label: 'Work state', unit: 'A', registerType: 'read', address: 5080, valueKind: 'U_DWORD' },
  { paramKey: 'meter_power', label: 'Meter power', registerType: 'read', address: 5082, valueKind: 'S_DWORD' },
  { paramKey: 'load_power', label: 'Load power', registerType: 'read', address: 5090, valueKind: 'S_DWORD' },
  { paramKey: 'daily_export_energy', label: 'Daily export energy', unit: 'kWh', registerType: 'read', address: 5092, valueKind: 'U_DWORD', scale: 0.1 },
  { paramKey: 'total_export_energy', label: 'Total export energy', unit: 'kWh', registerType: 'read', address: 5094, valueKind: 'U_DWORD', scale: 0.1 },
  { paramKey: 'daily_import_energy', label: 'Daily import energy', unit: 'kWh', registerType: 'read', address: 5096, valueKind: 'U_DWORD', scale: 0.1 },
  { paramKey: 'total_import_energy', label: 'Total import energy', unit: 'kWh', registerType: 'read', address: 5098, valueKind: 'U_DWORD', scale: 0.1 },
  { paramKey: 'daily_running_time', label: 'Daily running time', registerType: 'read', address: 5112, valueKind: 'U_WORD' },
  { paramKey: 'present_country', label: 'Present country', unit: 'A', registerType: 'read', address: 5113, valueKind: 'U_WORD' },
  { paramKey: 'mppt_4_voltage', label: 'MPPT 4 voltage', unit: 'V', registerType: 'read', address: 5114, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'mppt_4_current', label: 'MPPT 4 current', unit: 'A', registerType: 'read', address: 5115, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'mppt_5_voltage', label: 'MPPT 5 voltage', unit: 'V', registerType: 'read', address: 5116, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'mppt_5_current', label: 'MPPT 5 current', unit: 'A', registerType: 'read', address: 5117, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'mppt_6_voltage', label: 'MPPT 6 voltage', unit: 'V', registerType: 'read', address: 5118, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'mppt_6_current', label: 'MPPT 6 current', unit: 'A', registerType: 'read', address: 5119, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'mppt_7_voltage', label: 'MPPT 7 voltage', unit: 'V', registerType: 'read', address: 5120, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'mppt_7_current', label: 'MPPT 7 current', unit: 'A', registerType: 'read', address: 5121, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'mppt_8_voltage', label: 'MPPT 8 voltage', unit: 'V', registerType: 'read', address: 5122, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'mppt_8_current', label: 'MPPT 8 current', unit: 'A', registerType: 'read', address: 5123, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'mppt_9_voltage', label: 'MPPT 9 voltage', unit: 'V', registerType: 'read', address: 5129, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'mppt_9_current', label: 'MPPT 9 current', unit: 'A', registerType: 'read', address: 5130, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'mppt_10_voltage', label: 'MPPT 10 voltage', unit: 'V', registerType: 'read', address: 5131, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'mppt_10_current', label: 'MPPT 10 current', unit: 'A', registerType: 'read', address: 5132, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'mppt_11_voltage', label: 'MPPT 11 voltage', unit: 'V', registerType: 'read', address: 5133, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'mppt_11_current', label: 'MPPT 11 current', unit: 'A', registerType: 'read', address: 5134, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'mppt_12_voltage', label: 'MPPT 12 voltage', unit: 'V', registerType: 'read', address: 5135, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'mppt_12_current', label: 'MPPT 12 current', unit: 'A', registerType: 'read', address: 5136, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'total_power_yields_2', label: 'Total power yields', unit: 'kWh', registerType: 'read', address: 5143, valueKind: 'U_DWORD', scale: 0.1 },
  { paramKey: 'bus_voltage', label: 'Bus voltage', unit: 'V', registerType: 'read', address: 5146, valueKind: 'U_WORD', scale: 0.1 },
  { paramKey: 'grid_frequency_2', label: 'Grid frequency', unit: 'Hz', registerType: 'read', address: 5147, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'pid_work_state', label: 'PID work state', registerType: 'read', address: 5149, valueKind: 'U_WORD' },
  { paramKey: 'pid_alarm_code', label: 'PID alarm code', registerType: 'read', address: 5150, valueKind: 'U_WORD' },
  { paramKey: 'string_1_current', label: 'String 1 current', unit: 'A', registerType: 'read', address: 7012, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'string_2_current', label: 'String 2 current', unit: 'A', registerType: 'read', address: 7013, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'string_3_current', label: 'String 3 current', unit: 'A', registerType: 'read', address: 7014, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'string_4_current', label: 'String 4 current', unit: 'A', registerType: 'read', address: 7015, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'string_5_current', label: 'String 5 current', unit: 'A', registerType: 'read', address: 7016, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'string_6_current', label: 'String 6 current', unit: 'A', registerType: 'read', address: 7017, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'string_7_current', label: 'String 7 current', unit: 'A', registerType: 'read', address: 7018, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'string_8_current', label: 'String 8 current', unit: 'A', registerType: 'read', address: 7019, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'string_9_current', label: 'String 9 current', unit: 'A', registerType: 'read', address: 7020, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'string_10_current', label: 'String 10 current', unit: 'A', registerType: 'read', address: 7021, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'string_11_current', label: 'String 11 current', unit: 'A', registerType: 'read', address: 7022, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'string_12_current', label: 'String 12 current', unit: 'A', registerType: 'read', address: 7023, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'string_13_current', label: 'String 13 current', unit: 'A', registerType: 'read', address: 7024, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'string_14_current', label: 'String 14 current', unit: 'A', registerType: 'read', address: 7025, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'string_15_current', label: 'String 15 current', unit: 'A', registerType: 'read', address: 7026, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'string_16_current', label: 'String 16 current', unit: 'A', registerType: 'read', address: 7027, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'string_17_current', label: 'String 17 current', unit: 'A', registerType: 'read', address: 7028, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'string_18_current', label: 'String 18 current', unit: 'A', registerType: 'read', address: 7029, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'string_19_current', label: 'String 19 current', unit: 'A', registerType: 'read', address: 7030, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'string_20_current', label: 'String 20 current', unit: 'A', registerType: 'read', address: 7031, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'string_21_current', label: 'String 21 current', unit: 'A', registerType: 'read', address: 7032, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'string_22_current', label: 'String 22 current', unit: 'A', registerType: 'read', address: 7033, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'string_23_current', label: 'String 23 current', unit: 'A', registerType: 'read', address: 7034, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'string_24_current', label: 'String 24 current', unit: 'A', registerType: 'read', address: 7035, valueKind: 'U_WORD', scale: 0.01 },
  { paramKey: 'start_stop', label: 'Start/Stop', registerType: 'read', address: 5005, valueKind: 'U_WORD' },
  { paramKey: 'pid_recovery', label: 'PID Recovery', registerType: 'read', address: 5040, valueKind: 'U_WORD' },
  { paramKey: 'anti_pid', label: 'Anti-PID', registerType: 'read', address: 5041, valueKind: 'U_WORD' },
];
