import type { DriverRegister } from '../driverStore.js';

export const wm15Registers: DriverRegister[] = [
  { paramKey: "v_l1_n", label: "V L1-N", unit: "V", registerType: "read", address: 0, valueKind: "S_DWORD" },
  { paramKey: "v_l2_n", label: "V L2-N", unit: "V", registerType: "read", address: 2, valueKind: "S_DWORD" },
  { paramKey: "v_l3_n", label: "V L3-N", unit: "V", registerType: "read", address: 4, valueKind: "S_DWORD" },
  { paramKey: "v_l1_l2", label: "V L1-L2", unit: "V", registerType: "read", address: 6, valueKind: "S_DWORD" },
  { paramKey: "v_l2_l3", label: "V L2-L3", unit: "V", registerType: "read", address: 8, valueKind: "S_DWORD" },
  { paramKey: "v_l3_l1", label: "V L3-L1", unit: "V", registerType: "read", address: 10, valueKind: "S_DWORD" },
  { paramKey: "a_l1", label: "A L1", unit: "A", registerType: "read", address: 12, valueKind: "S_DWORD" },
  { paramKey: "a_l3", label: "A L3", unit: "A", registerType: "read", address: 16, valueKind: "S_DWORD" },
  { paramKey: "w_l1", label: "W L1", unit: "W", registerType: "read", address: 18, valueKind: "S_DWORD" },
  { paramKey: "w_l3", label: "W L3", unit: "W", registerType: "read", address: 22, valueKind: "S_DWORD" },
  { paramKey: "va_l1", label: "VA L1", unit: "VA", registerType: "read", address: 24, valueKind: "S_DWORD" },
  { paramKey: "va_l3", label: "VA L3", unit: "VA", registerType: "read", address: 28, valueKind: "S_DWORD" },
  { paramKey: "var_l1", label: "var L1", unit: "var", registerType: "read", address: 30, valueKind: "S_DWORD" },
  { paramKey: "var_l3", label: "var L3", unit: "var", registerType: "read", address: 34, valueKind: "S_DWORD" },
  { paramKey: "v_l_n_sys", label: "V L-N sys", unit: "V", registerType: "read", address: 36, valueKind: "S_DWORD" },
  { paramKey: "w_sys", label: "W sys", unit: "W", registerType: "read", address: 40, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "va_sys", label: "VA sys", unit: "VA", registerType: "read", address: 42, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "var_sys", label: "var sys", unit: "var", registerType: "read", address: 44, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "pf_l1_for_l_c_refer_to_0076h", label: "PF L1* (for L/C refer to 0076h)", registerType: "read", address: 46, valueKind: "S_WORD" },
  { paramKey: "pf_l2_for_l_c_refer_to_0077h", label: "PF L2* (for L/C refer to 0077h)", registerType: "read", address: 47, valueKind: "S_WORD" },
  { paramKey: "pf_l3_for_l_c_refer_to_0078h", label: "PF L3* (for L/C refer to 0078h)", registerType: "read", address: 48, valueKind: "S_WORD" },
  { paramKey: "pf_sys_for_l_c_refer_to_0078h", label: "PF sys* (for L/C refer to 0078h)", registerType: "read", address: 49, valueKind: "S_WORD" },
  { paramKey: "phase_sequence", label: "Phase sequence", registerType: "read", address: 50, valueKind: "S_WORD" },
  { paramKey: "hz", label: "Hz", unit: "Hz", registerType: "read", address: 51, valueKind: "S_WORD", scale: 0.1, precision: 1 },
  { paramKey: "kwh_tot", label: "kWh (+) TOT", unit: "kWh", registerType: "read", address: 52, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "kvarh_tot", label: "Kvarh (+) TOT", unit: "kvarh", registerType: "read", address: 54, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "w_sys_dmd", label: "W sys DMD", unit: "W", registerType: "read", address: 56, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "w_sys_dmd_max", label: "W sys DMD MAX", unit: "W", registerType: "read", address: 58, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "kwh_partial", label: "kWh (+) PARTIAL", unit: "kWh", registerType: "read", address: 60, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "kvarh_partial", label: "Kvarh (+) PARTIAL", unit: "kvarh", registerType: "read", address: 62, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "kwh_l1", label: "kWh (+) L1", unit: "kWh", registerType: "read", address: 64, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "kwh_l2", label: "kWh (+) L2", unit: "kWh", registerType: "read", address: 66, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "kwh_l3", label: "kWh (+) L3", unit: "kWh", registerType: "read", address: 68, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "n_a", label: "n.a.", unit: "A", registerType: "read", address: 70, valueKind: "S_DWORD" },
  { paramKey: "n_a_2", label: "n.a.", unit: "A", registerType: "read", address: 72, valueKind: "S_DWORD" },
  { paramKey: "n_a_3", label: "n.a.", unit: "A", registerType: "read", address: 74, valueKind: "S_DWORD" },
  { paramKey: "n_a_4", label: "n.a.", unit: "A", registerType: "read", address: 76, valueKind: "S_DWORD" },
  { paramKey: "kwh_tot_2", label: "kWh (-) TOT", unit: "kWh", registerType: "read", address: 78, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "kvarh_tot_2", label: "kvarh (-) TOT", unit: "kvarh", registerType: "read", address: 80, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "kwh_partial_2", label: "kWh (-) PARTIAL", unit: "kWh", registerType: "read", address: 82, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "kvarh_partial_2", label: "Kvarh (-) PARTIAL", unit: "kvarh", registerType: "read", address: 84, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "kvah_tot", label: "kVAh TOT", unit: "kVAh", registerType: "read", address: 86, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "kvah_partial", label: "kVAh PARTIAL", unit: "kVAh", registerType: "read", address: 88, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "run_hour_meter", label: "Run hour meter", unit: "h", registerType: "read", address: 90, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "run_hour_meter_kwh", label: "Run hour meter kWh (-)", unit: "h", registerType: "read", address: 92, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "n_a_5", label: "n.a.", unit: "A", registerType: "read", address: 94, valueKind: "S_DWORD" },
  { paramKey: "n_a_6", label: "n.a.", unit: "A", registerType: "read", address: 96, valueKind: "S_DWORD" },
  { paramKey: "n_a_7", label: "n.a.", unit: "A", registerType: "read", address: 98, valueKind: "S_DWORD" },
  { paramKey: "n_a_8", label: "n.a.", unit: "A", registerType: "read", address: 100, valueKind: "S_DWORD" },
  { paramKey: "n_a_9", label: "n.a.", unit: "A", registerType: "read", address: 102, valueKind: "S_DWORD" },
  { paramKey: "n_a_10", label: "n.a.", unit: "A", registerType: "read", address: 104, valueKind: "S_DWORD" },
  { paramKey: "n_a_11", label: "n.a.", unit: "A", registerType: "read", address: 106, valueKind: "S_DWORD" },
  { paramKey: "n_a_12", label: "n.a.", unit: "A", registerType: "read", address: 108, valueKind: "S_DWORD" },
  { paramKey: "run_hour_meter_partial", label: "Run hour meter PARTIAL", unit: "h", registerType: "read", address: 110, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "run_hour_meter_kwh_partial", label: "Run hour meter kWh (-) PARTIAL", unit: "h", registerType: "read", address: 112, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "pf_l1", label: "PF L1**", registerType: "read", address: 114, valueKind: "S_WORD" },
  { paramKey: "pf_l2", label: "PF L2**", registerType: "read", address: 115, valueKind: "S_WORD" },
  { paramKey: "pf_l3", label: "PF L3**", registerType: "read", address: 116, valueKind: "S_WORD" },
  { paramKey: "pf_sys", label: "PF sys**", registerType: "read", address: 117, valueKind: "S_WORD" },
  { paramKey: "inductive_capacitive_load_phase_1", label: "Inductive/Capacitive Load phase 1", registerType: "read", address: 118, valueKind: "S_WORD" },
  { paramKey: "inductive_capacitive_load_phase_2", label: "Inductive/Capacitive Load phase 2", registerType: "read", address: 119, valueKind: "S_WORD" },
  { paramKey: "inductive_capacitive_load_phase_3", label: "Inductive/Capacitive Load phase 3", registerType: "read", address: 120, valueKind: "S_WORD" },
  { paramKey: "inductive_capacitive_load_sys", label: "Inductive/Capacitive Load sys", registerType: "read", address: 121, valueKind: "S_WORD" },
  { paramKey: "n_a_13", label: "n.a.", unit: "A", registerType: "read", address: 122, valueKind: "S_DWORD" },
  { paramKey: "n_a_14", label: "n.a.", unit: "A", registerType: "read", address: 124, valueKind: "S_DWORD" },
  { paramKey: "n_a_15", label: "n.a.", unit: "A", registerType: "read", address: 126, valueKind: "S_DWORD" },
  { paramKey: "n_a_16", label: "n.a.", unit: "A", registerType: "read", address: 128, valueKind: "S_DWORD" },
  { paramKey: "thd_a_l1", label: "THD A L1", unit: "%", registerType: "read", address: 130, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "thd_a_l2", label: "THD A L2", unit: "%", registerType: "read", address: 132, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "thd_a_l3", label: "THD A L3", unit: "%", registerType: "read", address: 134, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "n_a_17", label: "n.a.", unit: "A", registerType: "read", address: 136, valueKind: "S_DWORD" },
  { paramKey: "thd_v_l1_n", label: "THD V L1-N", unit: "%", registerType: "read", address: 138, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "thd_v_l2_n", label: "THD V L2-N", unit: "%", registerType: "read", address: 140, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "thd_v_l3_n", label: "THD V L3-N", unit: "%", registerType: "read", address: 142, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "n_a_18", label: "n.a.", unit: "A", registerType: "read", address: 144, valueKind: "S_DWORD" },
  { paramKey: "thd_v_l1_l2", label: "THD V L1-L2", unit: "%", registerType: "read", address: 146, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "thd_v_l2_l3", label: "THD V L2-L3", unit: "%", registerType: "read", address: 148, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "thd_v_l3_l1", label: "THD V L3-L1", unit: "%", registerType: "read", address: 150, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "n_a_19", label: "n.a.", unit: "A", registerType: "read", address: 152, valueKind: "S_DWORD" },
  { paramKey: "i1_dmd_value", label: "I1 DMD Value", unit: "A", registerType: "read", address: 154, valueKind: "S_DWORD", scale: 0.001, precision: 3 },
  { paramKey: "i2_dmd_value", label: "I2 DMD Value", unit: "A", registerType: "read", address: 156, valueKind: "S_DWORD", scale: 0.001, precision: 3 },
  { paramKey: "i3_dmd_value", label: "I3 DMD Value", unit: "A", registerType: "read", address: 158, valueKind: "S_DWORD", scale: 0.001, precision: 3 },
  { paramKey: "i1_dmdmax_value", label: "I1 DMDMAX Value", unit: "A", registerType: "read", address: 160, valueKind: "S_DWORD", scale: 0.001, precision: 3 },
  { paramKey: "i2_dmdmax_value", label: "I2 DMDMAX Value", unit: "A", registerType: "read", address: 162, valueKind: "S_DWORD", scale: 0.001, precision: 3 },
  { paramKey: "i3_dmdmax_value", label: "I3 DMDMAX Value", unit: "A", registerType: "read", address: 164, valueKind: "S_DWORD", scale: 0.001, precision: 3 },
  { paramKey: "i1_max_value", label: "I1 MAX Value", unit: "A", registerType: "read", address: 166, valueKind: "S_DWORD", scale: 0.001, precision: 3 },
  { paramKey: "i2_max_value", label: "I2 MAX Value", unit: "A", registerType: "read", address: 168, valueKind: "S_DWORD", scale: 0.001, precision: 3 },
  { paramKey: "i3_max_value", label: "I3 MAX Value", unit: "A", registerType: "read", address: 170, valueKind: "S_DWORD", scale: 0.001, precision: 3 },
  { paramKey: "w1_dmd_value", label: "W1 DMD Value", unit: "W", registerType: "read", address: 172, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "w2_dmd_value", label: "W2 DMD Value", unit: "W", registerType: "read", address: 174, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "w3_dmd_value", label: "W3 DMD Value", unit: "W", registerType: "read", address: 176, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "w1_dmdmax_value", label: "W1 DMDMAX Value", unit: "W", registerType: "read", address: 178, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "w2_dmdmax_value", label: "W2 DMDMAX Value", unit: "W", registerType: "read", address: 180, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "w3_dmdmax_value", label: "W3 DMDMAX Value", unit: "W", registerType: "read", address: 182, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "w1_max_value", label: "W1 MAX Value", unit: "W", registerType: "read", address: 184, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "w2_max_value", label: "W2 MAX Value", unit: "W", registerType: "read", address: 186, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "w3_max_value", label: "W3 MAX Value", unit: "W", registerType: "read", address: 188, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "w_sys_dmd_value", label: "W sys DMD Value", unit: "W", registerType: "read", address: 190, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "w_sys_dmd_max_2", label: "W sys DMD MAX", unit: "W", registerType: "read", address: 192, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "w_sys_max", label: "W sys MAX", unit: "W", registerType: "read", address: 194, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "n_a_20", label: "n.a.", unit: "A", registerType: "read", address: 196, valueKind: "S_DWORD" },
  { paramKey: "n_a_21", label: "n.a.", unit: "A", registerType: "read", address: 198, valueKind: "S_DWORD" },
  { paramKey: "n_a_22", label: "n.a.", unit: "A", registerType: "read", address: 200, valueKind: "S_DWORD" },
  { paramKey: "n_a_23", label: "n.a.", unit: "A", registerType: "read", address: 202, valueKind: "S_DWORD" },
  { paramKey: "n_a_24", label: "n.a.", unit: "A", registerType: "read", address: 204, valueKind: "S_DWORD" },
  { paramKey: "n_a_25", label: "n.a.", unit: "A", registerType: "read", address: 206, valueKind: "S_DWORD" },
  { paramKey: "n_a_26", label: "n.a.", unit: "A", registerType: "read", address: 208, valueKind: "S_DWORD" },
  { paramKey: "n_a_27", label: "n.a.", unit: "A", registerType: "read", address: 210, valueKind: "S_DWORD" },
  { paramKey: "n_a_28", label: "n.a.", unit: "A", registerType: "read", address: 212, valueKind: "S_DWORD" },
  { paramKey: "va_dmd", label: "VA DMD", unit: "VA", registerType: "read", address: 214, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "va_dmd_max", label: "VA DMD MAX", unit: "VA", registerType: "read", address: 216, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "va_max", label: "VA max", unit: "VA", registerType: "read", address: 218, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "run_hour_meter_kwh_2", label: "Run hour meter kWh (-)", unit: "h", registerType: "read", address: 246, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "n_a_29", label: "n.a.", unit: "A", registerType: "read", address: 248, valueKind: "S_DWORD" },
  { paramKey: "n_a_30", label: "n.a.", unit: "A", registerType: "read", address: 250, valueKind: "S_DWORD" },
  { paramKey: "n_a_31", label: "n.a.", unit: "A", registerType: "read", address: 252, valueKind: "S_DWORD" },
  { paramKey: "run_hour_meter_2", label: "Run hour meter", unit: "h", registerType: "read", address: 254, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "n_a_32", label: "n.a.", unit: "A", registerType: "read", address: 256, valueKind: "S_DWORD" },
  { paramKey: "v_l_n_sys_2", label: "V L-N sys", unit: "V", registerType: "read", address: 258, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "v_l_l_sys", label: "V L-L sys", unit: "V", registerType: "read", address: 260, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "w_sys_2", label: "W sys", unit: "W", registerType: "read", address: 262, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "va_sys_2", label: "VA sys", unit: "VA", registerType: "read", address: 264, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "var_sys_2", label: "var sys", unit: "var", registerType: "read", address: 266, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "pf_sys_2", label: "PF sys", registerType: "read", address: 268, valueKind: "S_DWORD" },
  { paramKey: "phase_sequence_2", label: "Phase sequence", registerType: "read", address: 270, valueKind: "S_DWORD" },
  { paramKey: "hz_2", label: "Hz", unit: "Hz", registerType: "read", address: 272, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "kwh_tot_3", label: "kWh (+) TOT", unit: "kWh", registerType: "read", address: 274, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "kvarh_tot_3", label: "Kvarh (+) TOT", unit: "kvarh", registerType: "read", address: 276, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "kwh_tot_4", label: "kWh (-) TOT", unit: "kWh", registerType: "read", address: 278, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "kvarh_tot_4", label: "kvarh (-) TOT", unit: "kvarh", registerType: "read", address: 280, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "n_a_33", label: "n.a.", unit: "A", registerType: "read", address: 281, valueKind: "S_DWORD" },
  { paramKey: "w_sys_dmd_2", label: "W sys DMD", unit: "W", registerType: "read", address: 282, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "w_sys_dmd_max_3", label: "W sys DMD MAX", unit: "W", registerType: "read", address: 284, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "v_l1_l2_2", label: "V L1-L2", unit: "V", registerType: "read", address: 286, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "v_l1_n_2", label: "V L1-N", unit: "V", registerType: "read", address: 288, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "a_l1_2", label: "A L1", unit: "A", registerType: "read", address: 290, valueKind: "S_DWORD", scale: 0.001, precision: 3 },
  { paramKey: "w_l1_2", label: "W L1", unit: "W", registerType: "read", address: 292, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "va_l1_2", label: "VA L1", unit: "VA", registerType: "read", address: 294, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "var_l1_2", label: "var L1", unit: "var", registerType: "read", address: 296, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "pf_l1_2", label: "PF L1", registerType: "read", address: 298, valueKind: "S_DWORD" },
  { paramKey: "v_l2_l3_2", label: "V L2-L3", unit: "V", registerType: "read", address: 300, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "v_l2_n_2", label: "V L2-N", unit: "V", registerType: "read", address: 302, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "a_l2", label: "A L2", unit: "A", registerType: "read", address: 304, valueKind: "S_DWORD", scale: 0.001, precision: 3 },
  { paramKey: "w_l2", label: "W L2", unit: "W", registerType: "read", address: 306, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "va_l2", label: "VA L2", unit: "VA", registerType: "read", address: 308, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "var_l2", label: "var L2", unit: "var", registerType: "read", address: 310, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "pf_l2_2", label: "PF L2", registerType: "read", address: 312, valueKind: "S_DWORD" },
  { paramKey: "v_l3_l1_2", label: "V L3-L1", unit: "V", registerType: "read", address: 314, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "v_l3_n_2", label: "V L3-N", unit: "V", registerType: "read", address: 316, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "a_l3_2", label: "A L3", unit: "A", registerType: "read", address: 318, valueKind: "S_DWORD", scale: 0.001, precision: 3 },
  { paramKey: "w_l3_2", label: "W L3", unit: "W", registerType: "read", address: 320, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "va_l3_2", label: "VA L3", unit: "VA", registerType: "read", address: 322, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "var_l3_2", label: "var L3", unit: "var", registerType: "read", address: 324, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "pf_l3_2", label: "PF L3", registerType: "read", address: 326, valueKind: "S_DWORD" },
  { paramKey: "kwh_partial_3", label: "kWh (+) PARTIAL", unit: "kWh", registerType: "read", address: 328, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "kvarh_partial_3", label: "Kvarh (+) PARTIAL", unit: "kvarh", registerType: "read", address: 330, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "kwh_l1_2", label: "kWh (+) L1", unit: "kWh", registerType: "read", address: 332, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "kwh_l2_2", label: "kWh (+) L2", unit: "kWh", registerType: "read", address: 334, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "kwh_l3_2", label: "kWh (+) L3", unit: "kWh", registerType: "read", address: 336, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "n_a_34", label: "n.a.", unit: "A", registerType: "read", address: 338, valueKind: "S_DWORD" },
  { paramKey: "n_a_35", label: "n.a.", unit: "A", registerType: "read", address: 340, valueKind: "S_DWORD" },
  { paramKey: "n_a_36", label: "n.a.", unit: "A", registerType: "read", address: 342, valueKind: "S_DWORD" },
  { paramKey: "n_a_37", label: "n.a.", unit: "A", registerType: "read", address: 344, valueKind: "S_DWORD" },
  { paramKey: "kwh_partial_4", label: "kWh (-) PARTIAL", unit: "kWh", registerType: "read", address: 346, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "kvarh_partial_4", label: "Kvarh (-) PARTIAL", unit: "kvarh", registerType: "read", address: 348, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "kvah_tot_2", label: "kVAh TOT", unit: "kVAh", registerType: "read", address: 350, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "kvah_partial_2", label: "kVAh PARTIAL", unit: "kVAh", registerType: "read", address: 352, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "wsys_max_value", label: "Wsys MAX Value", registerType: "read", address: 354, valueKind: "S_DWORD" },
  { paramKey: "n_a_38", label: "n.a.", unit: "A", registerType: "read", address: 356, valueKind: "S_DWORD" },
  { paramKey: "n_a_39", label: "n.a.", unit: "A", registerType: "read", address: 358, valueKind: "S_DWORD" },
  { paramKey: "n_a_40", label: "n.a.", unit: "A", registerType: "read", address: 360, valueKind: "S_DWORD" },
  { paramKey: "n_a_41", label: "n.a.", unit: "A", registerType: "read", address: 362, valueKind: "S_DWORD" },
  { paramKey: "n_a_42", label: "n.a.", unit: "A", registerType: "read", address: 364, valueKind: "S_DWORD" },
  { paramKey: "n_a_43", label: "n.a.", unit: "A", registerType: "read", address: 366, valueKind: "S_DWORD" },
  { paramKey: "n_a_44", label: "n.a.", unit: "A", registerType: "read", address: 368, valueKind: "S_DWORD" },
  { paramKey: "n_a_45", label: "n.a.", unit: "A", registerType: "read", address: 370, valueKind: "S_DWORD" },
  { paramKey: "n_a_46", label: "n.a.", unit: "A", registerType: "read", address: 372, valueKind: "S_DWORD" },
  { paramKey: "n_a_47", label: "n.a.", unit: "A", registerType: "read", address: 374, valueKind: "S_DWORD" },
  { paramKey: "n_a_48", label: "n.a.", unit: "A", registerType: "read", address: 376, valueKind: "S_DWORD" },
  { paramKey: "n_a_49", label: "n.a.", unit: "A", registerType: "read", address: 378, valueKind: "S_DWORD" },
  { paramKey: "n_a_50", label: "n.a.", unit: "A", registerType: "read", address: 380, valueKind: "S_DWORD" },
  { paramKey: "n_a_51", label: "n.a.", unit: "A", registerType: "read", address: 382, valueKind: "S_DWORD" },
  { paramKey: "thd_a_l1_2", label: "THD A L1", unit: "%", registerType: "read", address: 384, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "thd_v_l1_n_2", label: "THD V L1-N", unit: "%", registerType: "read", address: 386, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "thd_v_l1_l2_2", label: "THD V L1-L2", unit: "%", registerType: "read", address: 388, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "i1_dmd_value_2", label: "I1 DMD Value", unit: "A", registerType: "read", address: 390, valueKind: "S_DWORD", scale: 0.001, precision: 3 },
  { paramKey: "i1_dmdmax_value_2", label: "I1 DMDMAX Value", unit: "A", registerType: "read", address: 392, valueKind: "S_DWORD", scale: 0.001, precision: 3 },
  { paramKey: "i1_max_value_2", label: "I1 MAX Value", unit: "A", registerType: "read", address: 394, valueKind: "S_DWORD", scale: 0.001, precision: 3 },
  { paramKey: "w1_dmd_value_2", label: "W1 DMD Value", unit: "W", registerType: "read", address: 396, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "w1_dmdmax_value_2", label: "W1 DMDMAX Value", unit: "W", registerType: "read", address: 398, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "w1_max_value_2", label: "W1 MAX Value", unit: "W", registerType: "read", address: 400, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "thd_a_l2_2", label: "THD A L2", unit: "%", registerType: "read", address: 402, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "thd_v_l2_n_2", label: "THD V L2-N", unit: "%", registerType: "read", address: 404, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "thd_v_l2_l3_2", label: "THD V L2-L3", unit: "%", registerType: "read", address: 406, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "i2_dmd_value_2", label: "I2 DMD Value", unit: "A", registerType: "read", address: 408, valueKind: "S_DWORD", scale: 0.001, precision: 3 },
  { paramKey: "i2_dmdmax_value_2", label: "I2 DMDMAX Value", unit: "A", registerType: "read", address: 410, valueKind: "S_DWORD", scale: 0.001, precision: 3 },
  { paramKey: "i2_max_value_2", label: "I2 MAX Value", unit: "A", registerType: "read", address: 412, valueKind: "S_DWORD", scale: 0.001, precision: 3 },
  { paramKey: "w2_dmd_value_2", label: "W2 DMD Value", unit: "W", registerType: "read", address: 414, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "w2_dmdmax_value_2", label: "W2 DMDMAX Value", unit: "W", registerType: "read", address: 416, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "w2_max_value_2", label: "W2 MAX Value", unit: "W", registerType: "read", address: 418, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "thd_a_l3_2", label: "THD A L3", unit: "%", registerType: "read", address: 420, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "thd_v_l3_n_2", label: "THD V L3-N", unit: "%", registerType: "read", address: 422, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "thd_v_l3_l1_2", label: "THD V L3-L1", unit: "%", registerType: "read", address: 424, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "i3_dmd_value_2", label: "I3 DMD Value", unit: "A", registerType: "read", address: 426, valueKind: "S_DWORD", scale: 0.001, precision: 3 },
  { paramKey: "i3_dmdmax_value_2", label: "I3 DMDMAX Value", unit: "A", registerType: "read", address: 428, valueKind: "S_DWORD", scale: 0.001, precision: 3 },
  { paramKey: "i3_max_value_2", label: "I3 MAX Value", unit: "A", registerType: "read", address: 430, valueKind: "S_DWORD", scale: 0.001, precision: 3 },
  { paramKey: "w3_dmd_value_2", label: "W3 DMD Value", unit: "W", registerType: "read", address: 432, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "w3_dmdmax_value_2", label: "W3 DMDMAX Value", unit: "W", registerType: "read", address: 434, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "w3_max_value_2", label: "W3 MAX Value", unit: "W", registerType: "read", address: 436, valueKind: "S_DWORD", scale: 0.1, precision: 1 },
  { paramKey: "digital_output_status", label: "Digital output status", registerType: "read", address: 773, valueKind: "S_WORD" },
  { paramKey: "alarm_status", label: "Alarm status", registerType: "read", address: 774, valueKind: "S_WORD" },
  { paramKey: "kwh_tot_5", label: "kWh (+) TOT", unit: "kWh", registerType: "read", address: 1280, valueKind: "S_QWORD", scale: 0.001, precision: 3 },
  { paramKey: "kvarh_tot_5", label: "Kvarh (+) TOT", unit: "kvarh", registerType: "read", address: 1284, valueKind: "S_QWORD", scale: 0.001, precision: 3 },
  { paramKey: "kwh_partial_5", label: "kWh (+) PARTIAL", unit: "kWh", registerType: "read", address: 1288, valueKind: "S_QWORD", scale: 0.001, precision: 3 },
  { paramKey: "kvarh_partial_5", label: "Kvarh (+) PARTIAL", unit: "kvarh", registerType: "read", address: 1292, valueKind: "S_QWORD", scale: 0.001, precision: 3 },
  { paramKey: "kwh_l1_3", label: "kWh (+) L1", unit: "kWh", registerType: "read", address: 1296, valueKind: "S_QWORD" },
  { paramKey: "kwh_l3_3", label: "kWh (+) L3", unit: "kWh", registerType: "read", address: 1304, valueKind: "S_QWORD" },
  { paramKey: "kwh_tot_6", label: "kWh (-) TOT", unit: "kWh", registerType: "read", address: 1308, valueKind: "S_QWORD", scale: 0.001, precision: 3 },
  { paramKey: "kwh_partial_6", label: "kWh (-) PARTIAL", unit: "kWh", registerType: "read", address: 1312, valueKind: "S_QWORD", scale: 0.001, precision: 3 },
  { paramKey: "kvarh_tot_6", label: "kvarh (-) TOT", unit: "kvarh", registerType: "read", address: 1316, valueKind: "S_QWORD", scale: 0.001, precision: 3 },
  { paramKey: "kvarh_partial_6", label: "kvarh (-) Partial", unit: "kvarh", registerType: "read", address: 1320, valueKind: "S_QWORD", scale: 0.001, precision: 3 },
  { paramKey: "kvah_tot_3", label: "kVAh TOT", unit: "kVAh", registerType: "read", address: 1324, valueKind: "S_QWORD", scale: 0.001, precision: 3 },
  { paramKey: "kvah_partial_3", label: "kVAh PARTIAL", unit: "kVAh", registerType: "read", address: 1328, valueKind: "S_QWORD", scale: 0.001, precision: 3 },
  { paramKey: "run_hour_meter_3", label: "Run hour meter", unit: "h", registerType: "read", address: 1332, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "run_hour_meter_kwh_3", label: "Run hour meter kWh (-)", unit: "h", registerType: "read", address: 1334, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "run_hour_meter_partial_2", label: "Run hour meter PARTIAL", unit: "h", registerType: "read", address: 1336, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "run_hour_meter_kwh_partial_2", label: "Run hour meter kWh (-) PARTIAL", unit: "h", registerType: "read", address: 1338, valueKind: "S_DWORD", scale: 0.01, precision: 2 },
  { paramKey: "hz_3", label: "Hz", unit: "Hz", registerType: "read", address: 1340, valueKind: "S_DWORD", scale: 0.001, precision: 3 },
  { paramKey: "major_minor_and_revision", label: "Major, Minor and Revision", registerType: "read", address: 770, valueKind: "U_WORD" },
  { paramKey: "reserved", label: "Reserved", registerType: "read", address: 771, valueKind: "U_WORD" },
  { paramKey: "carlo_gavazzi_controls_identification_code", label: "Carlo Gavazzi Controls identification code", registerType: "read", address: 11, valueKind: "U_WORD" },
  { paramKey: "password", label: "PASSWORD", registerType: "read", address: 4096, valueKind: "U_WORD" },
  { paramKey: "measuring_system", label: "Measuring system", registerType: "read", address: 4098, valueKind: "U_WORD" },
  { paramKey: "current_transformer_ratio", label: "Current transformer ratio", registerType: "read", address: 4099, valueKind: "U_DWORD" },
  { paramKey: "integration_time_for_dmd_power_calculation", label: "Integration time for DMD power calculation", registerType: "read", address: 4112, valueKind: "U_DWORD" },
  { paramKey: "pulse_output_duration_ton", label: "Pulse output duration (Ton)", registerType: "read", address: 4114, valueKind: "U_WORD" },
  { paramKey: "reserved_2", label: "Reserved", registerType: "read", address: 4115, valueKind: "U_WORD" },
  { paramKey: "alarm_enable", label: "Alarm Enable", registerType: "read", address: 4116, valueKind: "U_WORD" },
  { paramKey: "alarm_linked", label: "Alarm linked", registerType: "read", address: 4117, valueKind: "U_WORD" },
  { paramKey: "alarm_setpoint1_on", label: "Alarm SetPoint1 (on)", registerType: "read", address: 4118, valueKind: "S_DWORD" },
  { paramKey: "alarm_setpoint2_off", label: "Alarm SetPoint2 (off)", registerType: "read", address: 4120, valueKind: "S_DWORD" },
  { paramKey: "delay", label: "Delay", registerType: "read", address: 4122, valueKind: "U_WORD" },
  { paramKey: "reserved_3", label: "Reserved", registerType: "read", address: 4123, valueKind: "U_WORD" },
  { paramKey: "reserved_4", label: "Reserved", registerType: "read", address: 4124, valueKind: "U_WORD" },
  { paramKey: "reserved_5", label: "Reserved", registerType: "read", address: 4125, valueKind: "U_WORD" },
  { paramKey: "output_type", label: "Output Type", registerType: "read", address: 4126, valueKind: "U_WORD" },
  { paramKey: "output_normal_status", label: "Output normal status", registerType: "read", address: 4127, valueKind: "U_WORD" },
  { paramKey: "kwh_per_pulse", label: "kWh per pulse", unit: "kWh", registerType: "read", address: 4128, valueKind: "U_DWORD" },
  { paramKey: "quick_set_up_at_next_power_on", label: "Quick set up at next power on", registerType: "read", address: 4361, valueKind: "U_WORD" },
  { paramKey: "check_connection_at_next_power_on", label: "Check connection at next power on", registerType: "read", address: 4362, valueKind: "U_WORD" },
  { paramKey: "input_1_voltage_configuration", label: "Input 1 Voltage configuration", registerType: "read", address: 4432, valueKind: "U_WORD" },
  { paramKey: "input_2_voltage_configuration", label: "Input 2 Voltage configuration", registerType: "read", address: 4433, valueKind: "U_WORD" },
  { paramKey: "input_3_voltage_configuration", label: "Input 3 Voltage configuration", registerType: "read", address: 4434, valueKind: "U_WORD" },
  { paramKey: "input_1_current_configuration", label: "Input 1 Current configuration", registerType: "read", address: 4435, valueKind: "U_WORD" },
  { paramKey: "input_2_current_configuration", label: "Input 2 Current configuration", registerType: "read", address: 4436, valueKind: "U_WORD" },
  { paramKey: "input_3_current_configuration", label: "Input 3 Current configuration", registerType: "read", address: 4437, valueKind: "U_WORD" },
  { paramKey: "input_1_current_direction", label: "Input 1 Current direction", registerType: "read", address: 4438, valueKind: "U_WORD" },
  { paramKey: "input_2_current_direction", label: "Input 2 Current direction", registerType: "read", address: 4439, valueKind: "U_WORD" },
  { paramKey: "input_3_current_direction", label: "Input 3 Current direction", registerType: "read", address: 4440, valueKind: "U_WORD" },
  { paramKey: "pages_filter_enable", label: "Pages filter enable", registerType: "read", address: 5632, valueKind: "U_WORD" },
  { paramKey: "inactivity_time_enable", label: "Inactivity Time enable", registerType: "read", address: 5633, valueKind: "U_WORD" },
  { paramKey: "screen_saver_time", label: "Screen Saver time", registerType: "read", address: 5634, valueKind: "U_WORD" },
  { paramKey: "home_page", label: "Home page", registerType: "read", address: 5635, valueKind: "U_WORD" },
  { paramKey: "backlight_time", label: "Backlight Time", registerType: "read", address: 5636, valueKind: "U_WORD" },
  { paramKey: "page_1", label: "Page 1", registerType: "read", address: 5648, valueKind: "U_WORD" },
  { paramKey: "page_2", label: "Page 2", registerType: "read", address: 5649, valueKind: "U_WORD" },
  { paramKey: "page_3", label: "Page 3", registerType: "read", address: 5650, valueKind: "U_WORD" },
  { paramKey: "page_4", label: "Page 4", registerType: "read", address: 5651, valueKind: "U_WORD" },
  { paramKey: "page_5", label: "Page 5", registerType: "read", address: 5652, valueKind: "U_WORD" },
  { paramKey: "page_6", label: "Page 6", registerType: "read", address: 5653, valueKind: "U_WORD" },
  { paramKey: "page_7", label: "Page 7", registerType: "read", address: 5654, valueKind: "U_WORD" },
  { paramKey: "page_8", label: "Page 8", registerType: "read", address: 5655, valueKind: "U_WORD" },
  { paramKey: "page_9", label: "Page 9", registerType: "read", address: 5656, valueKind: "U_WORD" },
  { paramKey: "page_10", label: "Page 10", registerType: "read", address: 5657, valueKind: "U_WORD" },
  { paramKey: "page_11", label: "Page 11", registerType: "read", address: 5658, valueKind: "U_WORD" },
  { paramKey: "page_12", label: "Page 12", registerType: "read", address: 5659, valueKind: "U_WORD" },
  { paramKey: "page_13", label: "Page 13", registerType: "read", address: 5660, valueKind: "U_WORD" },
  { paramKey: "page_14", label: "Page 14", registerType: "read", address: 5661, valueKind: "U_WORD" },
  { paramKey: "page_15", label: "Page 15", registerType: "read", address: 5662, valueKind: "U_WORD" },
  { paramKey: "page_16", label: "Page 16", registerType: "read", address: 5663, valueKind: "U_WORD" },
  { paramKey: "page_17", label: "Page 17", registerType: "read", address: 5664, valueKind: "U_WORD" },
  { paramKey: "page_18", label: "Page 18", registerType: "read", address: 5665, valueKind: "U_WORD" },
  { paramKey: "page_19", label: "Page 19", registerType: "read", address: 5666, valueKind: "U_WORD" },
  { paramKey: "page_20", label: "Page 20", registerType: "read", address: 5667, valueKind: "U_WORD" },
  { paramKey: "page_21", label: "Page 21", registerType: "read", address: 5668, valueKind: "U_WORD" },
  { paramKey: "page_22", label: "Page 22", registerType: "read", address: 5669, valueKind: "U_WORD" },
  { paramKey: "page_23", label: "Page 23", registerType: "read", address: 5670, valueKind: "U_WORD" },
  { paramKey: "page_24", label: "Page 24", registerType: "read", address: 5671, valueKind: "U_WORD" },
  { paramKey: "page_25", label: "Page 25", registerType: "read", address: 5672, valueKind: "U_WORD" },
  { paramKey: "page_26", label: "Page 26", registerType: "read", address: 5673, valueKind: "U_WORD" },
  { paramKey: "rs485_stop_bit", label: "RS485 Stop bit", registerType: "read", address: 8195, valueKind: "U_WORD" },
  { paramKey: "reset_of_dmd_dmd_max_and_max_value", label: "Reset of DMD, DMD max and max value", registerType: "read", address: 16389, valueKind: "U_WORD" },
  { paramKey: "factory_setting_restore_default", label: "Factory setting (Restore default)", registerType: "read", address: 16416, valueKind: "U_WORD" },
  { paramKey: "letter_13_from_sx", label: "Letter 13 (from SX)", registerType: "read", address: 20486, valueKind: "U_WORD" },
  { paramKey: "production_year", label: "Production year", registerType: "read", address: 20487, valueKind: "U_WORD" },
  { paramKey: "name_configurable", label: "Name Configurable", registerType: "read", address: 20488, valueKind: "U_WORD" },
  { paramKey: "name_configurable_2", label: "Name Configurable", registerType: "read", address: 20489, valueKind: "U_WORD" },
  { paramKey: "name_configurable_3", label: "Name Configurable", registerType: "read", address: 20490, valueKind: "U_WORD" },
  { paramKey: "name_configurable_4", label: "Name Configurable", registerType: "read", address: 20491, valueKind: "U_WORD" },
  { paramKey: "name_configurable_5", label: "Name Configurable", registerType: "read", address: 20492, valueKind: "U_WORD" },
  { paramKey: "name_configurable_6", label: "Name Configurable", registerType: "read", address: 20493, valueKind: "U_WORD" },
  { paramKey: "name_configurable_7", label: "Name Configurable", registerType: "read", address: 20494, valueKind: "U_WORD" },
  { paramKey: "name_configurable_8", label: "Name Configurable", registerType: "read", address: 20495, valueKind: "U_WORD" },
  { paramKey: "instrument_secondary_address", label: "Instrument secondary address", registerType: "read", address: 20496, valueKind: "U_DWORD" },
  { paramKey: "device_state", label: "Device state", registerType: "read", address: 20498, valueKind: "U_WORD" },
];
