import type { DriverDefinition } from './driverStore.js';

export function builtinDrivers(): DriverDefinition[] {
  const now = new Date().toISOString();
  const base = {
    createdAt: now,
    updatedAt: now,
    recommendedPollMs: 1000,
  } satisfies Pick<DriverDefinition, 'createdAt' | 'updatedAt' | 'recommendedPollMs'>;

  return [
    // --- Meters ---
    {
      ...base,
      id: 'em500_grid',
      name: 'EM500 (Grid meter)',
      vendor: 'Rozwell / EM500 family',
      deviceType: 'meter',
      notes:
        'Built-in baseline EM500 grid meter driver. For full validated mapping see Modular_Yaml/meter_em500_grid.yaml. You can override by saving a driver with the same id.',
      registers: [
        { paramKey: 'freq_hz', label: 'Frequency', unit: 'Hz', registerType: 'read', address: 0x0032, valueKind: 'U_DWORD', scale: 0.01, precision: 2 },
        { paramKey: 'p_total_kw', label: 'Total Active Power', unit: 'kW', registerType: 'read', address: 0x003a, valueKind: 'S_DWORD', scale: 0.01, precision: 2 },
        { paramKey: 'v_eq_v', label: 'Equivalent Voltage', unit: 'V', registerType: 'read', address: 0x0034, valueKind: 'U_DWORD', scale: 0.01, precision: 2 },
        { paramKey: 'i_eq_a', label: 'Equivalent Current', unit: 'A', registerType: 'read', address: 0x0038, valueKind: 'U_DWORD', scale: 0.0001, precision: 4 },
      ],
    },
    {
      ...base,
      id: 'em500_v2',
      name: 'EM500 Meter v2 (template)',
      vendor: 'Rozwell / EM500 family',
      deviceType: 'meter',
      notes: 'Template for EM500-compatible variants. Start here, then tune registers as needed.',
      registers: [],
    },
    {
      ...base,
      id: 'em500_generator',
      name: 'EM500 Generator meter (template)',
      vendor: 'Rozwell / EM500 family',
      deviceType: 'meter',
      notes: 'Template for generator-side metering using EM500 family devices.',
      registers: [],
    },
    {
      ...base,
      id: 'wm15',
      name: 'Carlo Gavazzi WM15 (template)',
      vendor: 'Carlo Gavazzi',
      deviceType: 'meter',
      notes: 'Template only. Register references are in docs/Energy Analyzer/. Tune registers per your site.',
      registers: [],
    },
    {
      ...base,
      id: 'kpm37',
      name: 'KPM37 Rail meter (template)',
      vendor: 'KPM37',
      deviceType: 'meter',
      notes: 'Template only. Add parameters from the manual in docs/Energy Analyzer/.',
      registers: [],
    },
    {
      ...base,
      id: 'iskra_mc3',
      name: 'Iskra MC3x0x (template)',
      vendor: 'Iskra',
      deviceType: 'meter',
      notes: 'Template only. Add parameters from the Iskra user manual in docs/Energy Analyzer/.',
      registers: [],
    },
    {
      ...base,
      id: 'm4m',
      name: 'M4M (template)',
      vendor: 'M4M',
      deviceType: 'meter',
      notes: 'Template only. Use the Modbus map spreadsheet in docs/Energy Analyzer/ as source.',
      registers: [],
    },
    {
      ...base,
      id: 'gc_multiline',
      name: 'GC / DST4602 multiline (template)',
      vendor: 'GC / DST',
      deviceType: 'meter',
      notes: 'Template only. Add registers based on the multiline manual in docs/Energy Analyzer/.',
      registers: [],
    },
    {
      ...base,
      id: 'generic_modbus_meter',
      name: 'Generic Modbus meter (blank)',
      vendor: 'Generic',
      deviceType: 'meter',
      notes: 'Blank driver to quickly build a custom meter map (registers, scaling, byte/word order).',
      registers: [],
    },

    // --- Inverters ---
    {
      ...base,
      id: 'huawei_inverter',
      name: 'Huawei inverter (baseline)',
      vendor: 'Huawei',
      deviceType: 'inverter',
      notes:
        'Built-in baseline Huawei inverter driver (read path). For full mapping see Modular_Yaml/inverter_huawei.yaml. You can override by saving a driver with the same id.',
      registers: [
        { paramKey: 'p_ac_kw', label: 'Active Power', unit: 'kW', registerType: 'read', address: 32080, valueKind: 'U_DWORD', scale: 0.001, precision: 3 },
      ],
    },
    {
      ...base,
      id: 'huawei_smartlogger',
      name: 'Huawei SmartLogger (template)',
      vendor: 'Huawei',
      deviceType: 'inverter',
      notes: 'Template only. Populate registers based on your SmartLogger model/protocol.',
      registers: [],
    },
    {
      ...base,
      id: 'sma',
      name: 'SMA (template)',
      vendor: 'SMA',
      deviceType: 'inverter',
      notes: 'Template only. Use Modbus/SunSpec docs in docs/Inverter/SMA/.',
      registers: [],
    },
    {
      ...base,
      id: 'solaredge',
      name: 'SolarEdge (template)',
      vendor: 'SolarEdge',
      deviceType: 'inverter',
      notes: 'Template only. Use interface note in docs/Inverter/Solar edge/.',
      registers: [],
    },
    {
      ...base,
      id: 'growatt',
      name: 'Growatt (template)',
      vendor: 'Growatt',
      deviceType: 'inverter',
      notes: 'Template only. Add registers from the protocol PDF in docs/Inverter/.',
      registers: [],
    },
    {
      ...base,
      id: 'solax',
      name: 'Solax Hybrid G4 (template)',
      vendor: 'Solax',
      deviceType: 'inverter',
      notes: 'Template only. Add registers from docs/Inverter/Solax/.',
      registers: [],
    },
    {
      ...base,
      id: 'sungrow',
      name: 'Sungrow (template)',
      vendor: 'Sungrow',
      deviceType: 'inverter',
      notes: 'Template only. Add registers from the protocol PDF in docs/Inverter/.',
      registers: [],
    },
    {
      ...base,
      id: 'cps_chint',
      name: 'Chint / CPS (template)',
      vendor: 'Chint / CPS',
      deviceType: 'inverter',
      notes: 'Template only. Add registers from docs/Inverter/Chint/.',
      registers: [],
    },
    {
      ...base,
      id: 'knox_asw',
      name: 'Knox / ASW LT-G2 (template)',
      vendor: 'Knox / ASW',
      deviceType: 'inverter',
      notes: 'Template only. Add registers from docs/Inverter/Knox/.',
      registers: [],
    },
    {
      ...base,
      id: 'generic_modbus_inverter',
      name: 'Generic Modbus inverter (blank)',
      vendor: 'Generic',
      deviceType: 'inverter',
      notes: 'Blank driver to quickly build a custom inverter map (read registers first).',
      registers: [],
    },
  ];
}

